### ISSUE TITLE
include npm files for publishing

### ISSUE THREAD

**Issue by mg901** [semantic-release/semantic-release#1052]
I have a [project](https://github.com/typographist/core) I embedded a semantic-release into it. It generates a changelog and releases releases on gitHub, however I ran into two problems. First, despite the fact that the versions change to npm and github, the versions in ```package.json``` remain unchanged. Second: when publishing to npm there are no compiled files. Please tell me what am I doing wrong?

I explicitly indicated in ```package.json``` which files should be included in npm. 
```
  "files": [
    "lib",
    "es"
  ],
```

This is what I see when I download my package.
<img width="272" alt="screenshot 2018-12-27 at 23 55 30" src="https://user-images.githubusercontent.com/7874664/50494219-f9606f00-0a32-11e9-9384-fccbc0cba097.png">

there are no compiled files and the version in ```package.json``` is different from the one that is currently listed on gitHub

**Comment by pvdlg** [comment]
When you want to ask questions or ask for help please use the [Spectrum community](https://spectrum.chat/semantic-release) as mentioned in [Using the issue tracker](https://github.com/semantic-release/semantic-release/blob/master/CONTRIBUTING.md#using-the-issue-tracker).

Please also read take a look at [the documentation](https://github.com/semantic-release/semantic-release/tree/master/docs) as well as the plugins documentation.

You can find the answer to your question reagarding the `package.json` not being committed to GitHub in [the first example of the `@semantic-release/git` example](https://github.com/semantic-release/git#examples).

Your compiled file are not included in the published package simply because you are not running your [build script](https://github.com/typographist/core/blob/master/package.json#L8) on your CI, so those file do not exist when **semantic-release** publishes your package.
