### ISSUE TITLE
migration guide from travis-deploy-once to build stages

### ISSUE THREAD

**Issue by boneskull** [semantic-release/semantic-release#1065]
## New feature motivation

I had been used to `semantic-release-cli setup` blasting my `.travis.yml` with its configuration, and was surprised to see that it's now directing me to [the documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md).

My projects using `semantic-release`, until today, *all* use `travis-deploy-once`.

## New feature description

A migration guide (probably just a few list items) should be added to this documentation which describes how to move away from `travis-deploy-once` to Travis-CI build stages.

Alternatively, prompt the user to append the `deploy` stage to `.travis.yml`.  I have a feeling the provided `deploy` stage would be safe to append to `.travis.yml` in the general case.  It would be problematic if jobs are already defined, but that's not too difficult to detect.

`semantic-release` is all about the power of automation, so it's surprising to have to configure CI manually.  :wink:

Thanks for the great work!

**Comment by pvdlg** [comment]
Unfortunately that's no so simple as we can't assume the current configuration in the `.travis.yml`. Many jobs could already exists for example.

In the large majority of cases you can just replace your `.travis.yml` by what's in the documentation linked. But if we provide a step by step doc that will create problems for some users with a different configuration.

Generally, speaking you have to understand how your CI configuration work and how to split and orchestrate your jobs, because each project is different. You might want to run 2 test jobs each running half of your tests to speed up the build, or you might want to run a different test command based on the Node version or the platform etc... We could add docs in this project explaining all that, but it will never be as good and as complete as the docs of each CI provider. 

We used to have a more detailed and opinionated CI configuration documentation in the past. It only generated a lot of noise on the issue tracker with people either giving their opinion about CI best practices or having issues due to something specific in their project. 

So we provide examples and we clearly state that semantic-release should run after all your tests. But that's up to you to figure out what's the best solution for your project. At some point we might rework the setup CLI to be smarter and try to guess the best configuration, but I don't know if the effort is worth the benefits.
