### ISSUE TITLE
Pluggable authentication

### ISSUE THREAD

**Issue by dominykas** [semantic-release/semantic-release#1093]
## New feature motivation

Providing tokens via env is not always feasible (there are environments where this is locked down, to avoid surprise leaks).

## New feature description

Add a way to provide a custom authentication function via a plugin, e.g. it could try to read values from `vault`, or from e.g. [`~/.config/hub`](https://github.com/github/hub), or via keychain access, etc etc.

## New feature implementation

1. A new configuration option for "auth plugin"
2. When configured, instead of [looping through env vars](https://github.com/semantic-release/semantic-release/blob/master/lib/get-git-auth-url.js#L43), read the credentials from plugin.

Possibly the existing auth could move into a `@semantic-release/auth-default` plugin.

I spotted some of this is covered in https://github.com/semantic-release/semantic-release/issues/585, but that proposal is for a full blown app, whereas this is just a building block.

**Comment by pvdlg** [comment]
The only authentication required by semantic-release core is for the `git` CLI as we have to push a git tag. `git` already support a lot of authentication method including ssh keys, keychain or password files. So what you are requesting is already possible.

The other authentication configuration are related to the GitHub, GitLab and npm plugins. Each one has its own specificities. For example with `@semantic-release/npm` you could have a `.npmrc` file in your home folder with the credentials.

As semantic-release is meant to run on a CI, I'm not sure there is really a better way than environment variables. Having a file containing your credentials on the CI is effectively the same as having environment variable. Keychain is probably not available on the CI (or at least it would be empty).

Can you provide a detailed use case that is not currently possible and explain why it would be better than environment variables?

**Comment by dominykas** [comment]
> The other authentication configuration are related to the GitHub, GitLab and npm plugins.

Sorry, I suppose I missed this bit, because I was primarily focused on the `GH_TOKEN` not available error. So, yes, I'm currently interested in GitHub plugin auth.

> Having a file containing your credentials on the CI is effectively the same as having environment variable.

Assuming a single token is very much the model of Travis (and maybe Circle, etc), however I'm currently working on implementing this in Jenkins, with a rather custom setup. We already have the credentials available in `~/.config/hub` that we use for other purposes, and there's restrictions on what we can put in env vars. From the access perspective, a publicly accessible file is in effect the same as an env var, but on the other hand, you can't accidentally leak the token by running `env` or `console.log(process.env)` while debugging something unrelated.

The other example I gave is `vault`. While at run time, as part of a CI job, the token is easily accessible, it generally rests in a controlled, encrypted environment. In certain environments this is important.

> Keychain is probably not available on the CI (or at least it would be empty).

While keychain is debatable (as this is meant for CI), it would be extremely handy when you're trying to debug or try out things locally (`--dry-run`, etc). This would be primarily a usability feature. I work daily with public GitHub and with GitHub Enterprise. They naturally have a different token, therefore a single `GH_TOKEN` env var does not suit me - I'd have to switch it every time I change repos.

> Can you provide a detailed use case that is not currently possible and explain why it would be better than environment variables?

I hope the above explains some of what I'm looking for. I agree with the sentiment that env vars suit most needs, yet I can't even control the env vars or job configurations in our CI environment (for various, mostly reasonable, compliance needs).

I do have the workaround of reading the file and setting the environment variables at build time via a custom script, but that is a little fiddly, and writing a `hub` auth plugin would also solve my local debug use cases.

**Comment by pvdlg** [comment]
> Assuming a single token is very much the model of Travis (and maybe Circle, etc), however I'm currently working on implementing this in Jenkins, with a rather custom setup. We already have the credentials available in `~/.config/hub` that we use for other purposes, and there's restrictions on what we can put in env vars. From the access perspective, a publicly accessible file is in effect the same as an env var, but on the other hand, you can't accidentally leak the token by running `env` or `console.log(process.env)` while debugging something unrelated.

Inability of setting an environment variable and using a file to store credentials seems to be a very specific use case and it doesn't it would benefit any other user. So I would suggest to implement your own fork of `@semantic-release/github` or to run a script that read the file and set the environment variable.

Leaking the credentials with `env` or `console.log(process.env)` is generally not an issue because most CIs do not provide the environment variable when building a PR coming from a fork repo. So if someone fork your repo, add `console.log(process.env)` to the code and open a PR, the credential won't leak ass the won't be available.

Also debugging things is usually done locally not on the CI.

> The other example I gave is `vault`. While at run time, as part of a CI job, the token is easily accessible, it generally rests in a controlled, encrypted environment. In certain environments this is important.

I'm not familiar with what vault is. It seems a quite specific use case, so again I'd suggest to run your own fork of `@semantic-release/github` for that.

> While keychain is debatable (as this is meant for CI), it would be extremely handy when you're trying to debug or try out things locally (`--dry-run`, etc). This would be primarily a usability feature. I work daily with public GitHub and with GitHub Enterprise. They naturally have a different token, therefore a single `GH_TOKEN` env var does not suit me - I'd have to switch it every time I change repos.

There is several issues with such approach. First, how do add the token to the keychain in the first place? That would require semantic-release to ask the user for the token if not found in the keychain. Which is a problem when running on a CI. There is certainly way to workaround that, but that's a lot of complexity added to semantic-release for few benefits.
Second, the keychain (at least on OSX and Windows) allow access based on process name. So if you add a token to the keychain with any Node app, any other Node app can access it, which is a big security issue. See https://github.com/atom/node-keytar/issues/88

If you want to test locally with different tokens I would suggest to either:
- Use https://direnv.net/ so you can have a different token for each directory automatically set
- Just run the command `GH_TOKEN=XXXX semantic-release --dry-run`

**Comment by dominykas** [comment]
While I do agree that my use cases are specific and I do understand that adding more functionality is a burden, as a user I feel that such a burden is significantly less than a burden of maintaining a full blown fork. Because that's what users do - feel that maintainer's work is easier than their own ;)

What I'm proposing, is providing a hook, a way to define a function, which returns the token, as opposed to only reading it from env. If you feel this does not tie into the architecture or bloats the code - I suppose it's your duty to say "no".

That said, if this can't be implemented on `semantic-release` side, do you think it would be reasonable to have a plugin, which loads first, before any other plugins, and writes the token directly into `process.env` (from whatever source it likes)? A bit hacky, but in effect the same as setting it to env from outside `semantic-release`, but the benefit is that you only need to configure it once, inside the `package.json`, as opposed to changing build scripts.

**Comment by dominykas** [comment]
Doesn't feel like I'll get any traction on this one, so I'll keep on working around for now.
