### ISSUE TITLE
The authenticity of host 'github.com can't be established

### ISSUE THREAD

**Issue by raulingg** [semantic-release/semantic-release#1095]
## Current behavior

When I run "npx semantic release" on CircleCI it asks for "github.com" connection established after that my CI job is truncated, which is rare because before I ran it on CircleCI for a previous workflow and everything works fine without that issue. 

## Expected behavior

it must follow the normal process

## Environment

- **semantic-release** version: 15.13.3, I'm using "npx semantic release" in CircleCI

- CI environment: CircleCI

- Plugins used: 
```
    @semantic-release/changelog": "^3.0.2",
    "@semantic-release/commit-analyzer": "^6.1.0",
    "@semantic-release/git": "^7.0.8",
    "@semantic-release/github": "^5.2.9",
    "@semantic-release/release-notes-generator": "^7.1.4"
```

- **semantic-release** configuration: 
```
module.exports = {
  branch: 'master',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    [
      '@semantic-release/github',
      {
        assets: ['build/**']
      }
    ],
    '@semantic-release/git'
  ]
}
```
- CI logs: 
```sh
#!/bin/bash -eo pipefail
npx semantic-release
[8:52:42 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[8:52:42 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[8:52:42 PM] [semantic-release] › ✔  Run automated release from branch master
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by raulingg** [comment]
Added a image 
![screenshot from 2019-02-08 15-53-30](https://user-images.githubusercontent.com/9435850/52506331-3c7a3a00-2bbc-11e9-9215-6417275bc98c.png)

**Comment by pvdlg** [comment]
semantic-release need to push tags to your git repo and uses the `git` CLI for that (`git tag vx.y.z` then `git push --tags`). Those command need to works for semantic-release being able to make the release.

I don't know why you get this error on CircleCI but there is not much we can do on semantic-release side. You can run semantic-release with `--debug` to have more detail about the `git` command that is ran.

It's probably related to the container you are using to run your CI job that somehow can't verify the authenticity of the `github.com` certificate.

**Comment by azdanov** [comment]
I've had similar issues, what helped is rerunning the workflow on CircleCI.

**Comment by azdanov** [comment]
Here is a hackish workaround:

```sh
mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
```

Add it before `npx semantic-release` step.

**Comment by travi** [comment]
its never a great idea to disable verification. it would be a much better idea to reach out to your ci service and have them investigate why the failure is happening.

**Comment by azdanov** [comment]
@travi Agreed. I migrated to Travis, no problems there.

**Comment by Jerska** [comment]
The fix for me was to change my `repository.url` field in my `package.json` to use the `https` version of my repo instead of the `git+ssh` one.

**Comment by gr2m** [comment]
> The fix for me was to change my `repository.url` field in my `package.json` to use the `https` version of my repo instead of the `git+ssh` one.

`semantic-release` should do this normalization already as far as I know. Can you share the exact change of `repository.url`?

**Comment by pvdlg** [comment]
If you set your `repository.url` to a  `git+ssh`, the `git` command triggered by semantic-release will use ssh. You will have this error if you don't configure ssh keys in your environment.

**Comment by Jerska** [comment]
Indeed, which is surprising as I believe the GH_TOKEN asked by the github plugin is necessarily supposed to be used for http auth.
I skimmed through the README to do my setup and the only thing I saw required was for me to setup this env var.
It would probably be a nice addition to transform such URLs when found.
Otherwise, I would have been happy also providing a GH_REPO env var, but the doc seems to state it’s only for github enterprise.

**Comment by Jerska** [comment]
@gr2m

> Can you share the exact change of repository.url?

https://github.com/algolia/renderscript/commit/a9983261164e9a32247111001c35e68e3b715072

**Comment by pvdlg** [comment]
That has been discussed many times in issues in this repo.
The `GH_TOKEN` is used to make GitHub API call in the `@sematnic-release/github` plugin.
semantic-release also run `git` commands that require authentication which can be done via ssh URL + ssh keys or via https URL + `GH_TOKEN`.
We support both type of authentication for `git` commands in order to accommodate the most workflows. And we let the user choose the method of authentication by letting them choose the URL format they set in `package.json#repository.url` or the semantic-release `repositoryUrl` option.

**Comment by Jerska** [comment]
I’m not at all blaming the implementation or you or the project.
But something is wrong somewhere, and it might just be my reading skills, or it might be some missing or misplaced docs.
If changing the implementation is not an option, a detection of the git prompt to send an helpful message would have been awesome.
Going through the docs, even on https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration , I saw nothing even remotely mentioning repositoryUrl . All it said was that I needed to setup GH_TOKEN.
Hopefully, the next people googling it like I did will find this issue, which is why I posted this message in the first place.

**Comment by pvdlg** [comment]
The reason is that we want to keep the documentation as simple and straight forward as we can.
So we mention the most case which is to use https and tokens.

For people who want to use ssh, we added a link to the specific [documentation for using ssh keys](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md).

Finding the right balance when it comes to documentation is quite difficult. On one side you want to be exhaustive, but you also want to be accessible. If you mention every specific case, and every details, you end up with a documentation that users won't read.

The immense majority of users:
- Are not aware that Git can access a repo with multiple protocol
- Are not aware that ssh keys are required to access a repo with ssh
- Have a `package.json#repository.url` created by `npm init` without having ever noticed it

Those users are not willing to spend more than 5 to 10 minutes reading the doc and configuring semantic-release. We don't want to bother them with ssh stuff. This is why we have this doc in a different page: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md.

If you want to use the less common way and use ssh, then it require a bit more effort and you'll have to go through the longer and more complex [ssh keys docs](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md).

**Comment by 3nvi** [comment]
Just faced the same issue with CircleCI. For me, the fix involved issuing a new key and replacing the existing `GH_TOKEN` with a newly generated one.

There could have been some sort of external change to our company's repo that I'm not aware of, I just wanted to share that this did the trick for me (in case anyone has tried all of the above)

**Comment by Anthropic** [comment]
@Jerska you saved me, took me a half day to find your comment, but I did, thank you!

> The fix for me was to change my `repository.url` field in my `package.json` to use the `https` version of my repo instead of the `git+ssh` one.

I would add though that my repository url was  `git@` not `git+ssh@` and I **still** needed to change it to `https`.
The break occurred when we had to update from `17.0.1` to `17.2.3`, was then able to go up to `17.4.3`.

**Comment by BBlackwo** [comment]
For me I had to manually execute these steps before running `semantic-release`:

```yml
- run: mkdir -p ~/.ssh      
- run: ssh-keyscan github.com >> ~/.ssh/known_hosts
```

This was based off of the Circle CI docs: https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host

See PR https://github.com/btroncone/ngrx-store-localstorage/pull/193
