### ISSUE TITLE
Maintenance branch - correct use ?

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1099]
Hi,

I wonder if anybody can help. I am using the latest beta and basically, I am releasing versions as features are checked into master. Let's say we decide that version 1.8 is the release that goes to production. While 1.8 is being tested a few problems are found. So the idea is to create a branch from this tag (1.8) called 1.8.x .   

The problem here is that if master has no other release in yet then the only version that can be deployed from the maintenance 1.8 is between 1.8 and 1.8. This is due to no other release being available in master - master latest is 1.8.

Is there some way of changing this behaviour?

Let's assume that master has 1.9 now, so technically the release allows me to apply fixes on top of the 1.8.x branch now....  up until 1.9.0 - so hence I have a possibility of 8 fixes in the maintenance branch (from 1.8.1 to 1.8.9).

I was wondering what other peoples strategy is here ?

Maybe I am not fully understanding it correctly.

If we plan on releasing version tag 1.8 to production then QA needs to test this version in the QA environment but they might find issues so my understanding is that if they do then i must release maintenance fixes (updating the patch) on top of 1.8.

I would really love some insight and ideas around the above issues that i have raised - these are probably issues for us but maybe not for others.

**Comment by pvdlg** [comment]
> The problem here is that if master has no other release in yet then the only version that can be deployed from the maintenance 1.8 is between 1.8 and 1.8. This is due to no other release being available in master - master latest is 1.8.
Is there some way of changing this behaviour?

This is by design. Why would create a `1.8.x` branch such case? If the last version released from `master` is `1.8.0` and you want to apply a fix on `1.8.0` then push that fix to `master`.

> Let's assume that master has 1.9 now, so technically the release allows me to apply fixes on top of the 1.8.x branch now.... up until 1.9.0 - so hence I have a possibility of 8 fixes in the maintenance branch (from 1.8.1 to 1.8.9).
I was wondering what other peoples strategy is here ?

That's not accurate. Semantic version are not limited to a single digit. If you would push 500 fixes sequentially you would end up with version `1.8.500`.

> If we plan on releasing version tag 1.8 to production then QA needs to test this version in the QA environment but they might find issues so my understanding is that if they do then i must release maintenance fixes (updating the patch) on top of 1.8.

Only if you released version 1.9 in the meantime. If not apply your fix on `master`.
Also if you are making non-production ready releases for QA purpose you should use pre-releases: https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/pre-releases.md
