### ISSUE TITLE
Using git-cli commands for remote repository actions

### ISSUE THREAD

**Issue by prime-optimus** [semantic-release/semantic-release#1122]
## Current behavior
There are various locations in code, like [this](https://github.com/semantic-release/semantic-release/blob/master/lib/git.js#L179) where SM reaches out to remote repo directly rather than using github API and github token.

I am using semantic-release in an enterprise Github installation and Drone CI. git-cli commands inside a plugin don't have access to remote repos. I have configured `GITHUB_TOKEN` properly in the environment variables. But because SM uses direct git-cli commands instead of going through github API it fails to work.

## Expected behavior
SM release should  not depend on git-cli credentials for remote repos and work fine with just `GITHUB_TOKEN`.

## Environment

- **semantic-release** version: semantic-release@beta (breaks with v15 too)
- CI environment: Drone CI
- Plugins used: Semantic-release github
- CI logs: `Password authentication is not available for remote operations.`

**Comment by pvdlg** [comment]
What is SM?

semantic-release uses the `git` CLI because not everyone uses GitHub. The `git` CLI is the most common way to access a git repo, including ones that doesn't provide an alternative API.

The releases on this GitHub repo are publish with semantic-release, so you can see that GitHub repositories are accessible via the `git` CLI.

According to the error message you have, it seems you have explicitly disabled remote operation authenticated via password. So obviously semantic-release won't work.

**Comment by pvdlg** [comment]
Closing as no response provided
