### ISSUE TITLE
Allow FIRST_RELEASE to be overridden

### ISSUE THREAD

**Issue by Aghassi** [semantic-release/semantic-release#1125]
## New feature motivation

We have teams that may not want to denote `1.0.0` in their project until they are ready for production. Is there a way I can specify the first release to always be `0.0.1` or something else instead of hard coding to 1.0.0?

The line I'm referring to is here https://github.com/semantic-release/semantic-release/blob/d6d1bc954e5f86fe8036702129f5b9807db81d08/lib/definitions/constants.js#L3

## New feature description

I'd like to be able to set (either through environment variables or through a constructor) the FIRST_RELEASE version, so it doesn't default to 1.0.0

## New feature implementation

1. Allow for an option https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/js-api.md#usage
2. take a flag for the CLI or a process.env for `FIRST_RELEASE` that allows me to set the version

**Comment by travi** [comment]
this is configured this way very intentionally, and i expect that it would be very unlikely to change. see https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0-0-1

that said, the recommended way to defer publishing a v1.0.0 is to publish pre-releases until you are ready to publish a "stable" or "functional" release (i mention both because "stable" implies more maturity than is encouraged). the beta version of semantic-release supports publishing pre-releases with basically no additional configuration, and i have found that approach to a be very effective alternative to v0.x.x

**Comment by Aghassi** [comment]
Yeah I was waiting on v16 to be able to do the pre-releasing, because that would solve my issue. I'm hesitant to take it in because I don't want to be caught in the middle of breaking changes. Also, there are no docs on how to use that yet are there? I need to learn more to understand how one can do `pre` and regular releases without issue.

**Comment by travi** [comment]
documentation is on the beta branch, with the features: https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/README.md#release-workflow

**Comment by travi** [comment]
fwiw, i've been using the beta successfully with a bunch of my projects and haven't had to add any special config other than naming my branches `alpha` or `beta`. the only other config i've changed is making sure that travis runs semantic-release on all branches instead of only master (because i use the deploy step).

**Comment by pvdlg** [comment]
Closing as we won't make this change for the reasons explained above.
The workflow discussed here will be supported with version 16.
