### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by forforeach** [semantic-release/semantic-release#1134]
Hello, 

it isn't exactly an issue, but I think there is a lack of a roadmap in the repo. Specifically, I'd like to understand, when version 16 is planned to be released? 

Thanks for the great work!

**Comment by alexan** [comment]
do you need help on any issues regarding the 16 release? I am waiting for this changes desperately

**Comment by travi** [comment]
the v16 beta is pretty stable and i can say from personal experience that it is working very well. if you need the features desperately, i would just recommend using the beta

**Comment by forforeach** [comment]
Thanks for your response. I already use the v16 beta. Just wanted to know, when it will be released and what else is planned for this great library

**Comment by markov00** [comment]
Any update on a possible ETA for the 16 release?

**Comment by leethree** [comment]
the new maintenance release feature of v16 beta is not working at all (#1131) and it seems no one has worked on the `beta` branch [since one year ago (Nov 2018)](https://github.com/semantic-release/semantic-release/compare/beta)

it's frustrating because we already waited for a year to use the maintenance release feature, and there's still no plan for actually releasing it.

**Comment by gr2m** [comment]
> v16 beta is not working at all (#1131)

Can you setup a fresh repository to reproduce the problem? Because we cannot.

> it seems no one has worked on the beta branch since one year ago (Nov 2018)

Last commit is 12h ago: https://github.com/semantic-release/semantic-release/commits/beta

> it's frustrating because we already waited for a year

I understand your frustration, but this is very complex work, and it's all run by volunteers. I do not appreciate your attempt of shaming Open Source maintainers into doing more free work for you. Please stop doing that

**Comment by leethree** [comment]
@gr2m Apologies for saying that the `beta` branch is not updated. I was looking at a wrong branch. 

We do appreciate your work. However our team needs to make a decision on whether to wait for stable release of v16 or switch to another library. It would be very helpful to have more communication from the maintainers on the `beta` issues, and more visibility into the plan for the next release, which is exactly the main point of this thread.

**Comment by travi** [comment]
as i mentioned above, the beta is very useful currently, even though it has yet to be promoted to stable. i use it in many of my projects and would recommend simply using the beta.

**Comment by dominykas** [comment]
@leethree why not just use the beta?

@gr2m I'll admit that I haven't really looked hard, so it may already be answered, but nevertheless - the question of roadmap is a nice thing to be aware of. It's very hard to participate in other discussions without being aware of the direction - which may just be what you want as a maintainer. There's also the case of not being able to help (or ar least consider helping, then forgetting to do it, and feeling guilty about that). Which is also something you might want as a maintainer. But even then - I would definitely not be offended if you told me that.

And while it's absolutely maintainer's right to run their project as they see fit, it's nice, as a user, to know what's going on.

**Comment by gr2m** [comment]
We agree with your points 👍 Pierre already said he will comment here with what's left to do for the v16 release, he is just very busy right now.

**Comment by dominykas** [comment]
Thanks!

**Comment by pvdlg** [comment]
This issues I want to address before releasing v16:
- #1191 and #1101 => Will use `git notes` to store the sate
- #1131
- Maybe #1260
