### ISSUE TITLE
Fix resolved multiple times

### ISSUE THREAD

**Issue by cclauss** [semantic-release/semantic-release#1157]
## Current behavior

https://github.com/IBM/python-sdk-core/issues/8

## Expected behavior

Fix should happen in one release, no multiple.

## Environment

- **semantic-release** version: 
- CI environment: 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs:

**Comment by pvdlg** [comment]
Can you provide a link to the logs of the Travis job where the problem happened?

Looking at your config it seems likely the problem happens because [you use `bumpversion`](https://github.com/IBM/python-sdk-core/blob/4430ed1c4a4b0693ca846d1d8ca2cc18e52838d4/.releaserc#L7). It seems this tool determine the next version and create a tag. That will conflict with what semantic-release and will mess up the detection of what is included the last release.
Also your `bumpversion` probably create wrong tags as you pass `minor` to the command line and not all release are `minor`.

If you want to make a commit on each release with updated files you should use:
- `@semantic-release/exec` to update the files (and make sure to **not** create a tag here)
- `@semantic-release/git` to push a commit with the updated files
