### ISSUE TITLE
allow plugin to overwrite what env-ci does

### ISSUE THREAD

**Issue by cyberhck** [semantic-release/semantic-release#1171]
## New feature motivation
I'm configuring teamcity and it's very stubborn, versions are different, I can set branch name on environment variable, but env-ci won't let us do anything.

## New feature description

It'd be awesome, if we could do either of two things,
- totally allow plugin to replace envCi (not awesome)
- allow user replace envCi with their function, but pass in envCi as parameter (they could simply install themselves, but semantic-release could give them env and cwd, so it's easy)
- allow user to overwrite values passed, kind of like afterCi method which receives whatever envCi returns, then plugin can update values and return.

## New feature implementation
well, this should be non breaking change, as far as I see, it should be fairly simple as well.

Plugins will have a one more place where we could do this, maybe a new step, for example (of course better naming later), envCi, then on run function, after envCi is done, (or instead of), depending on what we decide, we can simply check if the plugin is there, and that could overwrite any info from envCi.

If you come up with what path to choose, I can send a PR :)

**Comment by cyberhck** [comment]
I've tried to come up with #1172 can someone see if that's something we'd go with?

**Comment by cyberhck** [comment]
for now I've changed it to overwrite branch name

**Comment by gr2m** [comment]
Is this a problem that could be fixed in https://github.com/pvdlg/env-ci instead? [The support matrix](https://github.com/pvdlg/env-ci#supported-ci) lists teamcity and claims it reads out the `branch` configuration. What exactly is not working? Maybe open an issue there instead if you don’t get the branch configuration you would expect?

**Comment by cyberhck** [comment]
thing is, I'm running my tests and semantic-release on a docker container, by mounting volume, so there's no other way of getting branch name because git branch doesn't give anything, and env-ci looks at some file which isn't present in my case.

It'd be awesome if we could convert env-ci usage into a plugin instead, by default we can use env-ci, but if someone wants to overwrite, they should be able to.

**Comment by gr2m** [comment]
@pvdlg put the most thought into this, let’s wait to see what he thinks.

Maybe `env-ci` could allow to override the properties with special `ENV_CI_*` environment variables?

**Comment by cyberhck** [comment]
I don't think they will https://github.com/pvdlg/env-ci/pull/83 I tried to give a PR, but it seems like they might not be aon board.

**Comment by gr2m** [comment]
The `TEAMCITY_BUILD_BRANCH` is a custom environment variable that you set yourself? Or is it provided by the teamcity. I both Pierre and I, we don’t fully understand the problem and don’t want to put in workarounds for a single person running into it, it feels like there should be a better way, such as a change in your setup

**Comment by cyberhck** [comment]
teamcity build branch can be changed to `ENV_CI_BRANCH`, the point is to be able to run these things inside a docker container.

**Comment by pvdlg** [comment]
As I explain over in pvdlg/env-ci#83 I would rather have env-ci to be improved to determine the branch itself.
If you have a way to determine the branch yourself and set it in `TEAMCITY_BUILD_BRANCH` or `ENV_CI_BRANCH` then instead env-ci could do whatever you do to figure out the branch on which the build was triggered.

Also there is a fallback mechanism in `env-ci` to determine the current local branch in case the environment variable and config file fails.
We run `git rev-parse --abbrev-ref HEAD` to figure out he local branch name. If the repo was cloned with a detached then this command returns `HEAD` instead of the branch name and in that case we run `git show -s --pretty=%d HEAD` to try to get the name of the remote branch that has the same head commit as the local one.

We have several other users on TeamCity (the `env-ci` code for TeamCity was written by a user) and it works fine for them. It seems your case is very specific as the environment/config file method fails while it works for other and the `git` CLI method fails while it should work on any cloned git repo.\
This is why I asked for more informations. We won't make a change until we fully understand the problem.

So please provide the following:
- Describe your environment and what trigger the builds.
- If you are in particular TeamCity configuration (involving Docker apparently) please provide some doc that would help us to understand your environment.
- Run `git rev-parse --abbrev-ref HEAD` on your CI and provide us the output
- Please provide the value of `TEAMCITY_BUILD_PROPERTIES_FILE` (with `echo $TEAMCITY_BUILD_PROPERTIES_FILE`)
- If `TEAMCITY_BUILD_PROPERTIES_FILE` contains a file path, please provide the content of this file (with `cat <path_to_the_file>`)

**Comment by cyberhck** [comment]
again, I think I'm not being clear, I'm using this on teamcity, but inside a docker container, but teamcity reads a config file which isn't available inside docker container, I simply do a `docker run ... ` which triggers semantic-release, now I am able to set the env vars, but I'm not able to mount a random file inside a docker container.

**Comment by pvdlg** [comment]
What's the point of running semantic-release inside docker? Why not running directly on the CI after you do whatever you have to do in Docker?

Currently, how do you clone the repo in Docker? What's the result of the command `git rev-parse --abbrev-ref HEAD` inside Docker?

**Comment by cyberhck** [comment]
because the things on CI aren't reliable, sometimes git version is less than 2, sometimes there's no approporiate nodejs not installed, filtering those out, I get only 1% of our agents, while there are almost 40% of agents staying idle, using docker just lets me run these anywhere.

Thing I like about semantic-release is it's plugin system, why can't we determine branch via plugin (default to your env-ci), and let users overwrite it? Doing everything via plugin will ensure we can swap any technology out, say someone don't want git, they can change and use anything else they want, if they don't want to rely on env variables, they can.

I'm not saying the current PR sent to this repo is good, because honestly it's not, it's not even a plugin, it just comes on context, I couldn't figure out how to add a plugin to the pipeline. But I do believe we should update a bit and let people a bit more customization.

**Comment by pvdlg** [comment]
> because the things on CI aren't reliable, sometimes git version is less than 2, sometimes there's no approporiate nodejs not installed, filtering those out, I get only 1% of our agents, while there are almost 40% of agents staying idle, using docker just lets me run these anywhere.

Maybe you might want consider using another CI?

> Thing I like about semantic-release is it's plugin system, why can't we determine branch via plugin (default to your env-ci), and let users overwrite it? Doing everything via plugin will ensure we can swap any technology out, say someone don't want git, they can change and use anything else they want, if they don't want to rely on env variables, they can.

Extracting a functionality as a plugin represent some development and documentation work. Moreover it add to the overall complexity of the project and generate a lot of support tickets, bug reports, unexpected issue and maintenance work.
As an open-source project, our time is limited, and we have to consider the long term impact of changes. Our experience so far is that adding some customization that might seems minor at first, end up generating a huge amount of work on the long run.
In short, it might seems a few line of code to change from your perspective but from mine that means a constant flow of tickets and support questions for the years to come regarding the configuration, the creation of plugins, the conflict with other plugins, bugs in third-party plugins, issues specific to a CI, the wording of the documentation, opinions about such and such "best practice", etc...

> Because if semantic-release can't run on docker, it's a bad thing?

It doesn't run on Docker **in your specific case**, that's quite a big difference.
I've been trying to see if there is a possible workaround by asking you questions [here](https://github.com/semantic-release/semantic-release/issues/1171#issuecomment-500904842) and [there](https://github.com/semantic-release/semantic-release/issues/1171#issuecomment-501321339)but it seems you are not interested in helping me to help you.
If the only thing you do is to ask over and over again for things to work on a certain way, refuse to consider that there is other things at stake than your use case and refuse to help us finding solutions, unfortunately, there is nothing we can do for you.

**Comment by cyberhck** [comment]
Well, I have replied to your questions where I could have, thing is that this is a company setup teamcity and I can't give too much information without consulting first.

Because teamcity checks out detached head, I already tried doing those rev parse stuff, doesn't work, using git to determine branch under teamcity doesn't work at all.

`TEAMCITY_BUILD_PROPERTIES_FILE` doesn't exist as I mentioned already that I'm on docker and I only mount my project directory.

**Comment by gr2m** [comment]
I fear it’s too much of a special case Nishchal, the solution would be to adapt your setup to set the same environment variables in the docker that teamcity does by default.

I’m going to close the issue, sorry that we can’t be of better help

**Comment by cyberhck** [comment]
I was using my fork for a while now, we're waiting for github actions in our enterprise and will officially remove the semantic-release fork on my branch :)
