### ISSUE TITLE
svn integration

### ISSUE THREAD

**Issue by spmeesseman** [semantic-release/semantic-release#1173]
Hello :)

Love your shared work, thank you!!

on the subject of a semantic-release with subversion support...

I'll be taking this on soon, is there any interest of having this functionality pulled into this project?  Or would you prefer I just keep a separate project?  Do you have any suggestions on best approach to this before I start digging in?

**Comment by cyberhck** [comment]
@spmeesseman Actually I'd suggest you if we could simply make everything working as plugin, then that'd be great.

Like determine branch can be a separate plugin, verify condition can check for git version if it's required, generate tags etc.

If everything is done via plugins, all you need to do is overwrite some of the plugins :) You just gave me an idea on what naming should I be using, thanks.

**Comment by spmeesseman** [comment]
Looking at the code, it does not appear this is possible to do with using just plugins?  For example, commit-analyzer plugin would be replaced with a commit-analyzer-svn plugin, but, where do the commits come from that get analyzed?  Isn't this in base semantic-release, retrieving the actual repository/url and commits?  Base semantic-release would need to branch on git vs. svn in its code for a bunch of things from what I see.  But I've only looked at it for an hour, so I could be wrong.  Am I?  Thoughts?

**Comment by cyberhck** [comment]
unfortunately you're not wrong, the initial step isn't done by plugins, they have requirements of git > 2.0.0, directly on the code, I also wanted a feature where I could add my own function for determining branch, tried a lot, but at last I ended up using context instead of plugins which also comes from release.config.js

that's why I was suggesting you to refactor semantic-release in a way that it's a simple plugin for every single thing except for initializing part.

If they want to check for git version, do it in verifyConditions cycle, so you could replace everything with svn related plugins, unfortunately that's not the case.

Actually if it were me, I'd have made a simple middleware pipeline, one calls the next and that calls next and so on, each es6 class could add middleware for any stage.

**Comment by spmeesseman** [comment]
so i was able to get things to start working in my own project with svn using a clone of semantic-release.  It turns out only a handful of files needed to be modified, maybe 5 or 6, and a additional dependency of node-svn-ultimate.  Do you have any interest in me contributing to this project and have that added to your base functionality?  Or would you rather stay away from svn support and ill just continue to work my own project?  In any case, its all inspired by your fantastic work, thank you again

**Comment by pvdlg** [comment]
semantic-release uses a lot of Git specific feature and it won't possible to migrate those to another version control system.
Also SVN is not really on the rise, so there is no much reason for us to invest time on that.
 
If you would like to find a way to make it work with SVN I would recommend to for the project.
