### ISSUE TITLE
Support manually triggering next release type

### ISSUE THREAD

**Issue by mkay581** [semantic-release/semantic-release#1225]
This is a great package! Thanks for creating it 🤗 

The documentation states that it analyzes Angular Commit Message Conventions to determine which type of release to create. But my team has a use case where we'd prefer not to use the Angular Commit Messages and just manually trigger the next release type instead (i.e. `major`, `minor`, `patch` etc). We would rather use our own experience and judgment to adhere to semver rules.

I'm aware of this sentence in your FAQs:

> You deliberately cannot trigger a specific version release, because this is the whole point of semantic-release.

I agree that triggering specific versions is undesirable, but we would like to pass `patch`, `minor`, `major` etc? since we do not want to adopt the Angular Commit Conventions. 

Is this possible? And if not, would you consider adding this ability?

**Comment by pvdlg** [comment]
It's not possible and goes against the semantic-release philosophie. The goal of semantic-release is to remove human decision in the process of choosing version number. We won't implement such features.

There is other packages out there that should do what you are looking for.

**Comment by mkay581** [comment]
wow, okay. No problem. Guess we won't use the package then and will seek alternatives. Thanks!

**Comment by NitroBAY** [comment]
It's annoying because I've created my whole app using sementic-release and our application does show the version to the users and we definitely DO need to show the users the this version is 2.0.0 and another application with different codebase will show to the users "VERSION 1.0.0"  and we started with 0.X version so for my understanding it won't bump UP the version number to write BREAKING CHANGE.
It's so unfortunate to force us developers to waste so many hours around your hard limitation. It will probably take a long time to replace your solution by another we yet have to find or to find how to hack around (we already spent hours on this). We have to release the BETA version to our user this morning with V2 tag (requirment) and we are absolutely stuck. 
@mkay581
