### ISSUE TITLE
Detect orphan commits & tags.

### ISSUE THREAD

**Issue by alvaropinot** [semantic-release/semantic-release#1257]
## New feature motivation

Some background from #1121 👇 

In case it helps @charliebravodev, I had a similar issue and I discovered that the released git tag was pointing at an orphan commit, probably due to a rebase. 

### My solution

Find the git commit that should be the one that the tag `vX.X.X` is pointing at and force update the tag with (`-f` stands for force, as the tag already exists)👇

`git tag -f <vX.X.X> <SHA_of_the_actual_comit>` 

In my scenario was `v1.2.3` pointing to `b843f6` when it should point to `356a7b4` so 👇 did the trick

`git tag -f v1.2.3 356a7b4`

then **force push** the tags to the remote repo too running 👇 

`git push -f --tags` . ⚠️ **This is risky business** 😛 

## New feature description

Check for orphan commits as ie: a precondition and either exit not 0 or warn the user that the tags are not present in the current release branch (default: master)

### Proposal
Include a precondition check in semantic-release or the check plugin like `git branch --contains $COMMIT_ID` to check if every tag is still in the `release.config` branch normally *master*. Warn the user if its not.

#### Not that pseudo code 😅 

```js
const tags = getTagsCommitIDs()
const DEFAULT_RELEASE_BRANCH = 'master'
const checkContains = (commitId, branch = DEFAULT_RELEASE_BRANCH) => 
   exec(`git branch --contains ${commitId}`)
const isEveryTagContainedInBranch = tags.every(checkContains)
```

Will this make sense @pvdlg? If so how will you approach it?

**Comment by alvaropinot** [comment]
Looks like there were some thoughts put against this at `isRefInHistory` https://github.com/semantic-release/semantic-release/blob/6a8eede96f9e61f22ddbf885db7947798b1bf55c/lib/git.js#L43 but it might not be working as intended.

Was https://github.com/semantic-release/last-release-git-tag/blob/master/lib/git.js just moved inside semantic-release/lib? It's archived but I don't know if it's actually in use by some plugins or so 😅

**Comment by PeterMerkert** [comment]
We were just running into the same problem and we have a reasonable scenario to support including the cross check you talk about here:
1. Merged new features in one merge commit (C#123) into master, resulting in tag `v2.3.3`
1. Now, we saw our code actually failing to be deployed on Google Play, because the build failed. However, this build can only occur __after__ a tag has been created.
1. Revert the merge with a rebase on master just one commit before C#123.
1. The next semantic release failed stating the tag `v2.3.3` is already existing

The first idea for a workaround for us is to actually remove the tag from git manually now. But that will result in our case in problems further down the build pipeline, because an iOS build wth `v2.3.3` succeeded, putting already a build out there into the market.

Since the double deploy does not work, we had also to change the tag `v2.3.3` to target the same commit as `v2.3.2`. This worked. So `git push -f --tags` 😅

**Comment by pvdlg** [comment]
What you describe is a fairly edge case that indicate a bigger problem on your repo, most likely that `master` history was rewritten.

There is no accurate way for semantic-release to identify what you describe accurately. A tag not being in the history of `master` doesn't necessarily means there is a problem. You might have other branches were you make releases, or where you create tags for any reason other than release. You mention a very narrow case that affect you, but it's not possible to identify it accurately, as there might be many similar cases that are not an issue for many other users.

We ignore tags that are not in the history of the branch for that exact reason. They are not relevant to semantic-release but they are not necessarily wrong and we don't want to prevent users to use tags on other branches or for other purpose.

Problems happens when semantic-release create a tag and you rewrite the associated commit. As a general rule you shouldn't rewrite `master` history and if you do it's your responsibility to fix the tags you have broke.

**Comment by oustn** [comment]
I had a similar issue and cause by deleted and recreated the release branch. The `dev` branch will release to the alpha channel. So I decide to create a "mock" release info.

1. Pick one commit id like `acb6cf2c`
2. Create a tag with the next version: just like current version is `v1.0.0-alpha.20`, the next version tag will be `v1.0.0-alpha.21`
```
git tag v1.0.0-alpha.21 acb6cf2c
```
3. Add notes to the commit Id use for identify the channel
```
git notes --ref semantic-release add -f -m {\"channels\":[\"alpha\"]} acb6cf2c
```
4. Pust tag and notes
```
git push origin v1.0.0-alpha.21
git push origin refs/notes/semantic-release 
```
5. release it.

> 2022-08-23 16:26:32.606  [8:26:32 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2022-08-23 16:26:32.606  [8:26:32 AM] [semantic-release] › ℹ  The next release version is 1.0.0-alpha.22
