### ISSUE TITLE
[Question] Possible to add release notes when branch is merged?

### ISSUE THREAD

**Issue by Marfru** [semantic-release/semantic-release#1281]
Hello,

We do not make builds in my team.

We were wondering if it's possible to add release notes when:

Branch is on PR > Snapshot Testing > If Test is successful, Merge. > When Merged, add release notes from commits.

Jenkins integration would be nice too. -> **[UPDATE: it supports Jenkins, nice]**

We are still digging into this.

Regards and thanks!

**Comment by gr2m** [comment]
When you merge, you can edit the commit message when using the `squash & merge` feature, that's what I usually do

**Comment by pvdlg** [comment]
semantic-release runs only on the brach you specify in the `branch` option (by default `master`).
How the commits got there doesn't matter to semantic-release, they can be pushed directly (not recommended) or merged from another branch (via PR or not).

When semantic-release runs it will look at all the commits on `master` since the last release tag and make a new release if necessary.
