### ISSUE TITLE
@semantic-release/npm fails with valid token, despite previous success

### ISSUE THREAD

**Issue by dannyrb** [semantic-release/semantic-release#1289]
## Current behavior

1. Previous `semantic-release` publish worked as expected
2. Recent `semantic-release` publish fails w/ same config and ENV variables

## Expected behavior

That `semantic-release` will continue to work if CI/env config has not changed

## Environment

- **semantic-release** version: `15.13.24`
- CI environment: `CircleCI`
- Plugins used: Default
- **semantic-release** configuration:  `{ "branch": "master" }`
- CI logs:
    - Failing: https://circleci.com/gh/OHIF/react-vtkjs-viewport/64
    - Most Recent Pass: https://circleci.com/gh/OHIF/react-vtkjs-viewport/16

I noticed that this is the relevant code throwing the error:

https://github.com/semantic-release/npm/blob/master/lib/verify-auth.js#L19-L21

When I create a local `.npmrc` with the default registry and my `NPM_TOKEN`, calling `npm whoami` returns `ohif-bot` (as expected)

**Comment by fulls1z3** [comment]
i had the same, just add `"@semantic-release/npm": "5.1.13"` to your devDependencies. the problem seems to happen because of `execa`.

**Comment by dannyrb** [comment]
@fulls1z3, that did the trick for us as well: https://github.com/OHIF/react-vtkjs-viewport/pull/37/files

I'll keep this open for now. While the workaround resolves our issue, it's still a workaround.

**Comment by pvdlg** [comment]
That's likely an issue with execa indeed. It was fixed in 5.1.13. Please use the latest version.
Using `5.1.13` is not a workaround as mentioned by @dannyrb. There was a bug it was fixed in a new version, if you that version or a newer one you won't have the bug.

Please note that `semantic-release` use a version range to define the `@semantic-release/npm` dependency so you will always get the latest version. Unless you use a lockfile that forces an outdated version.
