### ISSUE TITLE
Avoiding the need for git write access

### ISSUE THREAD

**Issue by rarkins** [semantic-release/semantic-release#1324]
## New feature motivation

I'm trying to write a filtering API proxy so that I don't need to give semantic-release a full read/write token. i.e. principles of least privilege.

## New feature description

It would be nice if semantic-release didn't require `git` access and instead could entirely use the API (e.g. GitHub). I just want semantic-release to be able to use use the Releases API and not a dry-run git push to verify write access.

## New feature implementation

Is it possible to do read-only `git` operations and then rely on write permissions for just the Releases API?

Right now I get this failure:

```
SemanticReleaseError: The push permission to the Git repository is required.
```

**Comment by gr2m** [comment]
semantic-release is not GitHub-centric. `git` is the only common denominator across all the targets we support. I think you'd need to build a whole new library as a replacement.

I'd say it's out of scope for the project, I'm sorry

**Comment by rarkins** [comment]
Does semantic release actually need git push for GitHub though? I presume it’s for tagging but doesn’t the Release API already handle tagging when you create a release? I can’t think why I’d need/want semantic release to “git push” anything.

**Comment by gr2m** [comment]
@pvdlg will no better about the latest implementation, but I think it wouldn't be trivial to remove the `git push` as the plugin architecture depends on it. I'm not sure the added complexity would outweigh the benefit

**Comment by pvdlg** [comment]
We need push access in order to push tags which is done in the core. It is a mandatory task as we rely on tags to figure out which commits were added since the last release.

Currently the core is agonistic to where the remote repo is hosted. It will work with GitHub, GitLab, BitBucket, a self hosted Git repo or anything that speaks the git protocol. Everything related to a specific Git host lives in plugins (`@semantic-release/github`, `@semantic-release/gitlab`).

I would prefer to not add any specific API dependency to the core and keep those in the plugins.
Adding the tag creation and push responsibility to plugins seems risky as it's a critical and mandatory task. If the tag doesn't get created and pushed to the remote repo, semantic-release simply won't work.

So there is serious drawbacks with either solution and I'm not sure what benefits it would provide.
Can you explain what would be the benefits of creating and pushing the tags via API rather than via `git` CLI?

**Comment by rarkins** [comment]
I was hoping to add an API filtering proxy for more security. Don’t like having a full read-wrote token lying around on CI systems. Maybe GitHub Actions kind of alleviates that concern though.

In theory, could one day we support simply *not* pushing the tag if the User is using GitHub and we know creating a release will tag anyway? I mean something like a Boolean option that does no more than skip an existing section of code.

**Comment by pvdlg** [comment]
Theoretically it's possible but as explained above, because creating tags is vital for semantic-release to function, we don't want to delegate that to plugins. Doing so would just give users the opportunity to create a misconfiguration that would result in semantic-release attempting to release always the same version.

I don't really understand the argument about a read-write token on a CI. You still need a read-write access somewhere, whether it is used with the `git` CLI of the Github API, you still need the same token with the same permissions.

**Comment by rarkins** [comment]
@pvdlg @gr2m thanks very much for the discussion and explanation. I understand your position re: keeping the core code as generic as possible across platforms, so think we can close this.

FYI I had nearly built a kind of "filtering proxy" for semantic release with the idea being that instead of exposing a full read/write token onto CI systems you can instead (a) use a proxy token in semantic-release, and (b) point it to my proxy, and the proxy would make sure you were only doing releasing and nothing else nefarious. It failed to work though because of this git read/write check because I wasn't proxying *that*, hence why I asked. I had mistakenly assumed that the tags were created as part of GitHub's "create a release" API call.

With GitHub Actions being available now, I think the need for a filtering proxy to sit between GitHub Actions and GitHub API would be overkill, so I'll probably pass on my idea.
