### ISSUE TITLE
Wrong SHA in published packages

### ISSUE THREAD

**Issue by bahmutov** [semantic-release/semantic-release#135]
Hi,

I have noticed and my users have reported problem installing packages that were published using NPM. For example trying to install `npm i manpm` and getting the SHA error https://github.com/bahmutov/manpm/issues/8

```
$ npm i manpm
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/kensho/.nvm/versions/node/v0.12.7/bin/npm" "i" "manpm"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.11

npm ERR! shasum check failed for /var/folders/hq/kswp5gxj5nz123d4jyx5b3yh0000gn/T/npm-68944-f2d2fadb/npm.kensho.com/manpm/-/manpm-1.3.0.tgz
npm ERR! Expected: 3f055d6e700df08338d821b9793d527b3f0641c7
npm ERR! Actual:   afc36a15f9ffd57ef168823207494e4574ff4326
npm ERR! From:     http://npm.kensho.com/manpm/-/manpm-1.3.0.tgz
```
The travis build that triggered the publication is https://travis-ci.org/bahmutov/manpm/jobs/93093109 
There is a second build of the same commit (2 node versions) which failed to publish here https://travis-ci.org/bahmutov/manpm/jobs/93093108

Will try removing one Node js from the travis and build again

**Comment by bahmutov** [comment]
Ok, seems single tested Node version on Travis fixed the problem. Is there something about multiple Node versions I can fix? Is there a way to only publish for a specific node version?

**Comment by boennemann** [comment]
Hey @bahmutov,

exactly, this caused by multiple Travis jobs running and publishing at the same time. You can prevent this from happening by using travis_after_all like so: https://github.com/semantic-release/cli/blob/master/.travis.yml#L31-L33

If you chose multiple node versions with the cli it sets it up for you and with future versions of semantic-release this going to be implemented in JS and bundled with semantic-release.

Best,
Stephan

**Comment by trodrigues** [comment]
Ah damn, I also got caught by this. Wondering if it would be a good idea to also add a note on the readme, as people integrating it with existing projects probably won't let semantic-release generate a travis file for them.
