### ISSUE TITLE
get-last-release gets incorrect version.

### ISSUE THREAD

**Issue by SongGithub** [semantic-release/semantic-release#1351]
## Current behavior
- fact: my latest github release version is v1.0.2, produced by the sem-release automatically
- fact: I did some Git rebase operations to clean up my commit history, then ran `git push --force-with-lease` which might contribute to the problem as it altered the git ref
- problem: when running the sem-release again, it could *not* acquire the latest tag which is v1.0.2, instead it thought it is v1.0.1. 

### The events leading to the error
```
semantic-release:get-last-release found tags: [ { gitTag: 'v1.0.2', version: '1.0.2' }, { gitTag: 'v1.0.1', version: '1.0.1' },
```

```
[semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1
```

### The error:
```
An error occurred while running semantic-release: { Error: Command failed with exit code 128: git tag v1.0.2
    at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command: 'git tag v1.0.2',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: tag \'v1.0.2\' already exists',
```

## Expected behavior
I expected it not to release at all. As the git commit `fix: foo-bar` has already triggered a patch version bump from v1.0.1 to v1.0.2. 

## my speculation

in [this line](https://github.com/semantic-release/semantic-release/blob/ffff100f472c3427ae157fe2edc8c6871bf542e2/lib/get-last-release.js#L42), it tries to check my local git ref log which may subject to chaos caused by my `git push --force-with-lease` command to Git history. If this was the case, I would hope it could be more robust against frequent Git history re-write.

**Comment by pvdlg** [comment]
As mentioned before, the Issue tracker is for bug reports not for support requests. The proper channels are indicated here: [Get Help](https://github.com/semantic-release/semantic-release#get-help).

I see that you posted on Spectrum as well (https://spectrum.chat/semantic-release/plugins/commit-analyser-module-failed-to-detect-the-latest-git-version-tag-causing-err~ba4b71d4-39a5-46b7-baf6-093fc478a22d) which is the correct place to ask support.

Please do not double post. That just creates an unnecessary burden on maintainers and make it less likely for you to get an answer.

**Comment by SongGithub** [comment]
hi @pvdlg , I think this is a bug, then it is better to raise it here. The semantic-release module determining new version is v1.0.2 when it has been already released is unexpected behaviour. I think it is due to function `isRefInHistory` not returning correct result when Git history has been modified.

**Comment by pvdlg** [comment]
It's not a bug, it's the intended behavior, we ignore tags that are not in the branch history.
semantic-release uses tags to maintain a state in between releases in order to figure out what changed since the last release. If you rewrite your commit history then semantic-release cannot work properly.

It seems you are in a situation were you removed the commit that was referenced by `v1.0.2` which create a major inconsistency in your repo as the code that was released in `v1.0.2` doesn't exist anymore or at least its history of changes as been altered.

You have to recreate the `v1.0.2` pointing to the commit that correspond to the code released in that version.

See #1229 and https://github.com/semantic-release/semantic-release/blob/master/docs/support/troubleshooting.md#reference-already-exists-error-when-pushing-tag

**Comment by SongGithub** [comment]
thanks a lot for your explanation!

**Comment by SongGithub** [comment]
hi @pvdlg 
> we ignore tags that are not in the branch history

Could you suggest how to use *semantic-release* properly when *Git-flow* is used? In the Git-flow, releases are produced in temporary *release* branches, then the branch will be deleted. The situation is similar to [this issue](https://github.com/semantic-release/semantic-release/issues/1229#issuecomment-507491422)

My question is, if the tags are created in release branch. Then once the branch squash-merged & got removed, *semantic-release* will not be able to properly determine the latest version/release, as the Git commit reference to the tag does **not** exist in future release branches. 

In my current project, Github Pull Requests' default "create a merge commit" which adds all commits into primary branch, has been disabled in order to redirect Devs to use the secondary option in Github Pull Request "Squash & Merge". I suspect current "Squash & Merge" pull request merge strategy won't be compatible with the *Semantic-release* ?

**Comment by pvdlg** [comment]
> Could you suggest how to use semantic-release properly when Git-flow is used? In the Git-flow, releases are produced in temporary release branches that are branched out from the Develop branch, then the branch will be merged & deleted. The situation is similar to this issue

semantic-release doesn't support Gitflow by design. See https://github.com/semantic-release/semantic-release/issues/1231#issuecomment-534773456
The goal of semantic-release assume is to continuously deliver. As such any commit that end up on the release branch (`master` by default) is considered releasable and is released. Gitflow does the exact opposite and "store" commits on a release branch before actually releasing.
If you want to use git flow you should look for another tool.

> In my current project, Github Pull Requests' default "create a merge commit" which adds all commits into primary branch, has been disabled in order to redirect Devs to use the secondary option in Github Pull Request "Squash & Merge". Otherwise, the primary branch will be flooded with trivial commit messages from Pull Requests. i.e. "fix a syntax error".
> I suspect current "Squash & Merge" pull request merge strategy won't be compatible with the Semantic-release, unless committing all commits from a Pull Request is enabled in Github repository ?

Yes it is supported with the [GitHub flow](https://guides.github.com/introduction/flow/). All that matter to semantic-release is the commit that end up on the release branch (`master`). Whether they were merged or squash and merged doesn't matter as long as the resulting commits follow the convention.

**Comment by SongGithub** [comment]
hi @pvdlg , just let to share with you & community that I found a work-around which enable us to use *Semantic-release* with the Git-flow.

As long as tagged Git commits that triggered the release from `release/*` branches, are **preserved**, Git-flow and semantic-release are compatible. Just don't use squash-merge nor rebase-merge when close a Pull-Request from release/* branches. 

My lesson was that I squash-merged release-branches containing commits that triggered releases with the *semantic-release* by mistake. (due to lack of understanding how the semantic-release works). As a result, subsequent releases by the semantic-release couldn't determine the latest version correctly, and trying to over-write some of existing version/tag. 

Thank you for insights & links along the way!
