### ISSUE TITLE
how to set the version step ？

### ISSUE THREAD

**Issue by ron0115** [semantic-release/semantic-release#1366]
## New feature motivation

I want to get the version auto bump from 1.0.9 to 1.0.10 but it turn to 1.1.0, how can I set the config to achieve this goal？

## New feature description

the same above

**Comment by pvdlg** [comment]
As indicated in the [first chapter of the README](https://github.com/semantic-release/semantic-release#how-does-it-work) the goal of semantic-release is to determine the next version based on the commits since the last release.

Without any context about your configuration, your commit history, I can't help you.

I would recommend to post here with additional details:  https://spectrum.chat/semantic-release

**Comment by ron0115** [comment]
@pvdlg  I just use the default config，the default behavour would bump version from 1.0.9 to  1.1.0 if I commit a "fix", but I want to get 1.0.10   =>   1.0.11    =>     1.0.99

**Comment by pvdlg** [comment]
Please provide the semantic-release and if possible a link to your repo.

**Comment by ron0115** [comment]
@pvdlg  I thougt I fixed it  thanks for your warm heart~

**Comment by pvdlg** [comment]
With that config all commits (even the one that are not following the convention) will trigger a patch release. And you won't be able to make a minor nor a major release. So that's probably not what you want...

With the default config a `fix` commit should trigger a patch (`1.0.9` => `1.0.10`).
If you went from `1.0.9` to `1.1.0` that meant you had a `feat` commit since the last release.

I have trouble to figure out what you are trying to achieve... You said you want `1.0.10 => 1.0.11 => 1.0.99` but that doesn't seems to make any sense...If you have a `1.0.10` a patch release would increase it `1.0.11`, and a minor release to `1.1.0`. In not case you would go from `1.0.11` to `1.0.99`. That's just how semantic versioning works...
