### ISSUE TITLE
dry run tries to push tags

### ISSUE THREAD

**Issue by oupala** [semantic-release/semantic-release#1396]
## Current behavior

I added some flags to prevent semantic-release from interacting with GitHub, and it still does.

> [23:24:42] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[23:24:46] [semantic-release] › ✖  The command "undefined" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/user/project.git/'.
[23:24:46] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://github.com/user/project.git.

## Expected behavior

I would like to see a `CHANGELOG.md` generated, the version number updated in `package.json` and that's all!

I want to commit by myself, for the moment.

## Environment

- **semantic-release** version: the one that `npx` is using ("Running semantic-release version 15.13.31"
- CI environment: none
- Plugins used:
  - @semantic-release/commit-analyzer,
  - @semantic-release/release-notes-generator,
  - @semantic-release/changelog,
  - @semantic-release/npm
- **semantic-release** configuration: nothing special
  - "private": true,
- CI logs: none

```json
  "release": {
    "ci": false,
    "dryRun": true,
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/npm"
    ]
  },
```

**Comment by pvdlg** [comment]
Creating a tag is not optional as it is required by semantic-release to determine the commits that were added since the last release. You can't create those by yourself.

The dry-run mode is intended to make sure everything is going to work fine when you make a real release. We don't modify the repository, create tags or commit or publish anything in a dry-run. However we run all the verifications to make sure everything is going to work on the real run.

The error you have is only due to semantic-release verifying if you have the permission to push tags.

**Comment by oupala** [comment]
I completely understand your point of view. The dry-run-mode is here to test that everything is gonna be alright when real-run-mode.

However, the logs are a bit confusing, telling that it tries to write tags in dry-run-mode.
 
Would it be a good idea to change the wording to tell that semantic-versionning is only checking write access to the git repository?
