### ISSUE TITLE
Can semantic release back merge to develop after release?

### ISSUE THREAD

**Issue by houlahaj** [semantic-release/semantic-release#1407]
I am working on a project which uses semantic-release to automate updating the changelog and tagging the next version whenever I merge changes from develop to master. This is done in Gitlab CI.

It works great, albeit with one caveat: develop branch doesn't get the updated changelog nor the new tag.

In the standard git flow model, you make a release branch from your develop branch, do the "release stuff", then merge this to both master and develop. This means both master and develop get the commit which updates changelog and carries the version tag. I wish semantic-release could do the same so that my develop branch reflects master after each release.

**Comment by pvdlg** [comment]
No it's not supported and I don't think it's something we would support.
The reason is that using Gitflow goes against some of the core concept of semantic-release.

semantic-release not only automate the releases (publish on npm, GitHub etc..) it also handle the decision process to make a release. In that regard semantic-release is opinionated and assumes that every merged commit is releasable and should be released right away.

On the other hand the concept of gitflow is to have a develop branch to "store" commits until you (and not semantic-release) make the decision to release. 

That's why we recommend to instead use the GitHub flow (work on feature branch, then open a PR, then merge to `master`).

**Comment by houlahaj** [comment]
Many thanks for the quick and helpful reply! That certainly made me rethink my branching model. Perhaps I'll give GitHub flow a try; I can certainly see some benefit to it (namely developing the habit of making higher quality changes, since every PR should be releasable).

**Comment by saitho** [comment]
@pvdlg 

Semantic versioning is not bound to a branching model. While semantic-release might want to enforce people to release as often as possible, there may be some cases where this is not wanted.

Let's say after two weeks of development several features have been developed. The customer decides that he wants 5 of those with the next release. Merging those into _master_ would create 5 separate releases and tags, of which only the last is only ever used.

Merging them into _develop_ first and then merging from _develop_ into _master_ would only create the one release that is really needed. It would be nice to be able to use semantic-release for that.

**Comment by travi** [comment]
> Merging them into develop first and then merging from develop into master would only create the one release that is really needed. It would be nice to be able to use semantic-release for that.

nothing about that flow is prevented by semantic-release. i would personally not call the branch `develop` because that implies a more formal flow, like gitflow. however, if wanting to group features into a single release, a temporary branch is a valid way to accomplish that with semantic-release. semantic-release doesn't really care about how the changes get to master, but will take action once the changes do make it to master.

i don't think there is anything here that you are asking for that can't be done without changes to semantic-release. am i misunderstanding? 

also, what you are asking about is significantly different from the original topic of this closed issue. i would recommend opening new issues in the future rather than tacking a different question at the end of a closed issue.

**Comment by gr2m** [comment]
> Merging those into master would create 5 separate releases and tags, of which only the last is only ever used.

I usually merge multiple branches into master locally if I want a single release. The most common use case is multiple pull requests. But with the latest semantic-release, you can even merge them on github.com one-by-one, semantic-release will not release a new version for each merge if you are quick enough :) It will realize that `master` branch is ahead of the commit it is currently running on and will cancel automagically, so only the last run of semantic-release will actually create a new release. I do that all the time now

**Comment by nolde** [comment]
Leaving this here for anyone in a similar situation

The plugin https://github.com/saitho/semantic-release-backmerge solves this issue by merging `master` back in `develop` (or rebasing develop over master, your choice). Works quite well.

**Comment by saitho** [comment]
> I usually merge multiple branches into master locally if I want a single release. The most common use case is multiple pull requests. But with the latest semantic-release, you can even merge them on github.com one-by-one, semantic-release will not release a new version for each merge if you are quick enough :)

That works when you don't have merge conflicts.  ^^

In the end this is not necessarily an issue with semantic-release. I like setting up a CI job for releasing I can start manually to trigger a release on master. This should be supported by most CI platforms, directly or indirectly (e.g. Drone does not have manual triggers, but you can use the deployments feature to achieve the same).
