### ISSUE TITLE
Automatically install plugins not built in

### ISSUE THREAD

**Issue by felipecassiors** [semantic-release/semantic-release#1445]
This is something to discuss:

Where you are in a Node JS project this doesn't matter, as you install the plugins by using `npm install --save-dev`, but when you're in non Node JS projects this might be a problem.

Let's suppose `semantic-release` is installed globally this case, and its configuration is at the `.releaserc` file.

- First approach
  - Behavior: To have a `package.json` only with the plugins dependencies we need and prior to running `semantic-release` we run `npm install`.
  - Caveats: 
    - you have to put a `package.json`, which might cause some guests to interpret your project as it is a Node JS one.
    - You have to add Node JS stuff into `.gitignore` such as `.node_modules/` and `package-lock.json`, or even worse: create a new file `.npmrc` to insert `package-lock=false`

- Second approach
  - Behavior: To install the plugins globally, running `npm install -g plugin-name` before the `semantic-release`
  - Caveats: each plugin should be installed one by one, without a helper such as `npm install`

**Suggestion:**

`semantic-release` should attempt to install the plugins defined in its configuration on-the-go.
- The plugins in `.releaserc` already has all the information needed in order to install these plugins
- Maybe only attempt to install if running globally or via temporary `npx`
- Would remove boilerplate code from the ci part, since we would only need `npx semantic-release`.

**Comment by pvdlg** [comment]
Is there a stable, well tested, not hacky way to do dynamic install in a Node app?

**Comment by felipecassiors** [comment]
Yes, there are some really good alternatives. 

Direct to the point -> ### https://www.npmjs.com/package/live-plugin-manager
Doing things manually -> https://www.npmjs.com/package/pacote
Npm programmatically -> https://www.npmjs.com/package/libnpm

There is also how to use the `npm` itself through Javascript, despite it's not a good idea to include `npm` in your package dependencies, because has a big size (~30 MB). 

I found most of these info at [here](https://stackoverflow.com/questions/15957529/can-i-install-a-npm-package-from-javascript-running-in-node-js).

**Comment by pvdlg** [comment]
https://www.npmjs.com/package/live-plugin-manager looks interesting. However they clearly mention there is risks: https://github.com/davideicardi/live-plugin-manager#security

Loading plugins dynamically would also make our life harder to re-use the semantic-release code in a GitHub app. We would have to implement different loading strategies.

On one hand that would be a nice feature, that would also solves https://github.com/semantic-release/semantic-release/issues/1260. But on the other I'm afraid we would open a can or worm for something that would just save one command line (the global install of plugins) a small subset of users (the ones installing semantic-release globally).

Worth noting that all that can be easily done with one `npx` command: `npx -p @semantic-release/gitlab @semantic-release/changelog @semantic-release/git semantic-release`

**Comment by felipecassiors** [comment]
Great to know about the `npx -p` option, that really helps!

**First**, I don't quite understand the risks here, since an automatic plugins installation would be user consensual, I mean, either the user have the plugin stated in the `package.json` for further install with `npm i` or it would have the plugin stated in the `.releaserc` for further automatic install by the `semantic-release`. 

However, to minimize the security implications, I can think in two alternatives:

* To have a whitelist of trustable plugins, as suggested [here](https://github.com/davideicardi/live-plugin-manager#security) (and that sounds great, don't you think? I mean, you could for sure trust in your own plugins in a first moment).
* To use [pacote](https://www.npmjs.com/package/pacote) instead, to manually extract the plugin packages from npm registry and prevent them to run any installation script or something like that. But I'm not sure if what I said is feasible, or even useful, or not. I'm just thinking loud.

And finally, I understand when you say it's small subset of users, but `semantic-release` is completely language agnostic by definition. I see that it has a huge potential to the people which has Maven projects, Gradle, and these two have a enormous base of users. I'm an example: I use `semantic-release` to manage the release of my [Vagrant box](https://github.com/felipecassiors/ubuntu1804-4dev) to Vagrant Cloud (and creating a [plugin](https://github.com/felipecassiors/semantic-release-vagrant) for it).

**Comment by pvdlg** [comment]
I kind of agree with your points. However I still have some concerns.

semantic-release runs mostly on CIs environment and so far we've seen that each CI provider has widely different setup which cause a lot of issues with how the `git` command we run behave.
I'm concern about running `live-plugin-manager` on a CI as I have no guarantee it will work everywhere. 

Many CI runs the `npm install`, the build phase and  the `semantic-release` in a different images/stages/environment. That might create situation where installing wouldn't work when we reach the semantic-release step (because of missing registry access, missing environment variable, missing permission in `node_module` or in temp folder etc...).
We don't have any way to test that on every CI out there, and even if we did it would take a huge amount of time.

I don't think it's likely to happens but if it does it would be a huge pain as semantic-release would break for some users and it would be very difficult for us to fix/workaround as we would have to replicate what happens on the CI. It's currently a big pain point for us to deal with all the specificities of the CIs regarding how they clone the Git repo.

Overall I don't think this feature is that valuable. Running `npx -p @semantic-release/gitlab @semantic-release/changelog @semantic-release/git semantic-release` vs `npx semantic-release` is not really harder and it's something configured once in your CI config file. If the doc is not clear we can improve it to advertise `npx -p` more.

Finally, having to install plugins manually is pretty common and doesn't seems to be an issue for popular projects like ESLint or Babel.

@gr2m do you have any opinion on that?

**Comment by gr2m** [comment]
I agree with your perspective.

An "enormous base of users" is not necesserily a good thing for an independent Open Source project without any kind of funding. It will add to the maintenance work load. We have to keep that to a minimum.

**Comment by felipecassiors** [comment]
The `npx -p` is great. I guess this is enough. It can be shortened even:

```bash
$ npx -p  @semantic-release/{gitlab,changelog,git} semantic-release
```

**Comment by pvdlg** [comment]
Closing the issue then
