### ISSUE TITLE
Update version in package.json without npm

### ISSUE THREAD

**Issue by damonmiller** [semantic-release/semantic-release#1453]
## New feature motivation

If I am understanding and configuring correctly, there seems to be a requirement that if we want the version updated in package.json that we must use the npm and git plugins to do so.  In my case, and I am sure many others, we build our private apps for our employers where we do care about versioning but not npm.  We want that package.json version updated but without being required to go through npm in order to do so.  Yes, we can set our project to private and publish to npm that way, but why bother - we do not need this step.  But there does not seem to be any other way to get that version updated that I have found.  If there is, please provide the configuration to do so.

## New feature description

I would like to see the package.json version updated in the core, not in the npm plugin.  This way I can still use the git plugin to commit the version change back to my repo.

**Comment by travi** [comment]
since semantic-release supports other package managers than npm, it is unlikely that functionality that is specific to the `package.json` will ever be moved to core. however, if you are simply not wanting to _publish_ to the npm registry, you can [set `npmPublish` to `false`](https://github.com/semantic-release/npm#options). it there a reason this wouldn't satisify your need?

**Comment by damonmiller** [comment]
This would be the part where I did _not_ understand the configuration correctly... I was not aware of that config.  Let me give it a shot.

**Comment by travi** [comment]
@damonmiller did this end up working out?

**Comment by damonmiller** [comment]
I did add the config but I have not yet tested this.  I think you got me on the right path now.  Thank you!
