### ISSUE TITLE
exit code 1 on failure

### ISSUE THREAD

**Issue by MartinMuzatko** [semantic-release/semantic-release#1480]
## New plugin motivation

I want to avoid publishing any artifacts (like docker images). But they are published, because even on failure semantic-release ends with exit code 0.

A simple plugin would then exit with code 1 on failure.

**Comment by MartinMuzatko** [comment]
I discovered.. This does not work D:
`fail` is only triggered on thrown errors.

https://github.com/semantic-release/semantic-release/blob/55be0ba2b1d8a5f7d817f0d4567be04170580028/index.js#L258-L265

Whereas problems like branch is behind remote, simply returns false
https://github.com/semantic-release/semantic-release/blob/55be0ba2b1d8a5f7d817f0d4567be04170580028/index.js#L78-L84

**Comment by pvdlg** [comment]
> I want to avoid publishing any artifacts (like docker images). But they are published, because even on failure semantic-release ends with exit code 0.

How comes semantic-release publishes your artifact and also return early due to the local branch being behind the remote one? Those 2 things seems contradictory...

What's you config? Can you also provide logs?

**Comment by MartinMuzatko** [comment]
Jenkins, my continuous integration pipeline is publishing my artifacts WHEN semantic-release was successful.
However, it is meaningless to push any artifacts if semantic-release says, it cannot release a new version, because it is behind its remote. Then semantic-release should exit with code 1, which stops the execution of the pipeline and does not proceed to push to registry.

![image](https://user-images.githubusercontent.com/2950505/76068484-87b67600-5f91-11ea-82d4-87bee075ec9c.png)

So in this case I got `[1:10:25 PM] [semantic-release] › ℹ  The local branch beta is behind the remote one, therefore a new version won't be published.`
But since I don't get an exit code other than 0, the pipeline is not aborted and proceeds to publish to my registry.

Jenkinsfile (simplified, semantic-release is pre-installed)
``` gql
pipeline {
  agent {
    docker {
      image 'node:12'
      args '-u node:docker'
    }
  }
  stages {
    stage('build') {
      steps {
        sh 'docker-compose build'
      }
    }
    stage('publish') {
      steps {
        sh 'docker-compose push'
        sh 'semantic-release'
      }
    }
  }
  post {
    always {
      deleteDir()
    }
  }
}
```

**Comment by pvdlg** [comment]
semantic-release was designed to publish your artifact as part of the release, not to have something doing it later one.
You should publish your artifacts with a semantic-release plugin or https://github.com/semantic-release/exec not with Jenkins.

**Comment by MartinMuzatko** [comment]
I will see if I get the same kind of child process logging support as in usual jenkins. But yes, it makes sense to hook this into 

Wouldn't it still make sense to make the behavior of the failure consistent in semantic-release?
Why is `branch is not up to date` not triggering `fail` plugins?
I would suggest to make 
https://github.com/semantic-release/semantic-release/blob/master/index.js#L48
https://github.com/semantic-release/semantic-release/blob/master/index.js#L61
https://github.com/semantic-release/semantic-release/blob/master/index.js#L80

to `throw new Error`s

These problems seem to be as severe as other errors that are thrown. I am not sure why there is a distinction made.
e.g.:
https://github.com/semantic-release/semantic-release/blob/master/index.js#L171-L172

**Comment by pvdlg** [comment]
> Why is branch is not up to date not triggering fail plugins?

Because that's not an error case and should not break the CI build. This situation happens when you push code to your repo while the build from the previous commit is running.
That's a fairly common scenario. In such case semantic-release will skip releasing on the outdated build, and will release on the next one.

**Comment by MartinMuzatko** [comment]
This is not a proper explanation for the three other examples I have shown.
The attention paid to this irregular error handling is underwhelming.

I'd happy to do a pull request, but since the (I think well-explained and in best practices founded) idea of proper error handling has been declined so far, so I am probably better off creating my own semantic-release with blackjack and hookers 🙄 

In all seriousness, I am just pissed off _now_, but overall thankful for that this tooling exists. And you surely put a lot of effort into this project, to make sure that unsolicited feedback like mine doesn't get in without proper thought. Probably you have thought this through a lot more than I have, since I am just relatively new to SR, and you are there from the start. So please excuse my ramblings and please continue with your glorious work that is used by thousands of devs <3

**Comment by pvdlg** [comment]
> The attention paid to this irregular error handling is underwhelming.

If you search the issue tracker and take aa look at `git blame` you would see a lot of attention has been paid to error handling.
The choices made were carefully considered and discussed with several users who reported issues.
We believe the way semantic-release handled and report errors and edge case is the best compromise we can achieve that would work for the largest majority of users.

> This is not a proper explanation for the three other examples I have shown.
Those have been answered countless time through many GitHub issues. I'm sorry if I answered your issue too quickly to avoid repeating myself.
But as you insist here the detailed explanation.

Case `This run was triggered by a pull request and therefore a new version won't be published`:
We don't run semantic-release on Pull Request for several reasons, one being that secret environment variables (tokens and credential) are not available on PR opened from a fork repo.
Obviously, we are not going to fail every CI jobs triggered by a Pull Request.

Case `This test run was triggered on the branch ${ciBranch}, while semantic-release is configured to only publish from ${context.branches...`:
We run semantic-release only on branches configured by users.
We have no reason to prevent users to run CI jobs on other branches. So we are not going to fail every CI jobs that is not on a semantic-release branch.

Case `The local branch ${context.branch.name} is behind the remote one, therefore a new version won't be published.`:
This happens when 2 commit are pushed quickly to a release branch which triggers 2 concurrent jobs on the CI. Because we have to push a tag to flag releases we can't  do that on an outdated branch.
The solution is to skip the release on the outdated one and the up to date build make the release.
We don't fail the job with an exit error because:
- It's not an issue the users can act on
- It will resolve itself by publishing from the up to date build
- Users don't want to have their build randomly failing when they merge 2 PRs quickly

I explained earlier that semantic-release is designed to handle the publish of your artifacts and I provided you a solution to your problem. But you seems to ignore it or reject it without explanation.

Allowing external tools to publish based on semantic-release result would be a major change that would have a deep impact across the whole code base and the workflow used by 1000s of people.

But it seems you refuse to consider that and prefer to post aggressive messages. I would appreciate if you were to consider the larger picture and remember that semantic-release is not build around your specific use case and personal preferences but build for a large user base.
Before accusing and OSS maintainer to not care about an issue, I would also like to remind you that semantic-release is entirely built on people free time. Moreover if you had used `git blame` to see the code history and searched the issue tracker you would see that a lot of attention was paid to this problem.
