### ISSUE TITLE
publish to crates.io

### ISSUE THREAD

**Issue by GopherJ** [semantic-release/semantic-release#1544]
## New feature motivation

rust crate release

## New feature description

release to crates.io

**Comment by travi** [comment]
information about this is available [in our FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-to-publish-non-javascript-packages). i'll close this issue since you should be able to find what you need there, but feel free to re-open if you need more information

**Comment by GopherJ** [comment]
ok thanks!
