### ISSUE TITLE
Merging pull requests in quick succession causes conflated releases

### ISSUE THREAD

**Issue by tlvince** [semantic-release/semantic-release#165]
Say a project has three pull requests open with three `fix` commits. If all pull requests are merged in quick succession, each resulting release will contain the commits merged before it. For example:

`1.0.0`
* Commit A

`1.0.1`
* Commit B
* Commit A

`1.0.2`
* Commit C
* Commit B
* Commit A

Unfortunately, I don't have a reduced test case for this yet, but we've noticed this in a production app (unfortunately closed source). Will provide more detail later.

`semantic-release` v4.3.5, Node 4.x.

**Comment by tlvince** [comment]
Note, I suspect this might be happening because Travis hasn't yet finished the previous build/semantic-release pushed a release. Perhaps limiting Travis' [concurrent jobs](https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Builds) to 1 would fix this?

**Comment by boennemann** [comment]
@tlvince Yeah seems like it to me. When `last-release` runs the other versions aren't released yet.

I'd suggest using the update branch button, or rebasing against the master branch first. That way you'll also get separate test runs for the combination of PRs, to make sure they're working together. Maybe look into GitHub's required status checks, which will enforce this.

I'm closing this here, because I think it's not a problem semantic-release can or should solve (in core).
I'm considering enabling protected branches/required status checks by default using the new API and making that part of the CLI.

Thanks for the report!

**Comment by tlvince** [comment]
Thanks! We'll give status checks a roll.
