### ISSUE TITLE
Built files not published to npm

### ISSUE THREAD

**Issue by colinmeinke** [semantic-release/semantic-release#168]
I'm not sure if this is a bug or if I'm doing something wrong, I assume the latter.

I have a repo that is attempting to use semantic release - https://github.com/colinmeinke/postcss-custom-props

It works great, apart from the fact that even though `prepublish` and `build` are [running on Travis](https://travis-ci.org/colinmeinke/postcss-custom-props), the output isn't available for consumption - https://npmcdn.com/postcss-custom-props@1.0.4

These are the relevant `scripts` in package.json:
```
 "scripts": {
    "build": "babel src --out-dir lib",
    "clean": "rimraf lib",
    "prepublish": "npm run clean && npm run build",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  }
```

I have also tried:

- Removing `prepublish` and [adding build into the semantic-release script](https://github.com/colinmeinke/postcss-custom-props/commit/80fbdb03cb1bebefacf60cee583e83b00372a5da) but [that had identical results](https://npmcdn.com/postcss-custom-props@1.0.1).
- [Moving the build step to .travis.yml](https://github.com/colinmeinke/postcss-custom-props/commit/6a16e6a6) but that was [also unsuccessful](https://npmcdn.com/postcss-custom-props@1.0.2).

**Comment by boennemann** [comment]
Hey @colinmeinke,
thanks for trying semantic-release. It appears to me that this is because you're having the lib folder in your `.gitignore` file. Try adding an additonal `.npmignore` file like this: 

```
/src
/test
/node_modules
```

or alternatively a "files" filed in your package.json:

```json
...
"files": [
  "lib"
]
```

After this npm will pick up your built files. You can verify if this is working correctly by running `npm pack`, which will create the tarball that would get sent to the registry.


Best,
Stephan

**Comment by colinmeinke** [comment]
You are totally right, that was the issue. Thanks so much :+1:
