### ISSUE TITLE
Breaking change relative to a non-released version

### ISSUE THREAD

**Issue by tusharmath** [semantic-release/semantic-release#181]
So, I created a feature `A` in the `develop` branch. Since it was in `develop` it did not get published. Now I want to update this particular feature to `A'`. These two features are not compatible with each other so while committing I added the `BREAKING CHANGE` tag. Now I am worried if this will be released as a breaking change.

**UPDATE**

I ran `npm run semantic-release` locally and realized that it would create a breaking release. Which I feel is incorrect.

**Comment by therealklanni** [comment]
Semantic Release uses your commit messages to decide how to release. If you do not want your package released as a major version (i.e. "breaking"), then don't write "BREAKING CHANGE" in your commit, since in your case it was never released before it was broken.

You can amend your commit to remove the "BREAKING CHANGE" note.

**Comment by tusharmath** [comment]
Got it thanks. Small request — can this be a part of the FAQs?

**Comment by therealklanni** [comment]
Feel free to submit a PR to update the docs.
