### ISSUE TITLE
Problem: ENOCHANGE There are no relevant changes, so no new version is released.

### ISSUE THREAD

**Issue by mprinc** [semantic-release/semantic-release#192]
I have problem with constant reporting:

```
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
```

I did manage to get new version and npm publish [before](https://travis-ci.org/mprinc/mappp/jobs/113259145), 
but now i am not able anymore, I did try to report new fix, then even [fake feature](https://travis-ci.org/mprinc/mappp/jobs/113276047l), etc, but no help.

I did also try on my local machine `npm run semantic-release` both before and after git publishing.

Here is the [github-project](https://github.com/mprinc/mappp) and [npm package](https://www.npmjs.com/package/mappp)

**Comment by pensierinmusica** [comment]
+1 I have the exact same problem

**Comment by thiagofelix** [comment]
Is it not the same case as #208? 
Please refer to my comment there.

**Comment by pensierinmusica** [comment]
@thiagofelix no it's a different case. The problem is that [commit analyzer](https://github.com/semantic-release/commit-analyzer/) will consider a new version only if there are commits of type `feat` or `fix`. I already sent a pull request to fix this: https://github.com/semantic-release/commit-analyzer/pull/13

If you'd like more details please check the conversation here: https://github.com/semantic-release/commit-analyzer/issues/12#issuecomment-203166512

Thanks, cheers!

**Comment by Moezalez** [comment]
@pensierinmusica correct me if I am wrong, but things like `refactor` and `style` do not change anything from the user's perspective and therefore shouldn't be a release.

**Comment by glebec** [comment]
Some of them may be debatable, but `docs` definitely changes the user experience.

**Comment by Moezalez** [comment]
@glebec AFAIK most people read the docs on github, and don't want to look at some completely unformatted markdown in their node_modules folder.

**Comment by glebec** [comment]
True, most don't. Some small number do. I have several times in the past. I guess it depends somewhat on whether you consider documentation to be part of the code source or a separate project.

**Comment by GarthDB** [comment]
@MoeSattler the README.md does change what is shown on npmjs.com. So I guess I have to change it to a `fix` type for now.

**Comment by cdaringe** [comment]
i'm unclear on how the intent is supposed to work.  why would "no change" be a non-zero exit code?  what's the convention such that i can merge things into master that _arent supposed_ to cut new releases?  i dont want CI failing because it discovered "hey, there's nothing new."  in fact, yes, i'm aware there's nothing new, _and that's ok--no reason to exit 1_!  just askin' what i'm missing, here

**Comment by terales** [comment]
@cdaringe semantic-release should run after successful build and this error won't trigger Travis CI build fail.

**Comment by cdaringe** [comment]
@terales, when`ENOCHANGE` happens for me, the cli exits with code 1, and on codeship, a non-zero exit code == fail.  are you suggesting that your CI is configured to allow it to fail?

**Comment by terales** [comment]
Nope. This is just default Travis CI behavior.

First it runs all tests. A non-zero exit here will fail build.
If there was no error with tests, Travis will mark build as passing and run `after success` scripts.
Result of `after success` scripts won't affect build state.

**Comment by terales** [comment]
@boennemann Would it be okay for you if I create PR with this changes in https://github.com/semantic-release/semantic-release/blob/a5cb9ea7f7a66657f95f0d913126e812adb6d9f8/bin/semantic-release.js#L116-L123

```javascript

if (err) {
  var errMessage = (err.code ? err.code + ' ' : '') + err.message

  if (err.code && err.code === 'ENOCHANGE') {
     log.warn(errMessage )
     process.exit(1)
  }

  log.error('pre', 'Failed to determine new version.')

  var args = ['pre', errMessage]
  if (err.stack) args.push(err.stack)
  log.error.apply(log, args)
  process.exit(1)
}

```

Which will exit with:

```
semantic-release Warn pre ENOCHANGE There are no relevant changes, so no new version is released.
```

**Comment by cdaringe** [comment]
IMHO (respectfully) `ENOCHANGE` possibly shouldn't be a thing.  "no change" is a valid and expected state, not an error condition.  using ENOCHANGE as a mean of control flow seems like misuse of the `Error` construct.

Grateful for this project, keep up the good work :)

**Comment by jhabdas** [comment]
> IMHO (respectfully) `ENOCHANGE` possibly shouldn't be a thing.

It's my understanding that error is preventing simple doc changes from causing a release for some users. If it were not an error, builds would not fail and the period I forgot to add to my `README` (because I'm a human, and I'm not perfect), would trigger a new patch release, and for many libraries, deployments to CDNs, etc. Am I missing something?

**Comment by mrfelton** [comment]
You can work around this using https://github.com/fullcube/customizable-commit-analyzer

**Comment by vanduynslagerp** [comment]
If there is no release on npm, `semantic-release` will analyze all the commits in your repo to figure out if a release is necessary. A new release (the initial `1.0.0`) will happen only if the `commit-analyzer` determines there is a commit in the history that should trigger a release.
By default it's: `perf`, `feat`, `fix` or a breaking change.

If your repo contains only commits that doesn't trigger a release, then the initial won't happen. This is the expected behavior as we don't want to make the initial release until there is actually something to release. For example if your firsts commits are something like `chore: Add license`, `ci: Set up Travis` etc we don't want to release. Once you push a commit like `feat: Initial release` for example the release will happen.

In addition, the releases rules are now completely customizeable: see [commit-analyzer#release-rules](https://github.com/semantic-release/commit-analyzer#release-rules)

Here is a config that would trigger a `patch` release for commits that starts with `docs(readme)`:
```json
{
  "release": {
    "analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {"type": "docs", "scope": "readme", "release": "patch"}
      ]
    }
  }
}
```

This issue cover a lot of things but I think they should be covered by this new plugin configuration. Some other problems are mentioned but there is corresponding issue already open.
Feel free to open a new issue if it's not the case.

**Comment by filipvh** [comment]
i seem not able to find how i can make it so a breaking change commit will trigger a build?

**Comment by benjamincharity** [comment]
Check out: https://github.com/semantic-release/semantic-release#commit-message-format

In short, if you add `BREAKING CHANGE: your message here` to a commit message, it should trigger a breaking change release

**Comment by filipvh** [comment]
its that if i do this i get:
[Semantic release]: Analyzing commit: BREAKING CHANGE: Testing breaking change
[Semantic release]: The commit should not trigger a release

**Comment by filipvh** [comment]
when i debug, the commit object that is given to analyze-commit.js 
```
{ type: null,
  scope: null,
  subject: null,
  merge: null,
  header: 'BREAKING CHANGE: Testing breaking change',
  body: null,
  footer: null,
  notes: [],
  references: [],
  mentions: [],
  revert: null }

```

**Comment by benjamincharity** [comment]
Hmm.. I _think_ the breaking change message needs to be in the body rather than the header. (not 100% on that..)

So your commit would need a line break before the breaking change message.
```bash
fix: I did a thing!

BREAKING CHANGE: I broke a thing!
```

**Comment by filipvh** [comment]
is there a way to change this? using config?

**Comment by benjamincharity** [comment]
I don't believe so.

I think they are trying to follow Github's native functionality somewhat. Github seems to only parse the body of PRs etc for functionality rather than the title (ie `closes #12` will auto close an issue - but only when in the _body_ of the PR)

I definitely don't know all the ins and outs of semantic release, so you may want to open a new issue asking if that is possible.

**Comment by pvdlg** [comment]
semantic-release uses by default the [Angular format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) that specify `BREAKING CHANGE` should be in the body.
You can change that by re-implementing a different [analyzeCommits plugin](https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/plugins.html#analyzecommits-plugin).

**Comment by travi** [comment]
you might consider https://github.com/bahmutov/simple-commit-message#as-plugin-for-semantic-release if you don't want to implement your own
