### ISSUE TITLE
Release failed

### ISSUE THREAD

**Issue by RWOverdijk** [semantic-release/semantic-release#199]
https://travis-ci.org/SpoonX/aurelia-api#L583

> semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
> semantic-release ERR! post   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
> semantic-release ERR! post   code: 404 }

I'm not sure why this happens.

**Comment by RWOverdijk** [comment]
It did publish to npm, so that's something. :)

**Comment by RWOverdijk** [comment]
Could you perhaps give me a pointer as to how I can debug this without actually releasing? I want to know what is causing the 404 because I want to use this module. The concept sounds really cool! If it works :p

**Comment by boennemann** [comment]
Hey @RWOverdijk,

while this part is definitely working, GitHubs error messages aren't really helpful. My first guess is that the GitHub token is not uploaded correctly/invalid/doesn't have the right access to the repository.

Please verify manually that the token is working so we can at least rule that out.

Thanks,
Stephan

**Comment by RWOverdijk** [comment]
@boennemann Hm yeah. It created a personal access token, does that matter though? Because I have full access to the repo and org, so shouldn't it just work? If not, where should I create the key?

**Comment by blacksonic** [comment]
@boennemann With the very same token one package works, the other one doesn't and getting this error message also.

**Comment by travi** [comment]
after getting past a travis-pro permissions issue for our "bot" account, as described in #337, i'm now seeing this issue in one of my private repos. as mentioned above, it does successfully publish the package to our private registry (nexus in this case) but fails to publish the release notes to github.

i'm fairly sure that this is not a permissions issue because another of our private packages with the same config is publishing to the registry and posting release notes to github successfully. plus, the process of determining that the builds are all complete requires interacting with the travis api after logging in through github using the same token as would be used here. the problem appears to be limited to this particular project so far.

I have tried to publish a version manually, hoping that it would give a more appropriate previous version to go back to, but that did not appear to have any impact.

also worth noting, this appears to be the same error as seen in #328 and #257, neither of which appear to have found a resolution.

**Comment by travi** [comment]
i figured out my problem by adding a log statement so i could see the information that was being used to create the release through the github api. in my case, the `repository` field in the `package.json` pointed to a wrong, but real repo (probably a copy paste issue when the project was created). fixing this enabled the next release to be created successfully.

while this might not be the same problem for others, definitely look at the data for creating the release and confirm the sanity of that data.

**Comment by pvdlg** [comment]
@RWOverdijk is this issue still happen with the last release of `semantic-release` ?
If yes can you provide an updated link to a failing CI build ?

**Comment by RWOverdijk** [comment]
I'm not using this anymore.
