### ISSUE TITLE
No README data found! on npm

### ISSUE THREAD

**Issue by finnp** [semantic-release/semantic-release#203]
I was just looking into why https://www.npmjs.com/package/@hoodie/log has a `No README data found!` message on npm after being published with `semantic-release`

I found out that  [normalize-package-data](https://github.com/npm/normalize-package-data) is adding `"readme": "ERROR: No README data found!"`  to the `pkg`  on this line: https://github.com/semantic-release/semantic-release/blob/caribou/bin/semantic-release.js#L16

A fix would be to just remove `normalize-package-data`. It doesn't seem to me like it's needed there.

**Comment by gr2m** [comment]
@ashleygwilliams ^^ this is the cause for the problem I had with the empty README files [like this one](https://www.npmjs.com/package/@hoodie/log), we had a few twitter conversations on it. Turns out it’s not npm registry or the npm publish command, it’s the [normalize-package-data](https://github.com/npm/normalize-package-data) package that is used within `semantic-release`. See example here: https://tonicdev.com/gr2m/56eacb53ee0381120071d499

**Comment by boennemann** [comment]
Amazing find by @finnp :+1: :100: Thanks so much.

Fixed version about to land as 6.2.1.

**Comment by gr2m** [comment]
:clap: :clap: :clap:
