### ISSUE TITLE
Option to write version to package.json

### ISSUE THREAD

**Issue by dbartholomae** [semantic-release/semantic-release#211]
Hi there! There have been plenty discussions on why semantic-release doesn't add the version number to `package.json`. But there actually are valid reasons to do it: Readme, Changelog files, documentations, and other files need the current version and it would be helpful to automate this in the build process.
Would there be interest in a PR that adds an option (or an additional step similar to pre and post) that writes the upcoming version to package.json?

**Comment by hbetts** [comment]
Why does the `README.md` file need the current version of the package to be in `package.json`?

**Comment by dbartholomae** [comment]
The current version should be part of the documentation files to make it easy to look up documentation for different versions.
Furthermore it's needed to create a changelog-file. And if the version isn't in the `package.json`, it's hard to automate :)

**Comment by zkochan** [comment]
Some tools need the version in the `package.json`. For instance, this tool ([update-notifier](https://github.com/yeoman/update-notifier)) checks whether the package has a newer version and notifies the user if there is one. It is very useful for CLI tools. I myself would love to use it in my package ([mos](github.com/zkochan/mos)) but cannot because I use semantic-release, which removes the version from the package.json

**Comment by zkochan** [comment]
oh, I just realized, the tool will actually work when installed. The version is added before publish. The problem is just when running the package from a local repo

**Comment by dbartholomae** [comment]
Yes, that's why it would be easy to add an option that just adds the upcoming version.

**Comment by timotgl** [comment]
I currently have the problem that two repos A and B use semantic-release and have no version in their respective `package.json`. For testing purposes, I'd like to include A as a dependency of B by specifiying the github branch. This however breaks `npm install`, because repo A is cloned and no version is found in `package.json`.

I resorted to putting a fake version number in each repo's `package.json` that is included in that way (the dependency graph is actually bigger than B->A).

Is there a better way to deal with this? I think doing  `npm publish` just to test a branch is too much overhead. I'm aware that I can use `npm link` locally.

**Comment by GarthDB** [comment]
When I'm making CLI tools I use the version field from the package.json to return a version in the command line.

**Comment by ifyio** [comment]
Is there any word on this? I'm making a cli tool and I need to be able to grab the version number from the package.json.

**Comment by mucsi96** [comment]
+1

**Comment by bluecamel** [comment]
+1

**Comment by jhabdas** [comment]
In my case I want to write the version to my libraries license banner to help track which version is being used when others include the minified source code. Seems like a pretty legit use case, right?

However, it would be an anti-pattern for semantic release to clobber your actual source code, and it could in could in theory spawn infinite recurring builds. That said, there's going to be better solution than manually managing the version field, so my suggestion is to remove `version` from your `package.json` file entirely and figure out another way. That's what I'm planning to do, at least.

**Comment by jhabdas** [comment]
Bailed on the timestamp idea because I build several different modules concurrently and didn't want each to have a different, ahem, build indicator (what the hell was I thinking).

Anyway, I **was able to use the version number** from the Semantic Release pre script as a part of my build process. Here's [how I did it](https://github.com/semantic-release/semantic-release/issues/283#issuecomment-289291480).

**Comment by Robophil** [comment]
Updating package.json... Very necessary.

**Comment by gr2m** [comment]
I’m still not convinced that the version number needs to be written into package.json in the source code. All the use cases mentioned so far are covered by tooling. If someone really needs it, it can be done with a post script and we can maybe document that or even implement that plugin, but this is not going to be part of semantic-release core

> @GarthDB  When I'm making CLI tools I use the version field from the package.json to return a version in the command line.

Can you elaborate? The package.json version number is set in packages published to the npm registry. If you `npm link` a local package, it will say `0.0.0-development` which makes a lot of sense as it is your local version.

**Comment by pvdlg** [comment]
Thinking about this a bit more...

## When is the version is `package.json` is present

| Phase  | Description | Version set  | 
|---|---|---|
| npm `test` script | Usually runs on Travis `script` step  | No |
| npm `prepublish` | Runs in `after_scuccess`, trigger by `npm publish`  | Yes |
|Any PR build | | No|
| Execution  | When a user install the package from npm and use it  | Yes

## Different scenario and solutions

### Displaying version in a cli tool
The package is published on npm with a `package.json` containing the published version.
So at runtime (i.e. when a user install your package from npm and use it) the version is available and can be used. A cli tool for example can read its `package.json` and display it's version.

### Publishing documentation or a website
The version might be required so the script can publish in a the proper subfolder (i.e. http:mysite.com/myproject/doc/vx.x.x).
This script can be run in the `after_sucess` phase, after `semantic-release`. For example `semantic-release pre && npm publish && semantic-release post && my-doc-publish-script`
The doc/website publish would run only when a release is done.

### Build script that require the version
The solution is to run the build script during the `prepare`, `prepublish` or `prepublishOnly` script phase. This way semantic-release would update the version in the `pre` phase, and npm would call the `prepare`, `prepublish` or `prepublishOnly` before calling `npm publish`.

### Using version from `package.json` during tests
This wouldn't work.
But I don't see a scenario that would require that. 
=> **Do you have an example of such scenario? **

### Using version from `package.json` in a PR
The version wouldn't be present for a PR build.
It doesn't make sense to do a release in a PR anyway and I don't see a scenario in which a script ran in a PR would need to access the version.
=> **Do you have an example of such scenario? **

=> **Is there any other scenario not covered here ? **

**Comment by gr2m** [comment]
Thanks for putting this together @pvdlg!

**Comment by pvdlg** [comment]
This feature has been implemented via the plugin https://github.com/semantic-release/git

**Comment by rodoabad** [comment]
@pvdlg by using that plugin, semantic-release will write to `package.json` and `package-lock.json`?
