### ISSUE TITLE
ES Modules

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#2133]
### The plan

Migrate `semantic-release` and all the core plugins to native ES Modules.

### The motivation

Node is moving to native ES Modules, so it's only a matter of time when we will be forced to do the same. 

The 2nd reason is that a growing number of dependencies were or will soon be upgraded by ESM, and we are blocked from further updates, and have a ton of open pull requests which I'd love to get rid of.

`semantic-release` is in a good position to do the upgrade with comparably little friction, as it's often times run in it's own environment. It's not a production dependency.

### Projects to update

I'll create dedicated issues for these shortly. We already started work on some of them.

- [x] #2543
- [x] https://github.com/semantic-release/commit-analyzer/issues/296
- [x] https://github.com/semantic-release/error/issues/247
- [x] https://github.com/semantic-release/github/issues/418
- [x] https://github.com/semantic-release/npm/issues/436
- [x] https://github.com/semantic-release/release-notes-generator/issues/296
- [x] https://github.com/semantic-release/env-ci/issues/154

**Comment by fgreinacher** [comment]
@travi @gr2m I can take care of migrating the gitlab plugin, how far away do you think we are from completing the migrations already started? Did you notice any roadblocks so far?

**Comment by travi** [comment]
we have discovered a few roadblocks like https://github.com/semantic-release/commit-analyzer/pull/297#issuecomment-996123935, which i haven't found the time to investigate very deeply yet. 

our original plan was to update all the plugins consumed by core and core itself all at the same time so that they could be released together. at this point, i think i'm leaning toward updating core first since that will be the primary breaking change that will directly impact consumers. that way the plugins could be converted individually without much user impact since they are consumed by core that was already converted. 

unfortunately, making progress on that has been blocked since getting a new M1 Macbook for myself since our test suite has some trouble running on that architecture. I've made some progress there that i still need to capture into an issue, but we may need some help from the community to remove that blocker.

once we get to the point where either core or core + the plugins that it directly consumes by default are converted, it would be great to get the gitlab plugin converted shortly after, so your help there is greatly appreciated.

**Comment by travi** [comment]
for folks following this effort, it is worth noting that this effort has been greatly slowed by https://github.com/semantic-release/semantic-release/issues/2478. if you are hoping to see this effort move forward sooner and you are able to help with https://github.com/semantic-release/semantic-release/issues/2478, we would greatly appreciate the help.

**Comment by travi** [comment]
i've been investigating the path forward a bit more recently and i think there is a worthwhile step we can take ahead of the actual ESM conversion that will reduce the complexity of the actual conversion a bit. 

`proxyquire` will need to be removed from the tests in order to complete the transition either way. most use of `sinon` is in the same situation, but even the uses where it could still work are probably not worth keeping with the cost of inconsistency. the switch from `proxyquire` to an alternative that works with ESM, like [testdouble](https://github.com/testdouble/testdouble.js/blob/main/docs/7-replacing-dependencies.md#es-module-support) is complex to accomplish as part of the transition, but can be mostly done in isolation.

i suggest we migrate all use of `proxyquire` and `sinon` to use `testdouble` instead and that we do that switch separately _ahead_ of the ESM switch. the esm switch would still require changing from `td.replace()` to `td.replaceEsm()` and adding the configuration of the `testdouble` loader, but at least the philosophical differences between the tools will be already covered. i hope to have a change to tackle this change in one of the projects fairly soon as an example to follow for the others.

**Comment by gr2m** [comment]
Sounds like a good approach.

**Comment by pierluigilenoci** [comment]
@travi any news about this?

**Comment by pierluigilenoci** [comment]
@travi @gr2m any news about this?

**Comment by travi** [comment]
@pierluigilenoci we've already asked you to stop pinging us directly. we've also pointed you to this issue, which provides visibility to the status.

**Comment by pierluigilenoci** [comment]
@travi considering that more than a year has passed, maybe it's time to focus on solving the problem instead of responding peeved to those who ask for updates. And in any case, there have been no updates on this issue for more than 4 months. Considering it's already been almost 4 weeks since #2478 was fixed...

xoxo

**Comment by travi** [comment]
> maybe it's time to focus on solving the problem instead of responding peeved to those who ask for updates

my response only included facts. you can find the progress of this work in the PRs that have been associated to this issue.

this is a volunteer managed project. progress has been made and the work will be completed as we are able. suggesting your preferred timeline is neither helpful in getting us past the challenges that this work presented, nor is it welcome. 

as stated previously, you can follow this issue and the related PRs if you are interested in status updates. please stop pinging folks, it does not change the timing of how the work gets done.

**Comment by pierluigilenoci** [comment]
@travi considering the [impact](https://nvd.nist.gov/vuln/detail/CVE-2021-3795) this has, inquiring about a possible ETA is not a crime. 
Especially when progress seems quite stalled.
I am aware that it is a voluntary project but this cannot be a justification for everything.
If the resources are not enough, the constructive solution is to ask for help.

**Comment by its-dibo** [comment]
really really waiting for this feature, I'm migrating all of my projects and packages into ESM, so I really need semantic-release to support ESM projects

**Comment by travi** [comment]
@its-dibo is there something in particular about the current state of semantic-release that you find to be holding up your progress? the core package has been converted to ESM already, but since semantic-release is normally leveraged through its own executable, the module type of semantic-release should not need to be coordinated with the module type of consuming projects.

**Comment by its-dibo** [comment]
I got this error @travi 
v21
![image](https://user-images.githubusercontent.com/57308531/228389431-9d72c8da-fee6-4832-856c-30455b173dc0.png)


config:
```
export default {
  branches: [
    "+([0-9])?(.{+([0-9]),x}).x",
    "main",
    "master",
    "next",
    "next-major",
    { name: "beta", prerelease: true },
    { name: "alpha", prerelease: true },
  ],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", { pkgRoot: "dist", tarballDir: "tarball", npmPublish: false }],
    [
      "@semantic-release/github",
      {
        assets: [
          {
            path: "tarball/**/*.*",
          },
        ],
      },
    ],

    [
      "@semantic-release/git",
      {
        message:
          "build: release ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
      },
    ],
  ],

  extends: ["semantic-release-monorepo"],
};
```

**Comment by travi** [comment]
@its-dibo please see https://github.com/semantic-release/semantic-release/discussions/2686#discussioncomment-4771995. semantic-release works fine with ESM projects, but you need to use a `.cjs` extension if you are using a js config. alternatively, you can use other formats supported by cosmiconfig if your config does not rely on js logic

**Comment by travi** [comment]
this effort is now complete for the core plugins (included as dependencies of the core package) 🎉 

there are still official plugins beyond this list of core plugins that will still need to converted at some point, but they are beyond the scope of this initial effort. if folks would like to help us convert the remaining plugins, we would welcome that help.

**Comment by its-dibo** [comment]
> @its-dibo please see [#2686 (comment)](https://github.com/semantic-release/semantic-release/discussions/2686#discussioncomment-4771995). semantic-release works fine with ESM projects, but you need to use a `.cjs` extension if you are using a js config. alternatively, you can use other formats supported by cosmiconfig if your config does not rely on js logic

using .cjs introduced a new issue
can not use `require()` with the esm package `@semantic-release/commit-analyzer`

**Comment by travi** [comment]
> using .cjs introduced a new issue
> can not use `require()` with the esm package `@semantic-release/commit-analyzer`

lets keep this conversation focused within #3006. details like this are likely to get lost on a completely unrelated closed issue like this
