### ISSUE TITLE
npm — 4.3.5, github — 6.2.2‚ why not release on NPM?

### ISSUE THREAD

**Issue by develar** [semantic-release/semantic-release#223]
Why 6.2.2 is not marked as latest? Are there known issues?

**Comment by Tzaphkiel** [comment]
I'm also curious why it suddenly went from v4.3.5 to v6.x.y with the latest release v6.3.0 not released on npmjs.
Could you please give us some more information ?

**Comment by goodmind** [comment]
Is there anything about this?

**Comment by vrtxf** [comment]
taken from my package.json:
```
"semantic-release": "^6.3.0",
```
You are probably running the `semantic-release-cli` v4 and then fail to update with `ncu`.

Bottom line is that all versions are on npmjs.com. 
This issue needs to be closed

**Comment by uglow** [comment]
Is there any explanation for this? The 6.x releases have been going for almost a year. Surely there is a good reason to switch this to @latest **or** advise why it must remain on the @next channel. Should we be using 6.x?

**Comment by ocombe** [comment]
Same thing here, the new version are not visible on npm by default, I think this has something to do with marking the versions as "beta" or something, which is why they are available with @next but not with @latest.
I find it funny that a lib that helps you publish packages with correct semver on npm has a problem with releasing a new version :P

**Comment by boennemann** [comment]
Fixed via https://github.com/semantic-release/semantic-release/releases/tag/v6.3.2
