### ISSUE TITLE
Semantic Release: Git

### ISSUE THREAD

**Issue by tada5hi** [semantic-release/semantic-release#2691]
### New feature motivation

It is a bit of a hassle to always install `@semantic-release/git` additionally, as it is included/used in most of the libraries I contribute to.
Since it is pretty lightweight, i see no real disadvantage to provide it by default to any installation.

### New feature description

Add `@semantic-release/git` to the **dependencies** section of the package.json

**Comment by travi** [comment]
this would not be in line with the goals of this package. it currently has two goals that are relevant for this topic: it contains the core functionality of semantic-release and also defines our recommended default combination of plugins while including those plugins as dependencies.

we do not include the git plugin in our recommended configuration because it is unnecessary for most projects. we recommend against updating the `version` property in the `package.json` in the repository, but instead recommend relying on the package registry as the source of truth of the released version. semantic-release does not rely on the `version` property and instead uses the git tag added to the commit when a release is created. the other common use for the git plugin is for maintaining a `CHANGELOG.md` file. when using github releases, which is the default behavior, the changelog file is redundant.

we understand that our defaults dont fit everyone, which is why semantic-release is very configurable. however, when the additional complexity is unnecessary, we dont want to encourage straying from the defaults. including the plugin as a default dependency could encourage more folks to use the git plugin unnecessarily.

in addition, we have plans for the future to split the default configuration further away from the core. at that point, there would be not be any plugins defined as dependencies of this package.
