### ISSUE TITLE
Write an inchjs verifyConditions plugin

### ISSUE THREAD

**Issue by GarthDB** [semantic-release/semantic-release#285]
I think [inchjs](https://github.com/rrrene/inchjs) could make an excellent verifyConditions (just like condition-travis) that aborts any release where defined thresholds aren't met.

I'd like to work on it myself, but I thought I would log the issue here as I think it through and begin working on it.

**Comment by pvdlg** [comment]
Similarly to this [comment](https://github.com/semantic-release/semantic-release/issues/68#issuecomment-352072226) wouldn't it be better to run `inchjs` in the test phase rather than in the release phase?

If the documentation threshold is not met, the test should fail, similarly to test coverage or linting errors. In that case the release wouldn't be even attempted.

**Comment by pvdlg** [comment]
Closing per previous comment. Please re-open if the previous comment is no accurate.
