### ISSUE TITLE
Cannot pass build number to use in tag format

### ISSUE THREAD

**Issue by AndriyGo** [semantic-release/semantic-release#3308]
### Current behavior

If I add build number to tag format as `"tagFormat": "v${version}+${process.env.build_number}"`, semantic release fails to analyse commits correctly.

Check out this repo: https://github.com/AndriyGo/semanticTest. A tag v1.0.0+1 exists. However, no matter from which branch I call `build_number=2 npx semantic-release` it wants to create a new release. If I call `build_number=1 npx semantic-release` it detects tag `v1.0.0+1` and doesn't publish a release. So, looks like it doesn't want to ignore build number and considers `+${process.env.build_number}` to be an important identifier. Hence, when analysing commits, it only analyses if releases which end with `+${process.env.build_number}` exist.

This is a bug because as was suggested by @pvdlg in #835 this is supposed to be a workaround for passing build number which would otherwise be ignored by semantic release. However, it treats the change in build number the same way as it would treat the migration of tag format from `v${version}` to `version${version}`...

### Expected behavior

It is supposed to correctly detect that tag `v1.0.0+1` is a proper release whose version is 1.0.0 and create releases from there.

### `semantic-release` version

v23.1.1

### CI environment

terminal

### Plugins used

commit-analyzer
release-notes-generator

### `semantic-release` configuration

{
  "ci": false,
  "branches": ["main", {name: 'develop', prerelease: true}],
  "tagFormat": "v${version}+${process.env.build_number}",
  "plugins": ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator']
}

### CI logs

From main branch:

[5:58:20 PM] [semantic-release] › ℹ  Running semantic-release version 23.1.1
[5:58:20 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:58:20 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:58:23 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/AndriyGo/semanticTest.git
[5:58:24 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[5:58:24 PM] [semantic-release] › ℹ  No git tag version found on branch main
[5:58:24 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[5:58:24 PM] [semantic-release] › ℹ  Found 3 commits since last release
[5:58:24 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci: fix reseaserc syntax
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix:Let's test semantic version
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: Initial commit
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[5:58:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 3 commits complete: minor release
[5:58:24 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:58:24 PM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[5:58:24 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:58:24 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:58:28 PM] [semantic-release] › ✔  Created tag v1.0.0+2
[5:58:28 PM] [semantic-release] › ✔  Published release 1.0.0 on default channel

**Comment by AndriyGo** [comment]
In fact, I have found where the issue is and I will try to create a PR now :)

**Comment by travi** [comment]
please explain the use case. just because it is allowed by the semver spec does not mean it necessarily meets the goals of the semantic-release project. associating the build number to the version seems better solved by provenance than by semver. what are you trying to accomplish by including it?

**Comment by AndriyGo** [comment]
In my case I simply want to store the build number of my iOS app alongside the released version in a git tag.

Current implementation has a bug as plus symbol which immediately supersedes the version number is specified as build meta by semver and semantic release uses it, albeit incorrectly in this case

**Comment by AndriyGo** [comment]
@travi I have already submitted PR with a fix and test coverage – it is a super minimal change which brings tags analysis in line with how they should work according to semver

**Comment by travi** [comment]
> it is a super minimal change

this is not helpful when determining whether it is appropriate for the project. small changes can be big maintenance burdens over the life of a project, especially when the maintainers dont fully understand the use case.

> I simply want to store the build number of my iOS app alongside the released version in a git tag

i'm not familiar with the iOS release process. as mentioned in the previous issue that you referenced, npm does not honor such metadata. does the iOS release process? is this truly only for the tag, or does it need to be submitted to the iOS process as well? 

how are you coordinating the iOS part of the process? are you using a semantic-release plugin that is specfic to iOS? using our exec plugin? something outside of the semantic-release workflow?

**Comment by AndriyGo** [comment]
Sure, I can outline my use case, although I do think that it is a bit irrelevant in this case. As stated in the semantic-release docs

> strictly following the Semantic Versioning specification and communicating the impact of changes to consumers.

So, as we talk about a case in which semantic-release is not following the spec which it is supposed to follow – it looks like a bug which should be fixed 😃

Anyway my use case is the following. I have several apps in the same repository. For ease, think about a free version and a paid version. I strictly use semantic-release for versioning, but sometimes I do not update apps at the same time.

Let's say I developed a feature and want to try it out in the free version first. So I publish, let's say v1.1.0 and release my free app with build number 2.

Then, while I am gathering data – I improve my CI implementation with one commit. After this I decide that I want to ship this feature to the paid app as well.

I run semantic-release in dry mode and see that no new release is available. So, I can set the same version as was in my last release. However, I do not want to set the same build version because even though my commits since last release do not deserve a new version - my repo was changed. I am not on the same commit as before and I want to differentiate it.

So I want to ship my paid app as v1.1.0 but with build version 3. And I would like to have two tags in this case - v1.1.0+2 and v1.1.0+3.

This way if I ever need to debug the app - I know exactly at what point and against which repo codebase each version was shipped.

Another use case was outlined in #835 which I have quoted originally

**Comment by AndriyGo** [comment]
Actually I've just realised that my PR doesn't strictly follow semver as well. I will update it tomorrow to fully reflect the spec.

**Comment by travi** [comment]
> So, as we talk about a case in which semantic-release is not following the spec which it is supposed to follow – it looks like a bug which should be fixed 😃

our docs are not always perfectly worded, but it is not a bug that we do not implement _all_ of what is possible according to the semver spec. the strictness that is intended by the statement that you quoted is related to how the segments are bumped to communicate impact. it is not about completeness. we also intentionally chose not to implement the differences in bumping behavior for pre-v1.0.0 versions because use does not align with the practices we encourage, even though the semver spec allows it.

> Anyway my use case is the following. I have several apps in the same repository.

i appreciate the additional explanation of your use case, but unfortunately what you describe is a use case we do not support, despite lots of requests for various types of monorepo project structures. we support projects that have a single releasable asset per repository only. we understand that projects choose to use such structures, but we are not at a point where we can justify including the extra complexity of supporting monorepos in the official semantic-release project. there are extensions to semantic-release maintained by our community that provide various approaches to supporting monorepos, but we do not plan to add support, especially in the short term.

**Comment by AndriyGo** [comment]
One doesn't need to have a monorepo to want this feature.

Suppose I have one app and I ship a new feature on `develop` branch.

While my testers are fixing it, I commit some CI improvements. No new release is needed in this case, but I may want to rebuild the app as I am no longer on the same commit as before. And sure, I can distinguish these by commits, as I am doing now. I bump the build version and push a commit `build: v1.1.0 (3)`.

But now I have two sources of truths for my releases. Semantic release creates a v1.1.0 tag **the first time** it sees these changes, but the information on any new rebuilds is marked by commit messages, not by tags. In my opinion this is not great and kind of defeats the purpose.

An alternative could be for me to add those tags myself. So, the first 1.1.0 commit would have two tags: `v1.1.0` for semantic release and `v1.1.0+3` for build tracking. However, I think this is cumbersome.

I encourage you to check lengthy discussion on this in the semver issues: https://github.com/semver/semver/issues/95 and https://github.com/semver/semver/issues/136 (links to many other issues).

There are many examples when this feature may be useful.

In my opinion the following behaviour should be standard:

```
+-------------+--------------------+---------+
|     tag     |     tagFormat      | version |
+-------------+--------------------+---------+
| v1.1.0      | v${version}        | 1.1.0   |
| v1.1.0+abcd | v${version}        | 1.1.0   |
| v1.1.0+(3)  | v${version}        | -       |
| v1.1.0a+bcd | v${version}        | -       |
| v1.1.0a     | v${version}        | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+${var} | 1.1.0   |
| v1.1.0+abcd | v${version}+${var} | 1.1.0   |
| v1.1.0+(3)  | v${version}+${var} | -       |
| v1.1.0a+bcd | v${version}+${var} | -       |
| v1.1.0a     | v${version}+${var} | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+(3)    | -       |
| v1.1.0+abcd | v${version}+(3)    | -       |
| v1.1.0+(3)  | v${version}+(3)    | 1.1.0   |
| v1.1.0a+bcd | v${version}+(3)    | -       |
| v1.1.0a     | v${version}+(3)    | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+abcd   | 1.1.0   |
| v1.1.0+abcd | v${version}+abcd   | 1.1.0   |
| v1.1.0+(3)  | v${version}+abcd   | -       |
| v1.1.0a+bcd | v${version}+abcd   | -       |
| v1.1.0a     | v${version}+abcd   | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}a       | -       |
| v1.1.0+abcd | v${version}a       | -       |
| v1.1.0+(3)  | v${version}a       | -       |
| v1.1.0a+bcd | v${version}a       | -       |
| v1.1.0a     | v${version}a       | 1.1.0   |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}a+bcd   | -       |
| v1.1.0+abcd | v${version}a+bcd   | -       |
| v1.1.0+(3)  | v${version}a+bcd   | -       |
| v1.1.0a+bcd | v${version}a+bcd   | 1.1.0   |
| v1.1.0a     | v${version}a       | -       |
+-------------+--------------------+---------+
```

**Comment by AndriyGo** [comment]
Although on a second thought, I think it is best to ensure that tags are analysed according to this regex which is referenced in semver spec: https://regex101.com/r/vkijKf/1/

This would mean that in my table above, `v1.1.0a` etc would be invalid, even if `tagFormat` is set to `v${version}a`.
```
+-------------+--------------------+---------+
|     tag     |     tagFormat      | version |
+-------------+--------------------+---------+
| v1.1.0      | v${version}        | 1.1.0   |
| v1.1.0+abcd | v${version}        | 1.1.0   |
| v1.1.0+(3)  | v${version}        | -       |
| v1.1.0a+bcd | v${version}        | -       |
| v1.1.0a     | v${version}        | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+${var} | 1.1.0   |
| v1.1.0+abcd | v${version}+${var} | 1.1.0   |
| v1.1.0+(3)  | v${version}+${var} | -       |
| v1.1.0a+bcd | v${version}+${var} | -       |
| v1.1.0a     | v${version}+${var} | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+(3)    | error   |
| v1.1.0+abcd | v${version}+(3)    | error   |
| v1.1.0+(3)  | v${version}+(3)    | error   |
| v1.1.0a+bcd | v${version}+(3)    | error   |
| v1.1.0a     | v${version}+(3)    | error   |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}+abcd   | 1.1.0   |
| v1.1.0+abcd | v${version}+abcd   | 1.1.0   |
| v1.1.0+(3)  | v${version}+abcd   | -       |
| v1.1.0a+bcd | v${version}+abcd   | -       |
| v1.1.0a     | v${version}+abcd   | -       |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}a       | error   |
| v1.1.0+abcd | v${version}a       | error   |
| v1.1.0+(3)  | v${version}a       | error   |
| v1.1.0a+bcd | v${version}a       | error   |
| v1.1.0a     | v${version}a       | error   |
| ----------- | ------------------ | ------- |
| v1.1.0      | v${version}a+bcd   | error   |
| v1.1.0+abcd | v${version}a+bcd   | error   |
| v1.1.0+(3)  | v${version}a+bcd   | error   |
| v1.1.0a+bcd | v${version}a+bcd   | error   |
| v1.1.0a     | v${version}a+bcd   | error   |
+-------------+--------------------+---------+
```

I guess it touches on a discussion regarding what to do if `tagFormat` is specified in semver non-compatible format.

I don't think it is reasonable to allow non-compatible format, apart from some id **before** the `${version}`, such as `v${version}`.

The question is what to do if `tagFormat` is non-compatible. Should semantic-release exit with error? Or should it proceed creating a tag which it wouldn't process itself?

I think it should exit with error and warn the user that the specified `tagFormat` is invalid.

**Comment by AndriyGo** [comment]
@travi I've finished working on my PR – would appreciate if you could have a look at it! #3309

**Comment by travi** [comment]
> One doesn't need to have a monorepo to want this feature.
> 
> Suppose I have one app and I ship a new feature on `develop` branch.
> 
> While my testers are testing it, I commit some CI improvements. No new release is needed in this case, but I may want to rebuild the app as I am no longer on the same commit as before. And sure, I can distinguish these by commits, as I am doing now. I bump the build version and push a commit `build: v1.1.0 (3)`.

you are describing using gitflow to test published releases before promoting to stable releases for your consumers. you can find consistent messaging through previous issues that this is also a workflow that is not officially supported by semantic-release

> Lastly I would like to note that I didn't come up with this idea myself. I have googled this issue and found #835 where @pvdlg suggested to use `v${version}+${build}` to achieve this.

that is a six year old issue that has not risen to high enough priority to move forward up to this point, so we need not only a valid use case that we would consider supporting officially, but one that would be desired by enough of our user base to justify the maintenance burden. i dont think we have established that at this point.

> Although on a second thought, I think it is best to ensure that tags are analysed according to this regex which is referenced in semver spec: [regex101.com/r/vkijKf/1](https://regex101.com/r/vkijKf/1/)

i appreciate this investigation and i think there is merit to such an approach if we were to decide to revisit. however, this would result in needing to release a breaking change that could impact many existing users in order to support use cases that are outside our current support for reasons i've outlined above.

> I've finished working on my PR – would appreciate if you could have a look at it!

while i appreciate the effort, i encourage you to save the effort of investing in a PR before establishing agreement with maintainers first. we encourage this in our contribution guide in hopes of avoiding disappointment around investment that ends up being declined. for now, i'm going to close the PR. before re-opening, please make sure there is an agreed upon approach.

**Comment by AndriyGo** [comment]
The biggest issue with not having the ability to add build meta in my opinion is the need to store unneeded commits where only build number is bumped. On iOS (and I think on Android), every submitted build needs to have a different version. So, you may upload v1.0.0 (1), then v1.1.0 (2), v1.2.0 (3) etc.

If semantic-release correctly processed build meta, it would allow to store this info in the tags rather than commits. Suppose I finished working on a new release and there is a new feature. I run semantic release and see that the next version is 1.3.0. Great!

However, I also MUST set a build number. To do that, I need to increment the existing build number. But because I cannot pass it to semantic release to be used as build meta, I need to make a commit with this bump! If it was stored in build meta, I could read it, bump it, work with it and then discard any changes.

So my ideal git log would look like this:
```
commit: abcdef (tag: v1.3.0+4)
feat: Awesome feature for 1.3.0
```

Instead it is forced to look like this:
```
commit: abcdef (tag: v1.3.0)
build: v1.3.0 (4)

commit: ghijkl
feat: Awesome feature for 1.3.0
```

I would also like to stress, that the current implementation is objectively wrong. I understand your argument about this feature not being widely needed, hence no need to maintain it. However, this is reasonable when we talk about semantic-release adding build meta on its own. It is not reasonable when semantic-release is not parsing existing tags correctly.

If my tagFormat is set to `v${version}` and one of my tags is `v1.1.0+1` – the current implementation assumes that its version is `v1.1.0+1` – this is **wrong**. The fact that semantic-release is not reading this correctly as 1.1.0 is a bug.

So, while I understand that you do not wish to fully support adding build meta through tag format, variables, etc, I would like to discuss the possibility of limiting my PR to only ignoring build meta when reading tags so that semantic-release could be used in dry run mode for cases such as mine. I don't mind running it in dry run to determine next version and then adding build tag myself.

**Comment by travi** [comment]
> The biggest issue with not having the ability to add build meta in my opinion is the need to store unneeded commits where only build number is bumped. On iOS (and I think on Android), every submitted build needs to have a different version. So, you may upload v1.0.0 (1), then v1.1.0 (2), v1.2.0 (3) etc.

i admit that i still dont understand the usecase fully. i'm not an iOS or android developer, so i'm not familiar with the details there. are you actually submitting to the app store in a way that is coordinated by semantic-release? if so, the build number should be available to that step in the same way it would be available to the step that creates the tag, correct? if the submission step is already out of band of the semantic-release steps, it seems like it should not be much additional effort to add the step of collecting that information to an already manual list of steps

> However, I also MUST set a build number.

could you link to any reference about this so i can understand better. is the goal of this to establish some level of provenance, but in a not automated or cryptographically verifiable way?

> To do that, I need to increment the existing build number. But because I cannot pass it to semantic release to be used as build meta, I need to make a commit with this bump!

you lost me with this detail. if semantic-release is already releasing a new version, why is an additional build required beyond the one that produced the new release?

> It is not reasonable when semantic-release is not parsing existing tags correctly.
> 
> If my tagFormat is set to v${version} and one of my tags is v1.1.0+1 – the current implementation assumes that its version is v1.1.0+1 – this is wrong. The fact that semantic-release is not reading this correctly as 1.1.0 is a bug.

please clarify what you mean by "correctly". are you suggesting that our implementation does not align with our documentation or intended subset of semver support? or do you mean compared to the full semver spec? reminder that while we are heavily guided by the semver spec and intend to be faithful to it for the subset that we support, we do not intend to support the full spec and have intentionally chosen to _not_ support some parts of it.

> ignoring build meta when reading tags so that semantic-release could be used in dry run mode for cases such as mine

this suggests to me that your assertion that this is a bug is related to the part of the semver spec that we currently do not support. i'm not entirely against being convinced that there are valid enough use cases to reconsider our support level for this part of the spec, but i absolutely would not consider the current implementation a bug. 

ignoring part of the tag is a deviation from how tags translate to versions today. i'm honestly not convinced that _ignoring_ would even be the correct handling of that metadata. some ecosystems do ignore/not support that information, but i'm not sure that would be appropriate across all plugins. there are many dimensions to consider to support such a feature well and we would not be willing to support it without the intention to support it well. this carries a heavy weight when considering if there is enough justification from our user base to support the maintenance burden. this doesnt mean it can't be justified, but i'm having a hard time considering how little it has been requested in the history of the project

**Comment by Hernanm0g** [comment]
I second @AndriyGo on the importance of having the build_number as part of the semantic-release versioning.

My company's SRE team uses this standard for versioning:
```
Version Standard Policy

Description
Checks that your version matches versioning standards at production deployment time. The standard currently is a 4 digit version major.minor.patch.build (ex. 1.2.0.789)

Outcomes
Policy fails if the ref name does not match the standard when trying to deploy to production

Remediation
Update your pipeline/workflow to align with the versioning standard
```

This Standard is required for all our applications, disregard if they are web projects, android, iOS... please consider giving importance to this request as we have many teams that are working with semantic-release and their pipelines are constantly alerting  that this policy is not met.

**Comment by travi** [comment]
@Hernanm0g your request differs from @AndriyGo's request. The format you are requesting is not valid semver, so it is even further from what we would be willing to support in semantic-release

**Comment by Hernanm0g** [comment]
Thanks @travi for the quick response.
I slightly disagree with you on my request differing from @AndriyGo . We want to be able to have a tagFormat as
`"tagFormat": "${version}.${process.env.build_number}"`, so the same request applies:

It is supposed to correctly detect that tag 1.0.0.6789 is a proper release whose version is 1.0.0 and create releases from there.
As of today, I am able to remove the v prefix from the tag, but we would love to be able to add the build_number. 

Regarding the format not matching semver, you are right.
Thanks again.

**Comment by AndriyGo** [comment]
> could you link to any reference about this so i can understand better. is the goal of this to establish some level of provenance, but in a not automated or cryptographically verifiable way?

Sure, when I release an app I need to set what's known as [CFBundleVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion) (build number, mostly internal) and [CFBundleShortVersionString](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) (user-visible).

Please check [this](https://stackoverflow.com/questions/19726988/what-values-should-i-use-for-cfbundleversion-and-cfbundleshortversionstring) discussion to better understand how people are using it.

While it is theoretically possible to use the same for both, even Xcode cloud doesn't, [they increment build version by 1 on each build](https://developer.apple.com/documentation/xcode/setting-the-next-build-number-for-xcode-cloud-builds).

This is what I do in my project as well. I believe that previously you had to use this scheme for the build number. In any case - many people are doing this.

Moreover, you [cannot actually upload two identical builds](https://github.com/fastlane/fastlane/discussions/20743). So, imagine that you introduced a bug because of a mistake in your ci flow. You fix the error, try to rebuild and now you are stuck as semantic-release does not support multiple builds for the same release whilst you must change build number to resubmit your build.

> you lost me with this detail. if semantic-release is already releasing a new version, why is an additional build required beyond the one that produced the new release?

I'll describe my ideal workflow a bit more. Imagine that I fix a certain bug after the latest release (2.0.0 build number 100). And now I am ready to release my work. Semantically my next release should be 2.0.1. And my build number should increment to 101. Obviously, this requires changing some files in my repo. If I was able to store both of these in the tag (2.0.0+101) I could discard these changes to the repo. So, it would only contain the changes I make to the actual code, without a need to store commits such as "build: 2.0.1 (101)" which include only bumping of versions in several files.

As of now, I am unable to do this. Semantic release is working and I have setup my CI so that I can increment builds. But it requires me to keep these unneeded commits in the repo :)

> please clarify what you mean by "correctly".

I understand that you may not want to introduce an ability to set tags with variable during release process etc. However, if my tag format is set to "v${version}" and one of my tags is "v1.0.0+1", current implementation ignores this. And this is clearly a mistake. Because such a tag is in full compliance with SemVer and it means "version 1.0.0 build meta 1".

At a bare minimum, semantic-release should correctly identify this when analysing existing tags, even if it doesn't support setting build meta automatically itself. In such a case, I could utilise semantic-release in dry run mode, add build meta myself and know that semantic-release would be able to correctly read "v1.0.0+1" tag.

> The format you are requesting is not valid semver, so it is even further from what we would be willing to support in semantic-release

Their format is what some suggest for CFBundleVersion :) If there was an ability to add build meta through plus symbol (which is semver compliant), @Hernanm0g could easily substitute "+" with "." and get to the format which his company requires.

**Comment by AndriyGo** [comment]
@travi I would propose the following minimalistic PR.

Given the following commit history:

```
commit abcdef2 (HEAD -> develop)
    fix: New bug fix

commit abcdef1 (tag: v0.1.0+1)
    feat: First feature
```

Running semantic-release **must** suggest version `v0.1.1` if tagFormat is set to `v${version}`

The fact that it doesn't is a bug.

I totally understand that adding support for `"tagFormat": "${version}.${process.env.build_number}"` may not be of interest to you, but at least it should correctly read and analyse tags

**Comment by travi** [comment]
> Running semantic-release **must** suggest version `v0.1.1` if tagFormat is set to `v${version}`
> 
> The fact that it doesn't is a bug.

please stop claiming that behaviors of semantic-release are _bugs_ just because they are part of the semver spec, especially when they are from subsets that we intentionally do not support, as already explaining in this thread in https://github.com/semantic-release/semantic-release/issues/3308#issuecomment-2118456008. doing so is making me loose my patience to even try to understand if there is a use case related to your goal that we might be willing to support

**Comment by AndriyGo** [comment]
@travi I fully understand that you do not want to support all possible SemVer scenarios. However, I wish to defend my statement that the current implementation has a bug.

**Reading tags**

If my repo has tags `v1.0.0+build1`, `v1.1.0+macOS`, `v1.2.0+ios` etc and then I run semantic release with tagFormat set to `v${version}`, the fact that it doesn't understand these tags is a bug, not a feature. Semantic release may not support creating such tags on its own, but it should read them because they are clearly SemVer compliant.

I am not 100% sure what you meant by pre-v1.0.0 behaviour. However, I tested it a little bit and I see that semantic release is able to read all tags pre-v1.0.0 **correctly**.

**Adding tags**

If what you say regarding not wishing to support creating such tags is true, then semantic release has an even bigger bug. Because as of now, you are allowed to set your tagFormat to `v${version}+${process.env.build_number}`. Not only is it allowed – semantic release will correctly create such a tag, for example `v1.0.0+3`. The problem is that it will not be able to analyse it later.

And that is totally confusing. At a bare minimum:

1) Such tag format is SemVer compliant
2) Semantic release allows it
3) It breaks completely when dealing with such tags in the next release
4) Docs do not mention anywhere that this is not allowed

I am sorry, but these 4 clearly describe a bug.

**Poposal**

Re: reading tags – I propose that they are read in accordance with SemVer. Ie `v1.0.0+build1` translates to `v1.0.0`. Adding this is easy, it just requires ignoring anything starting with a `+` and should not be a maintenance burden.

Re: adding tags – this is really up to you to decide. My original PR allowed adding build meta. However, I understand that you may not wish to support such use cases. If that is true, I propose to modify my PR to make sure that:

1) Such tag format becomes illegal
2) Docs are updated to reflect this

**Comment by travi** [comment]
> am not 100% sure what you meant by pre-v1.0.0 behaviour.

while the tags might be read, semantic-release does not handle bumping to the next version according to the semver spec. this was an intentional project choice


> but it should read them because they are clearly SemVer compliant

again, just because it is in the semver spec does not mean it makes sense to be part of this project

> I wish to defend my statement that the current implementation has a bug.

proving that this falls into your definition of bug doesnt interest me if the desired feature is out of scope for the project. i have been trying to ask questions to better understand the use case in order to determine if there is a part of it that makes sense to be within the scope of the project. until we get the facts laid out in a way that helps determine how much, if any, of this makes sense in the scope of semantic-release, insisting that it is a bug is only distracting from what could move this forward.

> Docs are updated to reflect this

this may be where we land and i think it is completely valid to follow up with at least that, but doing so requires determining if we are willing to accept more of this feature as intended behavior or if we officially consider it out of scope. that decision has not been made officially yet, so it is possible that we could land where we decide it is worth adding support for. however, that requires convincing our maintainers, including me, that it is both a useful feature and will gain enough usage to justify the maintenance burden. 

> Adding this is easy

i already mentioned this earlier in the thread, but i will say it more clearly. this is one of the fastest ways to convince a maintainer that we should not accept the proposal. there are many more considerations we need to account for than just the ones that satisfy your part of this suggestion. if we do add official support for build metadata, i dont believe it would be as simple as ignoring it when reading tags. we would likely need to make that metadata available throughout the release lifecycle, which would change the current approach of passing the version through semantic-release to plugins, etc


i have not had time yet to read through some of the links you've provided above. i intend to do so later today and i will make one more attempt to frame what i understand of the workflow to try to align it to how semantic-release is intended to work

**Comment by AndriyGo** [comment]
`version` is extracted in `getTags`. So, as long as it is read correctly there – it will be passed correctly in other parts.

Here are some examples with current behaviour:

1) tagFormat set to `v${version}+abcd`, tag `v1.1.0+abcd` – gives version 1.1.0. That is correct, but probably shouldn't be allowed if build meta is not supported.

2) tagFormat set to `v${version}a`, tag `v1.1.0a` – gives version 1.1.0. This tag is not SemVer compliant at all, yet it is allowed and read.

In fact I double checked – my PR only addressed the reading of tags. Semantic-release already allows the creation of tags in any format, including non-SemVer compliant ones, (such as `v1.1.0blablabla`).

**Comment by AndriyGo** [comment]
SemVer spec contains the following wording regarding build metadata:

"Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version."

It also states that "The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/html/rfc2119)"

And RFC 2119 clearly states the following:

> MAY   This word, or the adjective "OPTIONAL", mean that an item is
   truly optional.  One vendor may choose to include the item because a
   particular marketplace requires it or because the vendor feels that
   it enhances the product while another vendor may omit the same item.
   An implementation which does not include a particular option MUST be
   prepared to interoperate with another implementation which does
   include the option, though perhaps with reduced functionality. In the
   same vein an implementation which does include a particular option
   MUST be prepared to interoperate with another implementation which
   does not include the option (except, of course, for the feature the
   option provides.)

I see no other way to read this than "a tool MAY support adding build metadata (but is not required to do so), but it MUST correctly process tags generated by any other tool, which includes build metadata"

**Comment by travi** [comment]
> 1. tagFormat set to `v${version}+abcd`, tag `v1.1.0+abcd` – gives version 1.1.0. That is correct, but probably shouldn't be allowed if build meta is not supported.

this is a point where you are contradicting yourself when you relate semantic-release's behavior to the semver spec. it isnt as simple as saying that dropping the build metadata is "correct". `1.1.0+abcd` is a valid version according to the spec. it is undefined, so far, what the semantic-release behavior should be around handling that version. it sounds like your use case would want the build metadata dropped from the version. npm would also need it dropped. 

however, i dont think it is safe to define the generic semantic-release behavior to assume it is always safe to drop. we may need to retain the build metadata as part of the version for some scenarios. do we retain it as a string and handle dropping it in specific plugins, or do we parse the parts into a complex object so that the plugins have more meaningful information to leverage without needing to parse in various locations?

**Comment by AndriyGo** [comment]
@travi getTags returns both `version` as parsed and the original git tag.

If any plugin needs to analyse the tag itself, for whatever purposes, then it should be analysing the tag.

However, I totally agree that migration-wise more feedback may be needed before releasing this, as, theoretically, someone could be using the current flow in this edge case

**Comment by AndriyGo** [comment]
That said – if someone was using it, they were supposed to cover it with tests as required by Contribution guidelines :) And my PR didn't break any tests.

**Comment by travi** [comment]
> the information on any new rebuilds is marked by commit messages, not by tags. In my opinion this is not great and kind of defeats the purpose

this is the part that still confuses me about this proposed workflow and is the part that i think might be incompatible with semantic-release. semantic-release does not support the concept of rebuilds of the same release. either a release is successful or a failure. if it was successful, it is assumed to be fully released to end consumers. if it doesnt complete a full release, it should be considered a failed release and retried. 

retrying is a bit less automated, of course, because you need to understand your release process to know how far it made it through the release process and how to undo the steps that succeeded. we've had requests to better automate the ability to retry, but the variance between workflows makes that difficult and some release steps are enforced as immutable, so cannot be undone.

because of the approval process, the iOS release flow feels somewhere between our pre-release workflow where you can release a release-candidate and then promote to a stable release after getting feedback (it isnt clear to me if the iOS process enables the idea of promoting a release-candidate after approval) and the normal release process where a denied build should be considered a failed release.

in any of these cases, semantic-release would expect additional commits to resolve whatever the reason was for the denial, resulting in a new release of some kind. from the options above, that could be a new release candidate, like 1.1.0-rc.2, a retry of a failed and rolled back release, or a release with a new version. if changes are required to resolve a problem with the previous release, commits get made to include those changes and a _new_ version is created, full-stop. there is no concept of "rebuilding" a release with new changes. am i still misunderstanding the desired workflow here?

> If any plugin needs to analyse the tag itself, for whatever purposes, then it should be analysing the tag.

please refrain from asserting how we should make design decisions about the project. there are options that need to be considered that each have trade-offs and we will not simply choose the one that makes it convenient to add this feature.

> tagFormat set to `v${version}a`, tag `v1.1.0a` – gives version 1.1.0. This tag is not SemVer compliant at all, yet it is allowed and read.

i'm not aware of us making claims that the tag format is required to be semver compliant. in fact, there are known use cases that would break if we enforced that. consider the community managed [semantic-release-monorepo](https://github.com/pmowrer/semantic-release-monorepo) unofficial extension to enable use in a monorepo. that extension uses tags with a format of `<package-name>-v<semver-compliant-version>`. while we dont officially support monorepos, we dont want to prevent the community from adding such support and forcing tags to only be semver compliant would not allow extension in the way that was chosen for that project

> 1. tagFormat set to `v${version}+abcd`, tag `v1.1.0+abcd` – gives version 1.1.0. That is correct, but probably shouldn't be allowed if build meta is not supported.

i think i'm still missing something about your request. i thought you've been saying this whole time that semantic-release _does not_ ignore the build metadata. from this, it sounds like it is ignoring it like you want. please clarify what is not happening that i'm still misunderstanding
