### ISSUE TITLE
semantic-release WARN pre undefined

### ISSUE THREAD

**Issue by PatrickHeneise** [semantic-release/semantic-release#337]
```
> semantic-release pre && npm publish && semantic-release post
semantic-release WARN pre undefined
```

someone did a manual release (`npm version minor`) on our repos, now this is all I see from semantic-release. How do I get this back working?? There's absolutely no information what's failing, not even with `debug: true`

**Comment by jcjones1515** [comment]
I'm hitting something similar @PatrickHeneise, did you have any luck?

**Comment by PatrickHeneise** [comment]
No, having this issue for a while already, no idea how to resolve / debug.

**Comment by travi** [comment]
digging into the specific issue that @jcjones1515 mentioned, I ensured that
* we have `publishConfig.registry` defined in the `package.json` to simplify [registry resolution](https://github.com/semantic-release/semantic-release/blob/3295f9570c71b57dbe867e72224ae7e5654de4eb/src/lib/get-registry.js#L2)
* the `publishConfig.registry` has a trailing `/` so that the request to get info would be [built correctly](https://github.com/semantic-release/last-release-npm/blob/2994e81304d945d9af6b7bc59dc8e8932213f2f8/src/index.js#L12)
* making a request to the url [built by the default last-release plugin](https://github.com/semantic-release/last-release-npm/blob/2994e81304d945d9af6b7bc59dc8e8932213f2f8/src/index.js#L12) successfully provides the expected info about the package

with `loglevel=debug` set in the `.npmrc` i was able to get a bit more log information. it doesn't provide an obvious answer yet, but it does narrow where the failure happens to somewhere in [this range](https://github.com/semantic-release/semantic-release/blob/462c51dc2abf291d568dc14306af1586e06f0d36/bin/semantic-release.js#L89-L123)
```
semantic-release verb init options: { argv: { remain: [ 'pre' ], cooked: [ 'pre' ], original: [ 'pre' ] },
semantic-release verb init   branch: 'master',
semantic-release verb init   fallbackTags: { next: 'latest' },
semantic-release verb init   debug: false,
semantic-release verb init   githubToken: '***',
semantic-release verb init   githubUrl: undefined }
semantic-release verb init Verifying config.
semantic-release verb pre Running pre-script.
semantic-release verb pre Veriying conditions.
semantic-release ERR! pre undefined
```

**Comment by travi** [comment]
after forking `semantic-release` and adding [a fallback](https://github.com/travi/semantic-release/blob/verify-conditions/bin/semantic-release.js#L92) to log `err` if `err.message` was undefined, i'm now seeing:
```
semantic-release ERR! pre { file: 'not found' }
```

 i was hoping for something more revealing, but that still isn't obvious to me.

**Comment by PatrickHeneise** [comment]
I have the issue in 5 repos now. It's caused by manual tagging, but there has to be a way to get this back up and running.

@boennemann any insight on where to start with debugging?

**Comment by PatrickHeneise** [comment]
@travi did you continue on this issue?

**Comment by PatrickHeneise** [comment]
@travi can you check if the tokens are all still valid? After some digging, I traced the `PRE undefined` error back to `travis-deploy-once/index.js` and resolved it with new keys. But I had a problem with my local branch and after a git reset to the GitHub origin, I'm back to [the original issue](https://github.com/semantic-release/semantic-release/issues/276) of a broken history.

As far as I remember, this `PRE: undefined` comes after the broken history issue, so I think it can be resolved with git. Here's a snippet I used to get `semantic-release` to run locally with a little bit of debug info (clone the repo to `../semantic-release`):

```
DEBUG=* \
TRAVIS_REPO_SLUG=[me/myrepo]
TRAVIS_BUILD_ID=[valid travis build id] \
TRAVIS_TEST_RESULT=0 \
TRAVIS_JOB_NUMBER=1.1 \
NPM_TOKEN=[fresg npm token] \
GH_TOKEN=[fresh github token] \
TRAVIS_BRANCH=master \
TRAVIS=true \
node ../semantic-release/bin/semantic-release pre --no-debug
```

**Comment by travi** [comment]
sorry, i haven't had a chance to trace this any further. i know i had tried updating the $GH_TOKEN and $NPM_TOKEN during my tests, but it's always possible that i pasted an incorrect value. 

from [my investigation](https://github.com/semantic-release/travis-deploy-once/issues/3#issuecomment-266311851) though, it seemed like the issue was from [node-travis-ci](https://github.com/pwmckenna/node-travis-ci/blob/master/lib/travis-ci.js) rather than directly from `travis-deploy-once`. This suggested to me that the problem was in communicating with travis pro, so it seems unlikely that $NPM_TOKEN or $GH_TOKEN would have an impact. by "new keys" did you mean one of these, or something else?

thank you for providing the details of running it locally. that was one of my next steps when i had been looking at this, but tracking down the right way to get it going was a big enough hurdle that i didnt get that far. this should be very helpful.

**Comment by travi** [comment]
thank you for the nudge to dig into this again. i did end up solving our problem. it was related to our `$GH_TOKEN`, but i did not end up needing to replace it with a different one.

we use a bot account for our semantic-release process. since no-one uses this account directly, it had never been used to log into the travis-pro webapp, so OAuth access had never been granted for travis-pro. even without this, [authenticating against the travis-pro api](https://github.com/semantic-release/travis-deploy-once/blob/master/src.js#L31) does not fail. Instead, it still attempts to get data about the build jobs, resulting in the `{file: 'not found'}` errors because of the lack of permissions.

i have not yet seen the broken history issues you mentioned, but our issue was definitely a permissions issue in the end. i just wish the errors would have been reported in a way that would have simplified resolution a bit more.

**Comment by PatrickHeneise** [comment]
Wow, that might indeed be a problem for some of our repos as well (same case with the bot), I'll look into it, thanks!

So far, I still don't know how to resolve the git issue without reverting back to the commit.

**Comment by pvdlg** [comment]
I think a workarround in the form of a more explicit error message has been added [here](https://github.com/semantic-release/travis-deploy-once/blob/master/lib/get-jobs.js#L18)

I'm not sure if we can do anything more on `semantic-release` unfortunately.

Is this error message solve this issue in a reasonable way?

**Comment by travi** [comment]
i think that error message would have been enough when i ran into this issue. it really came down to having no reason to think that was the issue and burning a ton of time investigating other things that seemed more likely. seeing that message would have cut down the time significantly for me.

**Comment by pvdlg** [comment]
Ok, I'm gonna go ahead and close this issue.

Feel free to re-open if you can think of a better way for `semantic-release` to handle this situation.

**Comment by felixfbecker** [comment]
Just had the same error again, in a project that doesn't publish to npm:

```
$ npm run semantic-release
> php-intellisense@0.0.0-development semantic-release /home/travis/build/felixfbecker/vscode-php-intellisense
> semantic-release pre && vsce publish -p $VSCE_TOKEN && semantic-release post
semantic-release WARN invalid config loglevel="notice"
semantic-release ERR! pre undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! php-intellisense@0.0.0-development semantic-release: `semantic-release pre && vsce publish -p $VSCE_TOKEN && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the php-intellisense@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-10-29T20_50_25_073Z-debug.log
```

I see this issue was closed, but were there any improvements done to error handling?
