### ISSUE TITLE
Maintenance: remove `codecov`

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#3425]
We have been noticed by @tidelift that `codecov` is no longer maintained. We don't really use it as far as I can tell and can simply remove it from our dependencies

We got this CSV that lists all the projects that currently have `codecov` listed as dev dependency:

[codecov-usage.csv](https://github.com/user-attachments/files/16607903/tidelift%40martynus.net.csv)

The projects are

- [x] `@semantic-release/changelog`
- [x] `@semantic-release/error`
- [x] `@semantic-release/npm`
- [x] `issue-parser`
- [x] `semantic-release`

**Comment by jedwards1211** [comment]
Yeah codecov stopped supporting that package and provides other utils for uploading coverage now

**Comment by travi** [comment]
we'd had some stability problems with codecov even before they made their changes, so we'd decided to stop shipping our coverage details there a while ago. it looks like these never got cleaned up with that decision. 

just removing the dependency from each project is probably the right step to get this cleaned up for now. with the changes that codecov has made since then, i've not experienced any stability problems in my own projects, so i wouldnt be opposed to re-adding at some point. i'd consider that a separate effort from this, though

**Comment by jedwards1211** [comment]
Yeah, I just added it back to a lot of my projects.  I can't directly translate what I learned to help here because I'm using their CircleCI orb, but it wasn't very complicated

**Comment by travi** [comment]
adding it back for a github workflow is pretty easy as well, since it is just a matter of [using their provided action](https://github.com/form8ion/project/blob/78d71e1c9be4a5799f40adc659be5aa3a83d5f7c/.github/workflows/node-ci.yml#L30)

**Comment by babblebey** [comment]
> just removing the dependency from each project is probably the right step to get this cleaned up for now.

How do you classify such change?? MAJOR/MINOR/PATCH??

**Comment by travi** [comment]
> How do you classify such change?? MAJOR/MINOR/PATCH??

this would be a change that has no impact on our consumers, so none of the above in this case. i personally would use either a `test` or `ci` commit type for a change like this, neither of which would be considered by semantic-release as a type that would trigger a release of any kind
