### ISSUE TITLE
Allow release branches to have names like `N.N`  (`N` is a number)

### ISSUE THREAD

**Issue by abichinger** [semantic-release/semantic-release#3478]
### New feature motivation

I'm currently trying to use `semantic-release` for an Odoo module. To publish a module on the Odoo Apps store you have to ensure that:

> The branch name exactly matches the series name for which your modules are meant, so `17.0` for  Odoo version 17.0.

When I try to release from branch `17.0` I get the following error:

```log
[9:08:25 PM] [semantic-release] › ✘  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
```

Because branch `17.0` is treated as a maintenance branch.

My current configuration:
```js
/**
 * @type {import('semantic-release').GlobalConfig}
 */
export default {
  branches: [{ name: "17.0", range: false }],
  tagFormat: "v17.0.${version}",
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/git",
      {
        assets: ["CHANGELOG.md", "__manifest__.py", "**/static/**"],
      },
    ],
    [
      "@semantic-release/exec",
      {
        prepareCmd:
          "python ./scripts/version.py ${branch.name}.${nextRelease.version}",
      },
    ],
  ],
};
```

### New feature description

Allow the user to define release branches with names like `N.N` by explicitly setting `BranchObject.range` to `false`

**Comment by abichinger** [comment]
Looking at the test case [`A "maintenance" branch is identified by having a "range" property or a "name" formatted like "N.x", "N.x.x" or "N.N.x"`](https://github.com/semantic-release/semantic-release/blob/c87596ee1603840d50822e002cea837209b3a243/test/definitions/branches.test.js#L4) this seems to be a bug, not a feature request.

**Comment by travi** [comment]
The current implementation is not a bug. As you can see from that test description, it is intended to describe a range, not a specific version. The purpose of our support for maintenance branches is to enable releasing additional changes that are before the latest, such as v2.x after v3.0.0 has been released. 

use of our maintenance workflow does not support the workflow you describe and will not be modified to add support. to support what you describe would require us to add support for a new workflow. Since our goal is to promote a continuous deployment style workflow, we would be very hesitant to add a workflow that targets every release to be a branch rather than from the default branch. 

You are welcome to attempt to convince us that this would be valuable, but it is likely that the workflow required by that ecosystem will remain incompatible with semantic-release

**Comment by abichinger** [comment]
> The current implementation is not a bug. As you can see from that test description, it is intended to describe a range, not a specific version.

I'm pretty sure it is a bug, because according to the test description a branch like `N.x`, `N.x.x` and `N.N.x` is a maintenance branch. Therefore, a branch like `N.N` should not be a maintenance branch. Right now the test case does not consider names like `N.N`.

This is the current behaviour:
```js
// semantic-release@24.1.2
maintenance.filter({ name: "1.0.0" })  // returns: false,   expected: false
maintenance.filter({ name: "1.0" })    // returns: true,    expected: false

```

> to support what you describe would require us to add support for a new workflow.

I don't require a new workflow. All I want is, that branches like `N.N` are release branches instead of maintenance branches.

**Comment by travi** [comment]
regardless of the behavior of the maintenance workflow implementation, i dont think you want to make those release branches either. releases need to be in a branch that is in the history of the next release. the closest you could get to what you describe is to release from the default branch and _then_ create a branch at the tag for the created release. because of that, you wouldnt need your branches to be any sort of release branch because your release branch would need to be a linear branch.

also, i dont understand your target versioning scheme. semantic-release is very specifically targeted at making it easy to release in a way that follows correct _semver_, which doesnt appear to be what you are after. semantic-release is not a generic release workflow tool, but an opinionated one. what it is about semantic-release that you are wanting to use for your release process? it seems like you are trying to work around the core parts of what makes it what it is

**Comment by abichinger** [comment]
> what it is about semantic-release that you are wanting to use for your release process?

I want to use semantic-release to
1. update the version of my [Odoo module] following [semantic versioning](https://semver.org/) rules
2. generate and commit a CHANGELOG.md file
3. commit the latest build artifacts of my module

I feel like I have not made it clear enough what I would like to achieve.
I want to automate the release of my [Odoo module]. The module is meant for [Odoo version 17.0](https://github.com/odoo/odoo/tree/17.0), so I have to publish the module on branch `17.0` in order for the [Odoo App Store](https://apps.odoo.com/apps/upload) to pick it up.

![image](https://github.com/user-attachments/assets/be466f9a-ffd9-43c3-b1c0-ba186f9d1bf8)
<p align="center"><i>Screenshot from https://apps.odoo.com/apps/upload</i></p>

Just to clarify, the Odoo version and the version of the module are independent from each other.
For example, If I'm targeting Odoo version 17.0 and semantic-release is in the process of publishing version 1.0.0, then semantic-release should create the verison tag `v17.0.1.0.0`.

But regardless of how I want to use semantic-release, can we agree that a branch like `N.N` should be identified as a release branch? (Please have a look at https://github.com/semantic-release/semantic-release/pull/3479)

[Odoo module]: https://www.odoo.com/documentation/18.0/developer/reference/backend/module.html#reference-module-manifest

**Comment by travi** [comment]
> feel like I have not made it clear enough what I would like to achieve.

thank you for the additional explanation about your use case. i was clearly not grasping the goal initially. apologies for making the assumptions that i did that didnt align with what you are after. we have many users that want to use our provided workflows for unintended use-cases, so not grasping your full goal, this sounded like a similar situation.

i think you are correct that the two-segment version matching as a maintenance branch is not what was intended. in my earlier read, i thought you were wanting to make it into a maintenance branch which we wouldnt want, but identifying that it was already matching as a maintenance branch and shouldnt is appreciated. i'll take a closer look at your PR and i think we can get that fixed
