### ISSUE TITLE
Way to just print the (new) version

### ISSUE THREAD

**Issue by leifg** [semantic-release/semantic-release#407]
I've playing around with options for a little bit now and I'd like to have a way to just print the version that will be generated (even if it didn't change). But I need so many options and especially the `NPM_TOKEN` variable just doesn't make any sense at this point.

Regardless of how many options I provide I'm not able to print the version.

My latest try:

```shell
CIRCLE_BRANCH=master CIRCLECI=true NPM_TOKEN=fake CI=TRUE GH_TOKEN=<redacted> GH_REPOSITORY_URL=repo yarn semantic-release pre

semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
error Command failed with exit code 1.
```

**Comment by vanduynslagerp** [comment]
You can run `semantic-release pre --debug`. That would print the new version determined by `semantic-release` based on the commit since the last release on NPM.

You need to set `NPM_TOKEN` as `semantic-release` needs to check on NPM registry what is the last version released (and what's the commit associated with this release).

Other environment variable are not necessary. `semantic-release` will display a warning if you don't have `CIRCLECI` and `CIRCLE_BRANCH` but it will still analyze your commit since last release and display the new version.

The message `ENOCHANGE There are no relevant changes, so no new version is released.` indicate that no commits you have made on your repository since last NPM release require to release a new version.
Maybe your commit messages are not properly formatted or none of them are of type `fix` or `feat`.
