### ISSUE TITLE
semantic-release created a tag-named branch

### ISSUE THREAD

**Issue by luftywiranda13** [semantic-release/semantic-release#415]
Hello guys, it's great to finally see some progresses/updates from `semantic-release` 🎉 

btw, I committed a `fix` type commit and pushed it to my repo https://github.com/luftywiranda13/generator-node-oss

as expected, `semantic-release` v7.0.1 detected the commit then published a patch version.
**but** it left a branch named `v1.0.3`

It doesn't matter to me how `semantic-release` works behind the scene as long as it does the `automatic releasing` but if it creates a branch then it should also delete the branch after releasing

**Comment by luftywiranda13** [comment]
@gr2m @boennemann

**Comment by gr2m** [comment]
no need to mention us, we’ll get back to you as soon as we can :) 

creating a branch is part of the main feature of semantic-release. Based on the branch we can create a GitHub release and then put the change logs in there, example: https://github.com/semantic-release/semantic-release/releases/tag/v7.0.1

The branches is also not something that was added with version 7, it was there since day one, so I don't quite understand your issue to be honest :)

**Comment by luftywiranda13** [comment]
I'm sorry but I see so many long open issues here 😉 

yes but why didn't semantic-release delete the branch after releasing? Do I have to manually delete the branch?

So if I think someday I'll have 50+ branches created by semantic-release in my repo 😢

**Comment by gr2m** [comment]
ah sorry it's late for me, I was thinking we were talking about tags, not branches. Okay something is off here.

If you could investigate what’s happening and send a pull request, that’d be great, because I don’t think neither Stephan nor I will get to this, we are working on other parts right now.

Thanks for your help!

**Comment by luftywiranda13** [comment]
oh okay, I'll try to

thanks Gregor!

**Comment by gr2m** [comment]
I’m pretty sure this is the change that cause it: https://github.com/semantic-release/semantic-release/pull/335

**Comment by luftywiranda13** [comment]
yeah it looks suspicious, i'm still digging a bit
