### ISSUE TITLE
Invalid config warning

### ISSUE THREAD

**Issue by RichardLitt** [semantic-release/semantic-release#430]
I repeatedly get this warning: 

```
> semantic-release WARN invalid config loglevel="notice"
```

Where can I find more information on it?

**Comment by gr2m** [comment]
npm@5 introduced `notice` as a new loglevel and it defaults to it. `semantic-release` uses the same library that `npm` uses for logging: https://www.npmjs.com/package/npmlog. So that’s where this is coming from.

But where exactly semantic-release validates the current level and logs the warning, I dunno :) Would be nice if you could investigate 🙌
