### ISSUE TITLE
Yarn fails to install semantic-release on node version < 8

### ISSUE THREAD

**Issue by calebeby** [semantic-release/semantic-release#433]
Given that you only support node 8+, how do you suggest configuring `package.json` and `.travis.yml` such that there aren't dependency errors on node versions less than 8?

**Comment by vanduynslagerp** [comment]
`semantic-release` will exit right away if ran on node < 8. See [semantic-release.js#L8](https://github.com/semantic-release/semantic-release/blob/12b35396d88d37de8000d7838b41de9f2b276f80/bin/semantic-release.js#L8).

So if you configure Travis to run multiple jobs on different node versions (ie. you want to test on node4, 6 and 8), `semantic-release` will run only for the job running node 8.

So the only constraint when you have multiple node version in your `travis.yml` is that at least one is 8.

so in your `package.json`:
```json
"scripts": {
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
}
```
and in `travis.yml`
```yaml
language: node_js
node_js:
  - 8
  - 6
  - 4
after_success:
  - npm run semantic-release
```

Only the node 8 job will run `semantic-release`. It will also wait for the node 4 and 6 jobs to complete and will do the release only if all 3 jobs are successful.

**Comment by calebeby** [comment]
Right, the issue that I have is that it is listed in devDependencies and it stops the whole travis install on node <8

**Comment by vanduynslagerp** [comment]
`semantic-release` require node >8 for execution. You can still list it in `devDependencies` and run `npm install` on node <8 without any problem?
Do you have a link to your build that fail on Travis ? Maybe I can look at the logs and help you.

**Comment by calebeby** [comment]
https://travis-ci.org/calebeby/transform-pkg/builds/276373481?utm_source=github_status&utm_medium=notification

**Comment by calebeby** [comment]
I didn't have the node 8 test running in that case, but it would've probably passed.

**Comment by vanduynslagerp** [comment]
This is due to a specificity of `yarn` that check the `engines` field of dependencies while `npm` doesn't.

According to the `package.json` specification on `npm` doc, the `engines` property in `package.json` is only advisory and create a warning only for `dependencies` not `devDependencies`. See [package.json#engines](https://docs.npmjs.com/files/package.json#engines).

It seems that `yarn` works differently and fails the install. I'm not really sure which of the `yarn` or the `npm` behavior is the right one here...

You have two options here.
1/ Use `npm` in your CI build by removing `yarn.lock` or by specifying in `travis.yml`:
```yaml
install:
  - npm install
```
2/ Pass the option [--ignore-engines](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) to `yarn`:
```yaml
install:
  - yarn install --ignore-engines
```

We should add this in the `semantic-release` documentation.

**Comment by calebeby** [comment]
OK, thanks for that feedback. I think I will choose the 2nd option for now. What if semantic-release didn't require node 8 in package.json (i.e. it would install but not run)?

**Comment by vanduynslagerp** [comment]
> What if semantic-release didn't require node 8 in package.json (i.e. it would install but not run)?

The intention in `semantic-release` `package.json` is not to require Node 8, but to inform that it's made to run on Node 8. This is what the `engines` property does according to `npm` docs. But not according to `yarn` apparently.

As a potential fix we could:
- Support Node > 4 and provide transpiled files (but that would be going backward)
- Recommended in the documentation to use `--ignore-engines` with `yarn`
- Remove the `engines` filed in `package.json` (as technically `semantic-release` can run on any version of node, it will just exit right away if node < 8).

**Comment by calebeby** [comment]
OK, makes sense.

**Comment by vanduynslagerp** [comment]
Thinking about that I think we should set `engines` to `>= 4` in `package.json` as `semantic-release` can and will run on Node 4 (it will just skip everything and do nothing other than a log message but still runs).

What do you think @gr2m ?

**Comment by gr2m** [comment]
Sounds like a pragmatic solution, let’s do it.

**Comment by hbetts** [comment]
Or encourage developers to switch to the new [Build Stages](https://docs.travis-ci.com/user/build-stages/) feature in Travis CI where you can install `semantic-release` in a Node 8 stage. (Travis CI is not the only CI and most allow you to have stages with their own version of Node)

Here's the stance on the `engines` property by the Yarn core team - https://github.com/yarnpkg/rfcs/pull/69#issuecomment-308567694

My stance is that engines should remain because technically `semantic-release` can not be executed successfully in any other environment other than Node 8.

**Comment by vanduynslagerp** [comment]
The Build stage feature in Travis is awesome and we'll write more documentation regarding how to use it.
And yes we could recommend to not include `semantic-release` in the devDependencies and run `npm install -g semantic-release && semantic-release pre && npm publish && semantic-release post`. But not quite now. Because `semantic-release`, when installed globally, won't be able to load custom plugins as they are loaded relatively to `process.cwd()` .

As explained [here](https://github.com/semantic-release/semantic-release/pull/442#issuecomment-331215278) `semantic-release` can be executed on node < 8. It report an error instead of an informational log due to current limitation is the way handle the different release steps (pre, publish, post).
