### ISSUE TITLE
New plugin: Visual Studio Team Services

### ISSUE THREAD

**Issue by marceloavf** [semantic-release/semantic-release#440]
Is there a way to use this semantic-release with VSTS? How can I start configuring things up?

**Comment by pvdlg** [comment]
Supporting a new CI provider is usually done via a `verifyCondition` plugin similar to [condition-travis](https://github.com/semantic-release/condition-travis).

In order to be able to support a CI provider the plugin need to verify:
- That `semantic-release` is running on CI (via environment variable for example)
- If the current run is a PR
- The git branch on which the build is currently running
- The current job run last in the build (if you build on different OS or Node version for example) and all the other jobs are successful

The last one is the most tricky, and it's very important as we want to make a new release only if all the test are successful, on each OS it's tested on and each version of Node.

Ideally the CI provider should also offer a Github integration that update the PR and commit status as `semantic-release` might rely on that in the future to detect if all build passed.

I'm not familiar with Visual Studio Team Services and I'm not sure if it's widly use, so it probably won't be a priority for us to support it.
That said you are more than welcome to create a plugin :)

**Comment by pvdlg** [comment]
A plugin for Visual Studio Team Services shouldn't be required anymore as Semantic-release works on any CI since #578.

Feel free to re-open if there is something to support Visual Studio Team Services
