### ISSUE TITLE
use without npm

### ISSUE THREAD

**Issue by nxmohamad** [semantic-release/semantic-release#465]
I'm a bit confused about how/if I can use this without publishing to NPM. I'm using this for a private project. The first release seemed to work fine 1.0.0, but then 4 commits later, there were still no releases made even after successful CI builds.

Is this because I have nothing published on NPM? Does it refer to the version number in NPM to generate the latest version number? If so, how can I get around this?

UPDATE: I've modified my setup to use a getLastRelease plugin that gets it from git tags instead. I still get the same thing, after the first publication of a release, it shows 'x commits have been made on master since this release' but no new releases are made. the versions are all just on 1.0.0 or 2.0.0.
after using the plugin the version number was bumped to 2.0.0.

**Comment by pvdlg** [comment]
Currently `semantic-release` doesn't support a scenario without npm by default. This is something we want to support in the future.

If you provide the link of a CI job where you experience the problem I can look at it and try to help.

**Comment by nxmohamad** [comment]
So the subsequent release is dependent on it being published on NPM? Is it right that semantic release would push a release on github on every commit? Or how does it calculate when to release?

**Comment by felixfbecker** [comment]
I'd like to use semantic-release with PHP projects that use Composer. Composer doesn't publish tarballs of new versions, it just uses git tags in the repository. So I only need the functionality of semantic-release to tag new releases, i.e. instead of
```sh
semantic-release pre && npm publish && semantic-release post
```
just do
```sh
semantic-release pre && semantic-release post
```
without an NPM_TOKEN, just a GH_TOKEN.

**Comment by felixfbecker** [comment]
Seems like this should work: https://www.npmjs.com/package/last-release-git

**Comment by gr2m** [comment]
We are also discussing a GitHub app which you can install on any repository and it will do language agnostic releases to GitHub only, stay tuned :)

**Comment by felixfbecker** [comment]
That sounds great, as long as it's still flexible enough to configure with custom scripts etc.

Got it to work btw: https://github.com/felixfbecker/php-semantic-release-test/releases/tag/v2.1.0

**Comment by destroyerofbuilds** [comment]
> We are also discussing a GitHub app which you can install on any repository and it will do language agnostic releases to GitHub only, stay tuned :)

That's exciting to hear! Looking forward to giving that app a try.

**Comment by destroyerofbuilds** [comment]
Actually, to move this discussion forward, could `npm` support be removed from `semantic-release`, and we just encourage developers to run `npm publish` as part of a build job that only runs on new tags`?

**Comment by felixfbecker** [comment]
I don't think it should be removed from the default configuration, because it's the biggest use case and the plugin architecture makes it easy enough to run on tags (but it requires to workaround some Travis annoyances).

But what I'd like to see is the requirement for `NPM_TOKEN` to be dropped and  have the CLI ask a question whether you want to use NPM integration or not. Atm the CLI adds an NPM token to Travis even when I want to set it up for a PHP project. The token is not used in the end because I use the git tag plugin, but if it is not set, semantic-release will bail early with an error. I have to set it to a fake token like `0000-0000-0000-0000` to make it work.

**Comment by destroyerofbuilds** [comment]
> CLI ask a question whether you want to use NPM integration or not

How would that work from within an automated CI job?

**Comment by felixfbecker** [comment]
I mean the `semantic-release-cli setup` command

**Comment by pvdlg** [comment]
I open this issue #484 to propose a solution that would allow to use `semantic-release` without npm and with repositories other than Github.
Would love to have your feedback on this proposal.

**Comment by felixfbecker** [comment]
Met another problem:
`travis-deploy-once` seems to check the Node version. If none of the jobs are using the `node_js` language, then there will be no build leader detected, even if node 8 is installed with `nvm`.

https://travis-ci.org/felixfbecker/php-language-server/jobs/291359846#L912-L915

**Comment by pvdlg** [comment]
@felixfbecker Good catch! Would you mind opening a bug in the `travis-deploy-once` repo?

**Comment by felixfbecker** [comment]
https://github.com/semantic-release/travis-deploy-once/issues/22
