### ISSUE TITLE
Strange case of bumping to major

### ISSUE THREAD

**Issue by charlike** [semantic-release/semantic-release#468]
just scratched it here: https://github.com/charlike/ideas/issues/97, cuz want to have it as reminder.

***

https://travis-ci.org/tunnckoCore/hela-config-tunnckocore/jobs/285838102

Initially that repo was named `hela-preset-tunnckocore` with ~30 commits. Needed the name to be changed, so i changed the name to `hela-config-tunnckocore`. After the first commit on new repo, it "found" 32 commits in bulk, so for some only-god-know reason it decided to bump to major. No one of the commits have "BREAKING CHANGE" anywhere, as you can see - just `fix` and `feat` types.

I, in any way, was going to publish v1 soon, but that surprise isn't good. Probably not documented that after some number of `fix`es and `feat`s it auto-magically decides to bump major? More strange thing is that in the GitHub release is listed only the last commit - https://github.com/tunnckoCore/hela-config-tunnckocore/releases/tag/v1.0.0

**Comment by pvdlg** [comment]
I think what happen is that after the name change,`semantic-release` ran and didn't found the new package on npm, then it concluded there is no releases yet. And in that case the version to release is `1.0.0`. That's the expected behavior.

If you change your package name you'd have to manually release the last version with the new name as `semantic-release` has no way to know there was a previous release with a different name.

**Comment by charlike** [comment]
Hm. Actually, good point. Okey, clarified, now not sounds so strange.

Thanks! :)
