### ISSUE TITLE
Migration to v9

### ISSUE THREAD

**Issue by sudo-suhas** [semantic-release/semantic-release#492]
This is how I was using `semantic-release` in travis:
```yml
# ...
after_success:
  - yarn global add semantic-release gh-pages
  - 'semantic-release pre &&
    npm run -s build &&
    gh-pages --add
      --dist .
      --src "{browser/*,docs/*}"
      --repo "https://$GH_TOKEN@github.com/sudo-suhas/elastic-builder.git"
      --message "docs: Build docs for `npm run -s print-version`" &&
    npm publish &&
    semantic-release post'
```

You can see this in action here - https://travis-ci.org/booleanapp/elastic-muto/jobs/285474235#L541.
I need to be able to generate docs after the version has been incremented. 

How would I migrate this to v9? Would `prepublishOnly` script work?

**Comment by gr2m** [comment]
I think all migration notes are in the [v9.0.0 release notes](https://github.com/semantic-release/semantic-release/releases/tag/v9.0.0).

Can you run the `gh-pages` task after the publish? There will be more breaking changes in future, you'll be on the safe side if you add semantic-release to your devDependencies and enable greenkeeper to get notified about a new verson

**Comment by pvdlg** [comment]
@sudo-suhas I'd suggest a `postpublish` script in which you would add anything to be done after a publish to npm.
This script would:
- be run only if a release is done
- After the `package.json` is updated

**Comment by buehler** [comment]
I just read the v9 release notes, and I'm asking myself the following: since the new version does everything in one command, is it possible to do the "old" path?

I'm asking because of a project of mine that actually relies on that part of semantic release:
https://github.com/buehler/typescript-hero/blob/develop/package.json#L91

I actually use semantic release pre to set the correct version, than generate changelog entries, and afterwards, do the actual release via `vsce publish` instead of npm publish.

Is this still possible?

Cheers

**Comment by pvdlg** [comment]
You can run those scripts by putting them in the `prePublishOnly` or `postpublish`.
The would be run by `npm` before or after the publishing.

At that point there is no way to not use npm though. That will be handled soon in #484

**Comment by sudo-suhas** [comment]
Alright, thanks @gr2m, @pvdlg. I think that answers my question. I think `prepublishOnly` hook is good for running the build and `postpublish` can be used for generating docs.
