### ISSUE TITLE
Artifactory npm auth fails

### ISSUE THREAD

**Issue by gergelyke** [semantic-release/semantic-release#500]
Hi,

first of all, thanks for working on this amazing project!

I've tried setting it up at with Artifactory, however when I pass in the url, username and password, I get the following error message:

```
http semantic-release request PUT ARTIFACTORY_URL/-/user/org.couchdb.user:USER_NAME
http semantic-release 403 'ARTIFACTORY_URL/-/user/org.couchdb.user:USER_NAME'
ERR! semantic-release Error: forbidden No oauth npm default login configuration found: org.couchdb.user:USER_NAME
```

any idea what am I doing wrong?

node version: 8.8.1
artifactory version: 4.16.0

**Comment by gr2m** [comment]
thanks for the kind words 😬 glad you like the project!

I'm afraid I have no idea about Artifactory. Did you replace the actual URL with `ARTIFACTORY_URL` in your logs above? 

e.g. 

> http semantic-release request PUT ARTIFACTORY_URL/-/user/org.couchdb.user:USER_NAME

looks as if `ARTIFACTORY_URL` should actually be a host name with username & password for auth.

If Artifactory is a drop-in replacement for npm it might lack APIs that semantic-release depends on

**Comment by destroyerofbuilds** [comment]
Artifactory does not have all the same user management features as the npm registry (I work with Artifactory and Yarn on a regular basis).

> might lack APIs that semantic-release depends on

I've been trying to find what those APIs may be. Does `semantic-release` interact with npm's User endpoint? (I've been trying to search the code for that without success)

Basic package metadata fetching is fully supported by Artifactory.

@gergelyke what is the contents of your `.npmrc` file (with sensitive information redacted).

**Comment by gr2m** [comment]
The best place to look what npm endopints semantic-relaese is using is Pierre’s work-in-progress `@semantic-release/npm` module: https://github.com/semantic-release/npm/pull/1. It is part of his great efforts to modularise semantic-release to make it work in other environments, so it’s a perfect fit to make it work with artifactory. Here is a preview of the README: https://github.com/semantic-release/npm/blob/initial-release/README.md

**Comment by pvdlg** [comment]
@gergelyke according to [Artifactory documentation](https://www.jfrog.com/confluence/display/RTF/Npm+Registry#NpmRegistry-AuthenticatingthenpmClient) the authentication with a token was introduced in version `5.4`.

As you are using version `4.16.0` you have to use the legacy authentication. It's supported by `semantic-release` but undocumented as it's deprecated.

With the current version of `semantic-release` you have to define the environment variables:
- `NPM_OLD_TOKEN` with your Artifactory username and password (formatted `username:password`) encoded in [Base 64](https://www.base64encode.org/)
- `NPM_EMAIL` with the email address associated with your Artifactory user

Once #515 is merged and released you will have to defined the environment variables:
- `NPM_USERNAME` with your Artifactory username
- `NPM_PASSWORD` with your Artifactory user password
- `NPM_EMAIL` with the email address associated with your Artifactory user

If you can, you should upgrade to a more recent version of Artifactory and just use the `NPM_TOKEN` generated with `npm login` as it's a lot more secured.
In order to do that run `npm login` and open the file `~/.npmrc`. You should see something like that in the file: `//<registry_url>/:_authToken=<token>`.
Set the `NPM_TOKEN` on your CI with the value of `<token>` from `~/.npmrc`.

Let us know if that solve your issue.
