### ISSUE TITLE
New plugin: Shippable-CI

### ISSUE THREAD

**Issue by ryan-kimber** [semantic-release/semantic-release#508]
I've been using semantic-release on the same set of projects for a couple of years.

We've recently encountered an issue where Shippable's environment variables (it sets some TRAVIS_* vars) trigger semantic-release's verification rules for Travis CI. 

It would be great if there was a verify plugin for Shippable, or if the default implementation didn't implement rules for Travis.

**Comment by ryan-kimber** [comment]
In trying to make it work, we tried following some of the instructions the pre command provided (such as setting a tag for 0.0.0-semantic-release to the previous version), but no additional luck. Our GitHub repo showing these as releases though, and there's a corresponding version in NPM for each. I should note, 1.5.0 was previously released, but after this error started, I deleted and re-created the release, hoping it would see it, but to no avail.

![screen shot 2017-11-09 at 10 36 29 pm](https://user-images.githubusercontent.com/1018189/32641917-b04d9146-c59e-11e7-813a-5702366a41b6.png)

**Comment by gr2m** [comment]
Hey @ryan-kimber, we are working towards further modularization of semantic-release. @pvdlg is doing great work on it. The best issue to subscribe to is https://github.com/semantic-release/semantic-release/issues/411, we will keep folks updated there as soon as we have something ready to try. If you could have a look at the open pull requests mentioned in https://github.com/semantic-release/semantic-release/issues/484, that’d be 💯 It’s the perfect time to get involved :) we hope to empower users like yourself to make semantic-release work with their environment and reduce hard coded dependencies as much as possible

**Comment by pvdlg** [comment]
A plugin for Shippable-CI shouldn't be required anymore as Semantic-release works on any CI since #578.

If the CI runs multiple jobs (to test multiple node version or different OSs) within a build it has to guarantee that `semantic-release` is executed only after all jobs are successful. Quickly going through the Shippable-CI doc it seems that running multiple jobs within a build is not supported anyway.

Feel free to re-open if there is something to support Shippable-CI
