### ISSUE TITLE
Support shareable config

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#549]
this has probably been discussed before, but i'm not finding any info about it if it has. semantic-release provides a considerable amount of customizability, but i've always been hesitant to get too deep because i didn't want to take on deviating from the default conventions consistently across all repos where my organization(s) use semantic-release. 

i think i'd be far more interested in tweaking semantic-release further if doing so could apply across all of the projects that i manage fairly automatically.

at minimum, this would enable a config to be published as an npm package, such as `semantic-release-config-travi` and used in each semantic-relase managed project using something along the lines of `extends: 'travi'`. ideally, a config could also extend another config, such as `semantic-release-config-greenkeeper-keeper` extending `semantic-release-config-travi`, allowing projects under the `greenkeeper-keeper` org to extend `semantic-release-config-greenkeeper-keeper` but have that mostly configured from my personal config.

has the concept of a shareable config, similar to what [eslint enables](https://eslint.org/docs/developer-guide/shareable-configs) been considered for semantic-release? would something like this be a huge undertaking to add?

**Comment by pvdlg** [comment]
Thanks for the proposal!

A shareable config might be a solution but the problem is that many (most?) parameters are repository/branch specifics:
- `branch` might have a different value on each permanent branches of your repo (in order to release on `latest` dist-tag from `master` and on `next` dist-tag from another branch)
- [assets](https://github.com/semantic-release/github#assets) will most likely be different on each repo
- `repositoryUrl` will by definition be different on each repo
- The list of plugins to use will in most case be the default one (no config at all) and when it's not it will in most case quite specific to a given repo

In addition some other configuration that `semantic-release` uses are independent from its configuration, such as `.npmrc` or the `publishConfig` in the `package.json`.

With a shareable config you would still have to configure most of the options manually on each repo.
That mean a shareable configuration would have to be extendable, which comes with a lot of problems: See the 2.5 year old, 110 comments [issue on the subject](https://github.com/eslint/eslint/issues/3458).

Maybe a better solution to share a config across repo would be https://github.com/sapegin/mrm. They event offer a [semantic-release task](https://github.com/sapegin/mrm-tasks/tree/master/packages/mrm-task-semantic-release).

For information, what parameters are looking to put in a shareable config?

I'm currently looking at a way to simplify the configuration, but I'm not sure what the right solution is yet... Ideally I'd like a way to configure the plugin params globally (instead of limiting the config within the plugin definition). Maybe that would alleviate the problem.

**Comment by pvdlg** [comment]
Here is a first proposal to implement such feature, so we can discuss what the best approach is.

This first step would be to allow plugin configuration to be set directly under the `release` property. Those config would be passed to each plugins. For example:
```json
"release": {
  "publish": ["@sematic-release/github", "@sematic-release/git"],
  "assets": ["dist/**/*.js"]
}
```
The `assets` option would be passed to both the `git` and `github` plugins. It would still be possible to define options inside each plugin, that would take precedence for this specific plugin over the one defined under `release`.

=> I'm finishing up a PR that I started a week ago that goes in that direction.

The second step would be to allow the new parameter `extends` that could be set either via config file or CLI. It would be a list of path (either file on the FS or npm modules) to extends from.

So `semantic-release` would determine its options by merging in that order of priority:
- options passed via CLI
- Options set in the `package.json` or dotfile config
- Options set in the scripts/modules defined in `extends`
- Default options

In order to keep things simple the shareable config would not be allowed to extends other shareable configs.

This way a shareable config could:
- Defined which plugin to use
- Defined a new set of default options

And the user could override any options specific to the current repo/branch.

Would that be an acceptable solution?

**Comment by travi** [comment]
thanks a lot for the quick response. i apologize for being so slow to follow up.

you've made some good points about how much of the config is specific to each project. admittedly, there are a number of config options that i have not explored very deeply due to concern around keeping things consistent after diverging from defaults. therefore, there are some of these implications that i have not explored enough to understand fully yet.

thank you for pointing out `mrm` i have searched for tools like that in the past, and it seems worth taking a close look at, even beyond `semantic-release` config.

the things that i had in mind that would be helpful in a shareable config are:
* [analyzeCommits](https://github.com/semantic-release/semantic-release#analyzecommits): i've stuck with the the default for simplicity, but there are times where we've wanted to tweek it a bit based on our team conventions. we use [`commitlint`](https://github.com/marionebl/commitlint) to ensure our commits align to what `semantic-release` is looking for. i'd want the shareable config to enable us to align any tweaks we've made to our `commitlint` config with `semantic-release` behavior. however, as you mention for other details, there might be a better place than a shareable config for this. if `semantic-release` could reference the [`commitlint` config](https://github.com/marionebl/commitlint#config) directly, maybe a shareable config wouldnt be needed for this detail
* prereleases: i have thoughts around a strategy for prereleases that would work for our team that i think would need to be coordinated across several plugins. since this would be a team strategy, we'd want to make sure each package is codified to follow the same strategy. i'd love to run my thoughts about this strategy by you all, but thats a separate conversation (would another issue be a good place for that type of conversation, or is there a better way?)

i do think there would be significant value in enabling shareable configs to extend other shareable configs, but i can certainly understand avoiding that complexity at first at least.

does this give some more context for what i was thinking?  what other information would be helpful?

**Comment by pvdlg** [comment]
Thanks for the feedback!

> analyzeCommits: i've stuck with the the default for simplicity, but there are times where we've wanted to tweek it a bit based on our team conventions. we use commitlint to ensure our commits align to what semantic-release is looking for. i'd want the shareable config to enable us to align any tweaks we've made to our commitlint config with semantic-release behavior. 

You can already do that with the `releaseRules` that accept a module or a path and `config` that accept a custom `conventional-changelog` preset module. `commitlint` is based on `conventional-changelog` preset I think. So it should work for your use case.

> prereleases: i have thoughts around a strategy for prereleases that would work for our team that i think would need to be coordinated across several plugins. since this would be a team strategy, we'd want to make sure each package is codified to follow the same strategy. i'd love to run my thoughts about this strategy by you all, but thats a separate conversation (would another issue be a good place for that type of conversation, or is there a better way?)

I have something in preparation for that, including multiple branches, multiple dist-tag and pre-releases, all that fully automated based git merge detection. It's a pretty complex thing so I've been experimenting on that for several weeks :) I'll open a (very long) issue for a proposal soon. Feedback welcome once I got that published :)

> i do think there would be significant value in enabling shareable configs to extend other shareable configs, but i can certainly understand avoiding that complexity at first at least.

As mentioned through the Eslint issue it's quite complicated and potentially not even solvable properly, mostly due to plugin dependencies. Ideally, when you create a shareable config that use a custom plugin, you'd want to include this plugin as a dependency of your config package. The case with a chain of several configuration using different version of the same plugin is either impossible or extremely difficult to solve.
In addition that would create a lot of complexity regarding how to merge the different config (deep merge or not ?). Doing a deep merge is probably error prone as plugin could define option that are inter-dependent, and doing a deep merge would create more often than not inconsistencies and very difficult issue to debug.
Chainable extends make sense for something like Eslint that defines a lot of things in a config. Not sure sure that the complexity and maintenance load would justify the gain in the case of `semantic-release`.

> does this give some more context for what i was thinking? what other information would be helpful?

Yes, it helps a lot!

**Comment by micha149** [comment]
@pvdlg How to deal with the plugin order? I would like to create a sharable config for our company. But not all projects are javascript. So, I need to add `@semantic-release/npm` in the project specific config, but it need to be executed before `@semantic-release/git`.
