### ISSUE TITLE
Version mismatch for semantic-release

### ISSUE THREAD

**Issue by nareshbhatia** [semantic-release/semantic-release#577]
It appears that the latest version of semantic-release on github is 11.1.0 whereas on npm it is 11.0.2. When I do `npm outdated`, I get

    Package           Current   Wanted   Latest
    semantic-release   11.0.2   11.1.0   11.0.2

What am I missing?

**Comment by pvdlg** [comment]
This is because we publish new version on the `next` dist-tag, and once a version has been tested enough we make it available on the `latest` dist-tag.
See https://docs.npmjs.com/cli/dist-tag

The current version on `latest` is `11.0.2`. If you want to use the version from `next` you can specify in your `package.json` `"semantic-release" : "^11.1.0"`.

**Comment by nareshbhatia** [comment]
@pvdlg, thanks for clarifying. Makes perfect sense now!
