### ISSUE TITLE
If semantic release fails (due to npm publish error) should travis fail?

### ISSUE THREAD

**Issue by remy** [semantic-release/semantic-release#63]
As per subject.

**Comment by boennemann** [comment]
Using the default setup it doesn't mark the build as failed, because, the actual build passed.

If you desire a different behavior you could remove `- npm run semantic-release` from the `.travis.yml`'s `after_success` section and add 
```yml
script:
- npm test && npm run semantic-release
```

Be prepared for **a lot** of failed builds though, e.g. every PR or non-master build.
