### ISSUE TITLE
Always have "v1.0.0" when I use tag-format option

### ISSUE THREAD

**Issue by R0oma1n** [semantic-release/semantic-release#648]
Hello

When I use yarn release without the option " --tag-format '${version}', sementic-release increments my version, but with the tag-format option, I always have the same version : v1.0.0

I do not understand why he does not get the package.json version

**Comment by pvdlg** [comment]
I'm not really sure I understand the issue. Can you edit your issue to add the information in the [bug report template](https://github.com/semantic-release/semantic-release/issues/new?template=bug-report.md). Thanks

**Comment by R0oma1n** [comment]
The version remains at v1.0.0 and it never increases, for each commit, my version remains at v1.0.0.
I don't have a bug in my console when I use --debug.

**Comment by R0oma1n** [comment]
# Bug report

## Current behavior



When I use semantic-release option tagFormat, the version of my code stay at v1.0.0.

## Expected behavior



I want to have the normal operation, when I push a fix, I want to have v1.0.1 and not v1.0.0

## Environment

- **semantic-release** version: 

"devDependencies": {
    "@semantic-release/git": "^3.0.0",
    "@semantic-release/gitlab": "^1.0.2",
    "@semantic-release/npm": "^3.0.0",
    "semantic-release": "^13.1.3",
    "@semantic-release/changelog": "^1.0.0"
  }

- CI environment: 

I use Gitlab-ci


- CI logs: 

https://gitlab.com/naerion/release-test

**Comment by pvdlg** [comment]
In the logs you linked no release is created and the `tag-format` is not used. It doesn't seems to be even related.

As a side note you have several other misconfigurations:
- `"gitlabUrl": "https://gitlab.com/naerion/"` is not configured properly. The `naerion/` part should not be included. In addition this config is useless as you use the default one (`https://gitlab.com`)
- `"createGitTag": "@semantic-release/git"` is not an option that exists
- You use the `@semantic-release/npm` plugin but it's configured in `verifyConditions`

But I'm not even sure it's relevant as it might not be the configuration you are using since you report a problem regarding `tagFormat` but don't use it in the configuration you linked.

I'd like to invite you to read out [contributing guidelines](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md) especially the part about [bug reports](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#bug-report). **semantic-release** is an open source project and all the maintainers are volunteer with limited time. All the time we spend chasing for accurate information to troubleshoot is time that we don't spend improving the project. So please try to take the time to write proper and detailed bug reports.

**Comment by R0oma1n** [comment]
I use another configuration that is very close to this one but the solution is on a local gitlab directory.
The command I use is : 
yarn release --branch ${CI_COMMIT_REF_NAME} --tag-format "${CI_COMMIT_REF_NAME}-"'${version}' 
Instead of :
yarn release --debug in the project I gave you

Here are the steps : 
- I modify my code 
- I commit my code 
- I use my yarn command : yarn release --branch ${CI_COMMIT_REF_NAME} --tag-format "${CI_COMMIT_REF_NAME}-"'${version}' 
- Normally, for each change, I should have a version that changes, but there, the version remains there even after each commit and each command executed.

When I use yarn release without the Format tag, semantic-release uses the version in package.json, but there it does not get the version of the package.json file. In the documentation, it says to use $ {version} but this command does not work when I use the tag-format option. I always get the same version when I use --tag-format 

I hope I have made you understand my problem
I'm sorry but I have no more explanation to give.
Thank you for your time

**Comment by pvdlg** [comment]
Once again you don't provide the information requested in the [bug report template](https://github.com/semantic-release/semantic-release/issues/new?template=bug-report.md), namely:
- **semantic-release** version
- Plugins used
- **semantic-release** configuration
- CI logs

This is 4 simple information that can be copied and pasted in the issue report, even if you are using a private repo and a private CI.
I feel like there is some misunderstanding somewhere and maybe you think we are asking this for the sake of it. But it's not the case, I really need those info to analyze what happen in your env as I can't reproduce what you are describing.

We are trying to make the process of reporting issues and troubleshooting as seamless as possible, which is why we wrote a [contributing guideline](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md) and and [bug report template](https://github.com/semantic-release/semantic-release/issues/new?template=bug-report.md).

We are at the 8th message on this issue and you didn't provided your configuration nor the semantic-release logs, so I imagine there is something that is not clear or confusing. How can we improve our docs/guideline/template in a way that would have prompted you to provide those information?

**Comment by R0oma1n** [comment]
I thought the informations given was sufficient. I give you the configurations as soon as possible.
And I thought you did not understand my problem at first.
I do not have the files on hand, I'll answer you tomorrow.

**Comment by pvdlg** [comment]
@R0oma1n do you still experience this issue? We'd really like to solve it if still the case.
If it still happening and you have access to your config and logs could you provide them?
Thanks!

**Comment by R0oma1n** [comment]
After a few tries, I managed to make the version system work the way I wanted it.
Thank you for your help and your work !

**Comment by pvdlg** [comment]
Thanks for letting us know! Feel free to open an other issue if you see the problem happening again.
