### ISSUE TITLE
Running on Travis CI tries to publish scoped package on npm

### ISSUE THREAD

**Issue by SirWindfield** [semantic-release/semantic-release#706]
## Current behavior
Running `semantic-release` on Travis CI does try to publish a scoped package by running `npm publish ./.`

## Expected behavior
It should run `npm publish`. Not sure why it tries to refer to a local dir/file instead.

## Environment

- **semantic-release** version: 15.1.2
- CI environment: Travis
- Plugins used: default, didn't change anything
- **semantic-release** configuration: https://github.com/SirWindfield/workspace-runner
- CI logs: https://travis-ci.org/SirWindfield/workspace-runner/jobs/354582377

**Comment by gr2m** [comment]
@SirWindfield I think the problem is your `publishConfig` https://github.com/SirWindfield/workspace-runner/blob/24b24636be707cd56c7f15fc5ca09e498965c492/package.json#L78-L80

The error at https://travis-ci.org/SirWindfield/workspace-runner/jobs/354582377#L525 says 

> Can't restrict access to unscoped packages

Which means you can’t restrict access for packages that don’t have a scope. It would work for `"name": "@sirwindfield/workspace-runner"` given you have the paid plan on npm

**Comment by SirWindfield** [comment]
Wow, I didn't see that I added that line of code. My fault, sorry.
Thank you for your help though @gr2m!
