### ISSUE TITLE
release fails because "git push --dry-run" fails with  "HEAD -> master (non-fast-forward)"

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#709]
## Current behavior

`semantic-release` is checking if it has write access with 

```
git push --dry-run https://[secure]@github.com/octokit/routes.git HEAD:master
```

It currently fails the release if the server rejects because it’s fast forward

```
! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://[secure]@github.com/octokit/routes.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
````

## Expected behavior

I think if we can take this error as a success, as we wouldn’t get it if we wouldn’t have write access, I assume?

## Environment

- **semantic-release** version: 15.1.2
- CI environment: Travis
- CI logs: https://travis-ci.org/octokit/routes/jobs/355627978#L2104

**Comment by pvdlg** [comment]
Do you know how we can test the push permission on a specific branch that wouldn't create this problem?

In such situation would creating a tag on the head commit and pushing it would work?

It seems this situation happens in the local branch on the CI is behind the remote branch. How can this happen?

**Comment by gr2m** [comment]
I think I pushed an update to `master` while the CI build was created on Travis, probably quite an edge case.

I wonder if we can ignore this error altogether? We just want to check if the token has write access, right?

**Comment by gr2m** [comment]
we create the tag using the API, don’t we?

**Comment by pvdlg** [comment]
No, we use `git push` with `execa`. The GitHub API is used only in the GitHub plugin to create the release.

Using `git push` has several advantages over using the GitHub API:
- Doesn't require to use the GitHub plugin
- Independent of the type of repo (GitLab, BitBucket, custom Git repo etc...)
- It allows us to create the tag in the core and control when the tag is created (after the prepare step and before the publish step)

That said even if we using the API that would create an other issue as we would create the tag on the wrong commit due to the discrepancy between the local and remote head.

I think we should still fail in such situation, but that would be great if we could display a more helpful error message in such situation.
Maybe we can add a test to make sure the remote head and the local head are the same.

Another solution would be to force a pull but that probably not a good idea as we would run semantic-release on a different code than the one on which the CI ran the tests.

**Comment by gr2m** [comment]
I remember now, thanks!

> Maybe we can add a test to make sure the remote head and the local head are the same.

Yes, that sounds good

> Another solution would be to force a pull but that probably not a good idea as we would run semantic-release on a different code than the one on which the CI ran the tests.

Agreed

**Comment by Arcanemagus** [comment]
> I think I pushed an update to master while the CI build was created on Travis, probably quite an edge case.

This isn't too edge of a case, it's pretty easy to hit if you are working on multiple PRs, don't require the PR to be up to date with `master`, and merge two close enough together that the CI build of the first to be merged hasn't hit the deploy stage before the second one is merged.

**Comment by felixfbecker** [comment]
I agree with @Arcanemagus. Even if you configure Travis to auto-cancel builds, I noticed it sometimes doesn't work. And you should always be able to rebuild an older build that failed without the release system tripping and therefor that build being broken forever. If the build is outdated, the best option would be if semantic-release noticed it and exited (not errors) to not override a newer release.

**Comment by demisx** [comment]
We get this error quite often with semantic release `15.13.27`. Just because the branch moved forward during execution of the release on CI.

**Comment by r4j4h** [comment]
We also get this error quite often with `15.13.30` as well.

**Comment by r4j4h** [comment]
@Arcanemagus is completely right.

By merging the changes it can complicate versioning for downstream users. We just encountered a situation where a fix was running, and someone from another team released a feature. We now only have a version with both things combined, semver'd as a feature. Now our downstream users have no way to pull only the fix without the feature, killing the entire point of semver in this case.
