### ISSUE TITLE
Dry run flag not working? (--dry-run)

### ISSUE THREAD

**Issue by benjamincharity** [semantic-release/semantic-release#722]
## Current behavior

- create a branch to batch my breaking changes: `release-8.0.0`
- add all changes
- run `npx semantic-release --dry-run` (this is run locally; not on CI)
- fails with error message about git-push permissions:

`[Semantic release]: EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch release-8.0.0 on remote Git repository.`

I have tried `-d`, `--dry-run`, `--dry-run true` and all have the same output.

## Expected behavior

According to the docs: `Dry-run mode, skip publishing, print next version and release notes.` So I would have expected the *next version to be printed out without pushing or releasing in any way*.

## Environment

- **semantic-release** version:
```
    "semantic-release": "^15.0.2",
    "@semantic-release/exec": "^2.2.3",
    "@semantic-release/github": "^4.2.8",
    "@semantic-release/npm": "^3.2.2",
```

- CI environment: N/A
- Plugins used: exec, github, npm (versions above)
- **semantic-release** configuration: 

> NOTE: I added the 'branch' option since without it semantic-release won't dry-run due to not being on the release branch.

```
  "release": {
    "verifyConditions": [
      "condition-circle",
      "@semantic-release/npm",
      "@semantic-release/github"
    ],
    "branch": "release-8.0.0",
    "publish": [
      {
        "path": "@semantic-release/exec",
        "cmd": "./tooling/ci/inject-version.sh ${nextRelease.version}"
      },
      {
        "path": "@semantic-release/npm",
        "npmPublish": true,
        "pkgRoot": "dist/terminus-ui"
      },
      {
        "path": "@semantic-release/github",
        "npmPublish": false
      }
    ]
  },
```

---

Any direction would be nice. Semantic-release has become a core component of our library builds, but releasing big changes is scary due to the inability to un-publish. I'd love to verify what will be published prior to the act of publishing.

**Comment by pvdlg** [comment]
The dry-run mode indeed skip publishing and print next version to be released.
The error you have is because you don't have push access to the remote repository.

The Dry-run mode verify the repository push permission, even though nothing will be pushed. The verification is done to help user figuring out potential config issue.

You should make sure the branch you running on exist on the remote repo and that you are allowed to push to it.

**Comment by pvdlg** [comment]
@benjamincharity did that solve your issue?

**Comment by benjamincharity** [comment]
I possibly don't really understand how the dry-run should be used.. Here is what I am hoping for:

- create new branch
- merge a bunch of work into this branch
- run dry-run to verify what _would_ be published on a merge to master

But this is where I'm blocked since semantic release just says this branch is not configured to publish. If I add `"branch": "my-branch",` under the `release` key I then get the 'push permission is required' error.

I am on my local machine and definitely have permission to push to the repo/branch.

**Comment by benjamincharity** [comment]
The same issue crops up really anytime I make any changes to semantic-release. Currently I'm trying to add the ability to generate a changelog.md. But there is no way to verify this will actually work until I merge and release. 

So I merge something, let the publish run and see that something was configured incorrectly. So now I need to push another hotfix release out to hopefully fix it.

I know I could set it up so that NPM doesn't publish to latest automatically but that doesn't solve the noisy commits/builds/tags. Plus it requires me to manually publish to NPM which happens ~7-10/week.

**Comment by pvdlg** [comment]
As mentioned in the doc and the CLI help message the `--dry-run` option just skip publishing, print next version and release notes. I don't think there is anywhere in the doc we suggest if would work the way you describe.

The dry-run mode isn't meant to run on a feature branch to test what would happen if you would merge it to the release branch. Running semantic-release on a PR (or on a feature branch) is currently not supported. This is something we might consider implementing in a GitHub app but there is a lot of unresolved challenges so far.

The objective of the dry-run mode is:
- Preview the first release for folks setting up semantic-release for the first time
- Preview the result for folks using releasing from their local machine instead of a CI

If you still want to do what you describe, locally, you can run `semantic-release --dry-run --branch <release-branch>`. That will work only if the `<release-branch>` exists on the remote repo (i.e. the PR was already opened). The result will be consistent only if the feature branch is not behind the release branch (i.e all the commits in `master` are present in the feature branch).

**Comment by benjamincharity** [comment]
Thank you for the very clear response. I understand the purpose much better.

---

Sorry for the noise.. just really trying to figure out how to be more confident in my releases. Having some way to say 'if this branch is merged into the current state of the release branch, here is what would happen' would be very helpful (especially as junior team members or new engineers begin helping out).

Thanks again for the explanation and the great tool!

**Comment by Etchs** [comment]
> Having some way to say 'if this branch is merged into the current state of the release branch, here is what would happen' would be very helpful

To achieve this goal without getting `push permission is required`:
1- Add `"branch": "branch-you-want-to-dry-run",` under the `release` key or in your `.releasesrc` file
2- Set the & environment variables on your local machine as stated here: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication
3- `npx semantic-release --dry-run`

**Comment by ysfaran** [comment]
> The objective of the dry-run mode is:
>- Preview the first release for folks setting up semantic-release for the first time
>- Preview the result for folks using releasing from their local machine instead of a CI

I would really like to see a simple solution also for CI setups. You should not have any disadvantage when you use the CI approach, which is IMHO the preferred one.
