### ISSUE TITLE
Found 0 commits since last release - despite commits

### ISSUE THREAD

**Issue by slkennedy** [semantic-release/semantic-release#723]
### Background Info
I previously setup semantic-release and travis on a repo and ran it successfully last week.  This week my org updated their npm account to an actual organization. 

Our practice is to push to a feature branch, merge to a staging branch and then finally to master where travis and semantic release run and push a publish if need be.

### Today
I pushed my work to a feature branch, then to the staging environment, then to master.  The build failed the first time because of an invalid NPM token ([the error](https://github.com/unumux/willow/issues/113)).  I assumed this was because of the organization account change. I created a new NPM Token on my account, set it in Travis and re-ran the build.

Now the build passes but it is not publishing b/c "Found 0 commits since last release"

## Expected behavior

The version is moving from 1.0.0 to 1.0.1. I thought that meant a publish to npm and a github release would be triggered.

## Environment

- **semantic-release** version: ^15.1.4
- CI environment: Travis-CI
- Plugins used: verifyConditions, analyzeCommits, generateNotes, prepare, publish, success, fail
- **semantic-release** configuration: [github](https://github.com/unumux/willow) /  [npm](https://www.npmjs.com/package/@unumux/willow)
- CI logs: https://api.travis-ci.org/v3/job/360372497/log.txt

**Comment by pvdlg** [comment]
semantic-release uses tags to determine the new commits between the last release and now.
semantic-release created the `v1.0.1` tag on the first run and failed to publish to npm due to the wrong token.

Then on the second run semantic-release tried to determine the new commits between the last tag (`v1.0.1`) and now and found none.

semantic-release tries to make as many checks as possible before creating the tag to avoid this situation, but it seems in your first run the checks passed even the token was invalid for publishing. It's because npm doesn't offer a way to check the permission of a npm token. We can only check that a token is set and valid but we cannot check if it allows to publish on a given orga.

To solve the problem you should delete the `v1.0.1` tag and run the CI job again.

**Comment by slkennedy** [comment]
Thanks @pvdlg - 

I deleted the tag (`git tag -d v1.0.1` and `git push origin :refs/tags/v1.0.1`) and re-ran the build in Travis.  This resolved the issue of no commits being found but still did not publish b/c of an npm 404 error. [current log](https://api.travis-ci.org/v3/job/361197353/log.txt)

I think this has something to do with our npm account changes, and isn't caused by semantic-release but wanted to share so you knew your support was helpful.

**Comment by pvdlg** [comment]
See https://github.com/npm/npm/issues/7932

It seems it's related to the permission of the npm user for the scope.
Is your package is public? If yes make sure to include the following in your `package.json`:
```
"publishConfig": {
  "access": "public"
}
```

**Comment by slkennedy** [comment]
I added the publishConfig setting with a previous push but that still didn't work. Started reviewing the [docs](https://www.npmjs.com/docs/orgs/) on npm organizations and found that our team had not been given read/write access to this repo in our new npm setup. So after adding that I am able to publish again.  

Thanks for your help @pvdlg
