### ISSUE TITLE
process.exit(1) in debug mode makes npm think there's an error

### ISSUE THREAD

**Issue by quarterto** [semantic-release/semantic-release#73]
[Here](https://github.com/semantic-release/semantic-release/blob/a7270bb84c13e803ca851e9426c2cef5071a583b/src/index.js#L115). It makes npm panic and output a debug log.

**Comment by boennemann** [comment]
Hey @quarterto,

this is entirely on purpose because we're still running `semantic-release pre && npm publish && semantic-release post` in series. If it weren't for `process.exit(1)` then `npm publish` would get executed next, which probably has some _very_ unintended side effects. Unfortunately [there is no way for us to fail an npm script without the verbose error log at the end](https://github.com/npm/npm/issues/7304).

Best,
Stephan

**Comment by quarterto** [comment]
Ok, thanks. I've added another script that runs `semantic-release pre || true`.

**Comment by boennemann** [comment]
Yeah, nice, looks like a good solution to get a version-preview command :+1:
