### ISSUE TITLE
Verify GitHub authentication false failure

### ISSUE THREAD

**Issue by Arcanemagus** [semantic-release/semantic-release#754]
# Bug report

## Current behavior

Specific commits fail GitHub authentication during deploy stage. The same configuration works for other commits, including to deploy a release.

## Expected behavior

If the configuration is valid, it should always work.

## Environment

- **semantic-release** version: [`^15.1.7`](https://github.com/semantic-release/semantic-release/releases/tag/v15.1.7)
- CI environment: Travis CI
- Plugins used: No extra plugins.
- **semantic-release** configuration: [`@semantic-release/apm-config@^2.0.1`](https://github.com/semantic-release/apm-config/releases/tag/v2.0.1)
- CI logs:
Passing build right before that: https://travis-ci.org/AtomLinter/linter-markdown/jobs/371682260
Failing build: https://travis-ci.org/AtomLinter/linter-markdown/jobs/371686321
Passing build of the commit directly after that: https://travis-ci.org/AtomLinter/linter-markdown/jobs/371686808 (_Note: this deployed a release_)

No CI configuration was changed between these builds. I tried restarting the job with the same results.

**Comment by felixfbecker** [comment]
I have the same problem, this commit consistently fails: https://travis-ci.org/felixfbecker/vscode-php-intellisense/jobs/371814953
The next commit always passes.

**Comment by pvdlg** [comment]
This is a duplicate of #709.

The problem happens if the Head commit on the local clone is behind the head on the remote, due to `git push` failing.

This is normal that we fail in this condition as we have to create a tag and push it and git won't allow to push if the local clone is behind the remote. We could force push but that's a bad idea as we would just erase some commits on the remote.

We need to improve the error message to:
- Log the git output
- Mention in can be due to authentication or due to the local repo being behind the remote

I think configuring Travis to cancel builds when a new commit is pushed on the branch should prevent this issue to happen. See https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation.

**Comment by Arcanemagus** [comment]
Ah, definitely a dupe of #709, sorry!

Hopefully future people searching for what I did will find this and be directed there 😉.
