### ISSUE TITLE
"do" is marked as secure and filtered from output

### ISSUE THREAD

**Issue by Arcanemagus** [semantic-release/semantic-release#773]
## Current behavior

It seems the characters `do` are currently being marked as secure tokens somehow, leading to it being replaced with `[secure]` everywhere in semantic-release's output.

This leads to text like this:

> Please refer to the authentication configuration [secure]cumentation (https://github.com/semantic-release/semantic-release/blob/caribou/[secure]cs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.

## Expected behavior

`do` not to be marked as a secure token.

## Environment

- **semantic-release** version: `^15.1.7` (15.2.0 tested)
- CI environment: Travis CI
- Plugins used: No extra plugins
- **semantic-release** configuration: [@semantic-release/apm-config](https://github.com/semantic-release/apm-config)
- CI logs: https://travis-ci.org/AtomLinter/linter-htmllint/jobs/373647402#L618

**Comment by pvdlg** [comment]
semantic-release look at all the environment variable containing the keywords `token`, `password`, `credential`, `secret` or `private` and replace their values in `stdout` and `stderr`.
So if you have an environment variable named 'SOME_CREDENTIAL' that contains the value `do` then `do` will be replaced in the log output.

I also noticed that Travis is replacing some keywords by `[secure]` as well. I don't know what the Travis algorithm is, but I noticed some weird cases in which a totally random string was replaced. So it's possible the case you mentioned is done by Travis and not by semantic-release.

Do you have any environment variable that would contains the value `do`?

**Comment by pvdlg** [comment]
Here is similar example where `do` is not replaced: https://travis-ci.org/mdn/bob/builds/364609477#L3816

Maybe you have an environment variable set to the value `do` by something else (a script)?

**Comment by pvdlg** [comment]
For info here is the code doing the replacement: https://github.com/semantic-release/semantic-release/blob/caribou/lib/hide-sensitive.js

**Comment by Arcanemagus** [comment]
Interesting, it must be something on Travis's part then, as [this script](https://github.com/atom/ci/blob/master/build-package.sh) is the only thing running there and it doesn't set any variable that would match that.

**Comment by pvdlg** [comment]
Only full match of the variable value is replaced.

**Comment by pvdlg** [comment]
If someone encounter the same issue, please provide:
- The semantic-release logs (or a link to the logs)
- The output of the `env` command

**Comment by pvdlg** [comment]
After further analysis  that happens because Travis set the environment variable `nvm_token` to the value `do`. This happens only in the `deploy` step for some reasons.

semantic-release considers that the content of the variable `nvm_token` is sensitive as the variable name contains `token` and then hide any instance of the value (`do`) from the output.

I'm not really sure what the proper fix is here.

When we detect the environment variables that might contains sensitive values we could exclude `nvm_token`. However the same problem might happens with other environment variables named `*token*`, `*credential*` etc...
Another solution would be to identify variable value as sensitive only if it has a minimum number of characters. I don't think any sensitive info (token, key, credential etc...) would be less than 5 characters.

Any though on that?

**Comment by pvdlg** [comment]
The problem is that plugins can use any environment variables, so there is no pre-defined whitelist.
The point of this feature was to prevent plugin to accidentally leak the user's credentials/tokens.

It can happens really easily without the plugin author noticing. For example if a plugin call a cli like that `some-cli --token <process.env.MY_TOKEN>`, and for some reasons the calls fails, it's likely the exception thrown will contains something like `The command some-cli --token value_of_the_token` will be logged.

The same can happens when you pass the token/credential to an API client that end up doing an http request with the token in a header. If an error happens it will likely contains information about the failed request, possibly including headers.

**Comment by travi** [comment]
> The problem is that plugins can use any environment variables, so there is no pre-defined whitelist.

ok, that makes sense.

remind me, i assume this filtering is intended for non-travis ci services, correct? i'm fairly certain travis expanded it's own filtering of values that are stored in encrypted environment variables. thats my normal use case, so this isn't really an issue in that context, but i know `semantic-release` needs to support more than travis.

**Comment by pvdlg** [comment]
Yes this is meant for any CI. It seems Travis does indeed hide that value contained in secured environment variables. I think it also hide other stuff but I don't know what are the rules.

And yes we support a lot more than Travis. I don't know which other CIs also hide value of environment variable in the log output, but I'm sure there is some that doesn't. And better be safe than sorry....

I think such feature is really important because we ask users to trust us with their tokens/credentials, and we don't want to "transfer" that trust to a third-party like the CI or a plugin author. Ideally, the semantic-release users should decide if they trust their CI and the plugins they are using, but I don't think it's reasonable to expect that.

Just a slightly related FYI point: In all CI the environment variables are available only for builds that runs on the repository itself, and not on forked ones.
So it means:
- Forking a repo and opening a PR that contains `sendToMyServer(process.env.NPM_TOKEN)` will not expose the token. `process.env.NPM_TOKEN` will be `undefined`.
- As a repo maintainer you have to make sure such code doesn't end up on your own repo, otherwise the token will be leaked. Basically, you have to make sure to not merge PRs that introduces malicious code, but that's not specific to using semantic-release.

**Comment by travi** [comment]
> And yes we support a lot more than Travis. I don't know which other CIs also hide value of environment variable in the log output, but I'm sure there is some that doesn't. And better be safe than sorry....

agreed in those cases. the part is was wondering about though was whether that opened any possibilities in this specific case since this is limited to travis.

> Just a slightly related FYI point: In all CI the environment variables are available only for builds that runs on the repository itself, and not on forked ones.

this is actually one of the reasons that i'm such a fan of travis. it is intentionally built for workflows involving PRs from internal branches as well as third-party contributions. configuring other CIs to follow even close to the same behavior is a _pita_. however, many users are unaware of some of the benefits like this one, so this is definitely a detail worth calling out for awareness.
