### ISSUE TITLE
Cleanup .npmrc files before publish?

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#78]
I see `.npmrc` files in the published packages, and now for the first time saw a `Failed to replace env in config: ${NPM_TOKEN}` error when testing a module. No idea where this comes from, but the `.npmrc` files are the only ones that contain that string.

My test script runs `npm start` in a node_modules folder, so maybe it's a change in npm?

To reproduce the issue, try

```
git clone git@github.com:eHealthAfrica/kazana.git
cd kazana
npm install
npm test
```

if the app won't start, check logs in `node_modules/integration-test/log/app.log`. 

After removing `node_modules/integration-test/.npmrc`, things worked as expected

```
$ node -v && npm -v
v0.10.32
2.13.3
```

Any idea?

**Comment by boennemann** [comment]
Unfortunately we can't clean this file up before publish, because npm needs it during publish. The best solution would be to store the `.npmrc` file outside of the package folder, but we don't have sufficient permissions to do so on e.g. travis. The easiest workaround for this is adding `.npmrc` to your `.npmignore` file.
