### ISSUE TITLE
semantic-release errors for 2 consecutive pushes to master

### ISSUE THREAD

**Issue by finnp** [semantic-release/semantic-release#793]
## Current behavior

When you push to master while another master build is still running, you get the error:
```
semantic-release cannot push the version tag to the branch master on remote Git repository.
```

## Expected behavior

It should not error. The problem is that you check for git push access by doing a `git push --dry-run`. However this fails because there would be a conflict with the new master that has been pushed. So that doesn't work for testing push access.

## Environment

- **semantic-release** version: 15.4.1
- CI environment: Travis

**Comment by pvdlg** [comment]
The test with `git push --dry-run` has been implemented a while ago and seems to work so far.

Can you clarify what you mean by "this fails because there would be a conflict with the new master that has been pushed"? What is the "new master that has been pushed"? The test with `git push --dry-run` happen before pushing anything so I'm confused. How can there be a conflict between the remote branch and the local one on the cloned repo?

If you refer to a situation in which the local cloned branch happens to be behind the remote branch (i.e. you push a commit to the remote repo after the CI build started but semantic-release runs) then it should have been handled in https://github.com/semantic-release/semantic-release/pull/759.

Could you provide the full logs with the `--debug` option?

**Comment by finnp** [comment]
Yep the problem is that the CI build is behind the remote:
```
[Semantic release]: The command "git push --dry-run https://[secure]@github.com/[secure].git HEAD:master" failed with the error message To https://github.com/[secure].git
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://[secure]@github.com/[secure].git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

To make sure it is not failing in this case you could do `git push --dry-run --force`.

**Comment by pvdlg** [comment]
Are you sure you are using `15.4.1`? This case should have been handled in #759 which was released in `15.1.10`.
Now if the local repo is behind the remote we log a message and exit without error.

Using `git push --dry-run --force` is not a good idea because later on in the process we'll have to push a tag. If we push the tag without `--force` it will fails as well (so we prefer to fails earlier before any release is attempted) and if we push it with `--force` we will erase the commits on remote that are not present in the local branch.

**Comment by finnp** [comment]
Might be that that was using a version before `15.4.1`. Closing this for now.

**Comment by finnp** [comment]
This is still happening as of `15.5.1`.

**Comment by pvdlg** [comment]
Can you provide some logs or some context to analyze exactly what cause the issue?

**Comment by adeelibr** [comment]
I have the same issue.

**Comment by adeelibr** [comment]
I have a working demo where I have 2 builds running every-time i merge to master.

https://github.com/adeelibr/learn-semantic-release/commits/master

I am using TravisCI for this, can anyone kindly tell what is it that I am doing wrong here?

Also after every release my package-lock.json file updates..

Can you kindly point me in the right direction as to what I am doing wrong @pvdlg
