### ISSUE TITLE
Major version upgrade of the engine is not treated as a breaking change

### ISSUE THREAD

**Issue by halfzebra** [semantic-release/semantic-release#830]
First of all, thank you for semantic-release 🙂

I'm experiencing an issue, which is not exactly falling into given categories.

## Current behavior

semantic-release and its dependencies maintained by the semantic-release organization are upgrading the major version of the engine(Node) without marking this as a breaking change.

If the library is  using semantic-release with Travis CI and supports older versions of Node, engine upgrade to higher version will cause the build task to break, like [here.](https://travis-ci.org/halfzebra/create-elm-app/jobs/394634319)

## Expected behavior

Mark engine upgrades as breaking change, so users can rely on older versions if they need to support older versions of node.

## Environment

- **semantic-release** version: @12
- CI environment: Travis CI
- Plugins used: Not relevant
- **semantic-release** configuration: Not relevant
- CI logs: https://travis-ci.org/halfzebra/create-elm-app/jobs/394634319

**Comment by gr2m** [comment]
I think semantic-release requires node 8 since version 12: https://github.com/semantic-release/semantic-release/releases/tag/v12.0.0. I think the current version should still work with it?

**Comment by halfzebra** [comment]
@gr2m Node 8 was introduced only in [v12.2.0](https://github.com/semantic-release/semantic-release/blob/v12.2.0/package.json#L67)

At the same time, [@semantic-release/commit-analyzer](https://github.com/semantic-release/commit-analyzer/blob/v5.0.2/package.json) got an engine version bump in a minor version(`5.0.1->5.0.2`), which did break the build for me.

I'm not sure if anything could be done about my issue with semantic-release, I wanted to raise awareness that engine version bumps are introducing breaking changes.

I think that engine upgrade should be reflected as a new major version. I hope that makes sense 🤔

**Comment by pvdlg** [comment]
Your remark make sense. We had a bit a floating period in which we were not sure how to handle the relationship between plugins and the core.
In the case you mention, `@semantic-release/commit-analyzer@5.0.x` was not really meant to work with older version of `semantic-release`.
We now have a more stable system in place and each (or at least most) plugins require a specific version of `semantic-release` via `peerDependencies`.
Currently we do not maintain older versions of `semantic-release`. That means versions `12.x.x`, to `14.x.x` probably have bugs and plugin incompatibilities that have been addressed in later releases, but won't be fixed in those versions.

Once #563 lands we might adopt a different policy and backport some of the fixes to previous version. The feature should be completed soon (all the code for the core, minus the doc, is in [multi-branches](https://github.com/semantic-release/semantic-release/tree/multi-branches) but I have to modify some plugins). However, we are currently in version `15.x.x` and you are using `12.x.x`, and it's unlikely that we continue to support 3 major release back. So I would recommend to upgrade to the latest version, it comes with a ton of fixes and new features.

**Comment by halfzebra** [comment]
Thanks for the feedback! :+1: 

I do understand that it would be too much of a pain to include backward compatibility for addressing my issue.

I've thought it would be healthy to share, so so this issue could be avoided in the future.

**Comment by pvdlg** [comment]
I'm going to close this issue then. You should really upgrade to the last version.
