### ISSUE TITLE
Different repository URL for connection and for writing

### ISSUE THREAD

**Issue by jormot** [semantic-release/semantic-release#831]
## New feature motivation

I have configured a custom host in my `.ssh` file, to be able to work with different private keys on the same host. So for using one key I use `git@githubcustom:myusername/myproject.git`, and for another I use `git@github.com:myusername/myproject.git`.

In the project using `semantic-release` I'm using the custom one. But since that URL only makes sense on my machine, in the `package.json` I have the normal one (`@github.com`, instead of `@githubcustom`).

The issue is that when generating the changelog, it's trying to connect to the normal one (`@github.com`) instead of the correct one. And if I change the URL in `package.json` or via options, it's connecting OK, but in the changelog it's using the one at `@githubcustom`, because I'm not able to send it a different URL.

## New feature description

Be able to connect to the repository using the remote at `.git/config` instead of the one provided, and use the one provided for creating the changelog and the links.

That way people with different configurations would be able to have a working changelog.

**Comment by pvdlg** [comment]
What is the point of having different ssh private keys on the same host?

**Comment by jormot** [comment]
I have a pem generated with my work laptop, which I use for a specific Github account (different from my personal one).

I can't use the works laptop at home, so when I have to take work to home, I use my personal computer, which already has a pem, which is also associated with a different Github account and other accounts as well.

Copying pasting my personal pem to works laptop wouldn't be very wise, so what I can do is to copy the work pem to my personal computer and add a different host in the `.ssh` config.

Right not the host that it's changed (`githubcustom`) is the one I'm trying to use with `semantic-release`

**Comment by pvdlg** [comment]
Even if we support running locally, semantic-release is mainly intended to run on a CI and the problem you describe wouldn't exist in a CI environment. I don't think it's a feature we would implement as it would only solve a very specific case (your work/home laptop setup) for a very limited number of users (I imagine only you).

I would suggest in your case to investigate other solutions, for example:
- Using a token instead of ssh keys
- Using the same GitHub account when you work on that specific project rather than having a specific one for different laptop
- Find tools that allow to manage your ssh keys with more flexibility

**Comment by jormot** [comment]
I do use a token (with `GH_TOKEN`), but when trying to connect to the server, `semantic-release` uses the `repositoryUrl` provided, instead of the one defined at `.git/config`.

It would be great if you could give more priority to the remote at `.git/config` for connecting, and use the one defined at `package.json` for appearance (writing `CHANGELOG.md`).

**Comment by jormot** [comment]
How do you suggest I use a CI in my setup? Can you quickly describe a high overview of the process?

**Comment by pvdlg** [comment]
> I do use a token (with GH_TOKEN), but when trying to connect to the server, semantic-release uses the repositoryUrl provided, instead of the one defined at .git/config.

Then you should configure the repository URL in your `package.json` as an `http` URL rather than a `git` (ssh) one, so semantic-release would use the token to authenticate instead of the ssh key.

> It would be great if you could give more priority to the remote at .git/config for connecting, and use the one defined at package.json for appearance (writing CHANGELOG.md).

It's not always possible to control the remote URL set by the CI environment in `.git/config`. However it is possible for users to configure the URL they want to use in their `package.json` or via CLI option. Therefore we choose to use the one set by the user first, and the one set by the CI during the repo cloning second.

> How do you suggest I use a CI in my setup? Can you quickly describe a high overview of the process?

The high overview of the semantic-release process is the [README.md](https://github.com/semantic-release/semantic-release/blob/caribou/README.md).

**Comment by jormot** [comment]
I have created a PR at https://github.com/semantic-release/release-notes-generator/pull/89 that will fix my issue, by adding a custom `repositoryUrl` option for this plugin.
