### ISSUE TITLE
Rate limit reached on big release

### ISSUE THREAD

**Issue by bodinsamuel** [semantic-release/semantic-release#843]
## Current behavior
(it's more related to the github plugin, but as it is activated by default I prefer to put it here)

I got plenty of 403 even on a local run (like some bug reports before me), until I figured it out.
When you have too much commit in a version, and the success from `@semantic-release/github` still activated it will try to do too much things and break without warning.
The logging is not enough verbose to understand that it's failing at this step, it actually stall for a long time then print this error:
```bash
[...]
[Semantic release]: Published GitHub release: https://github.com/redacted/redacted/releases/tag/v1.0.0
[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"API rate limit exceeded for user ID 1637651.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    at response.text.then.message (/Users/redacted/code/redacted/node_modules/@octokit/rest/lib/request/request.js:78:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 403,
  status: undefined,
  headers: 
[...]
```

## Expected behavior
This is an extreme scenario with 1 year of commits mostly PR and issues for each. But the logging should be more explicit to understand what is going, because debugging in CI is impossible.
Maybe the github plugin should try to stay in the rate limit boundary, even if that mean slowing down the whole task.

## Environment

- **semantic-release** version: 15.6.1
- CI environment: travis/local
- Plugins used: github,npm,changelog
- CI logs + config: https://gist.github.com/bodinsamuel/76e787a0efe9c946fff6877e9820f11d

**Comment by pvdlg** [comment]
GitHub limit API calls to 5000 per hour for each users: https://developer.github.com/v3/rate_limit/

We already have a throttling mechanism in the `@semantic-release/github` that limits 1 call every 720ms (which result in 5000 calls per hour maximum).

The problem happens when you have other things using the API with the same user, as the 5000 per hour limit is shared across all the API calls for the same user.

Currently the throttling mechanism in `@semantic-release/github` is relatively basic. In order to prevent this problem we would have to implement the throttle with a bucket of tokens that we would consume/refill based on the `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers.

@gr2m we talked at some point to have such feature implemented directly in the Octokit client. Do you know if it is still planned?

@bodinsamuel do you have a repo that I could fork and use to try to reproduce the problem?
How many commit, issues, PRs do you have in the repo?

**Comment by bodinsamuel** [comment]
hi @pvdlg 
great to here there is already something in place 👍 

I'm sorry this is a private repo, but I'v provided the redacted log, there was 1065 commits most of them related to one PR and at least one or more issues ! So you can imagine how huge it could be.
I don't know if it's really worth investigating for you, I'm probably the only having this kind of issue because it was a really old repo. 

I think the only way to reproduce would be to create a big repo with thousand of commit and launching the cli :D

**Comment by gr2m** [comment]
> @gr2m we talked at some point to have such feature implemented directly in the Octokit client. Do you know if it is still planned?

Yes it’s planned, I’m not working on it yet, but hope to soon, as in over the next 2-4 weeks

**Comment by pvdlg** [comment]
Ok, so I'll wait for that then. It's pretty complex issue to solve...and test....

For info see https://github.com/SGrondin/bottleneck/issues/51, especially https://github.com/SGrondin/bottleneck/issues/51#issuecomment-370641192 which should allow to implement the feature.

**Comment by travi** [comment]
while updating npm tokens, i found a package that i missed updating to a recent version of `semantic-release`, so it had lots of commits since the last publish, similar to what is described above. it hit rate limits as described above as well.

since this is public, here is a link to the [failed build](https://travis-ci.org/dsmjs/commitlint-config-dsmjs/builds/403821745#L1691-L1717) in case it is helpful. the plan to wait for octokit handling of this seems totally reasonable. i have no reason to add any time pressure, just providing some additional detail.

**Comment by pvdlg** [comment]
Your case seems different as it was detected as an abuse, which happens when your account make more than 1 write query per second.
This shouldn't happens as we throttle to 1 call per second...So either their is a bug and the throttling doesn't work either you have other stuff (maybe other semantic-release instance) running at the same time. From the date of failed errors it seems the throttling works.
Did you had other stuff running using the GitHub API at the same time?

In any case I think we can catch this specific 403 errors and block the execution for the time indicated in `Retry-After`.

**Comment by travi** [comment]
plus this is a [bot account](https://github.com/dsmjs-bot) that has a pretty small list of repos that it interacts with.

**Comment by pvdlg** [comment]
The API doc is not super specific about what's considered rate abuse: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

They mention `wait at least one second between each request`. We do wait 1 second between each requests.  I just tested and I can confirm it works as expected.

Maybe GitHub detect an abuse as we do a lot of similar calls and even if we wait 1 second in between they consider that suspicious...I don't know how to figure out what is the appropriate rate though...

**Comment by travi** [comment]
yeah, hard to say. this is the first time i've ever seen it and it was only because of a backup due to a misconfiguration. i'm happy to provide more examples if i end up seeing more, but it seems unlikely that this will cause me enough trouble to worry too much about.

**Comment by pvdlg** [comment]
I guess this part from the API doc is interesting:
> Requests that create content which triggers notifications, such as issues, comments and pull requests, may be further limited and will not include a Retry-After header in the response. Please create this content at a reasonable pace to avoid further limiting.

Creating comments does generate a notification. So It's limited to less than 1 per second. But it's not clear when GitHub consider it an abuse. In addition they don't return the `Retry-After` header so there is no to know for how long to wait to continue.

**Comment by pvdlg** [comment]
I can set a different throttler for the command that create notifications. But not sure what the proper interval should between requests...I'll try to test a bit more to figure out when does GitHub consider it an abuse.
