### ISSUE TITLE
AWS CodePipeline and git metadata

### ISSUE THREAD

**Issue by tbrunia** [semantic-release/semantic-release#870]
I'm using `semantic-release` with AWS CodePipeline. I discovered that CodePipeline does not pass the `.git` folder from one stage to the next. This is a problem b/c my `semantic-release` stage is downstream of the stage that downloads my project's source code from GitHub.

https://forums.aws.amazon.com/thread.jspa?threadID=248267

When running `semantic-release` version 15.8.1, I get the following error.

> This test run was triggered on the branch undefined, while semantic-release is configured to only publish from master, therefore a new version won’t be published.

Is there a work around I can apply to force `semantic-release` to think that it's working with code from my master branch? If not, are there any other suggestions to address this problem?

**Comment by pvdlg** [comment]
I don't think that can be solved because semantic-release needs to run from a Git repository to:
- Find the last release by reading the Git tags
- Retrieve the commits since the last release
- Create and push a tag

So if you don't have the `.git` directory in your project semantic-release cannot do any of that.

**Comment by pvdlg** [comment]
I'm going to close this as there is nothing we can without the `.git` directory.
