### ISSUE TITLE
Major Release does not get trigger

### ISSUE THREAD

**Issue by leocwlam** [semantic-release/semantic-release#890]
## Current behavior

I tried to 2 separate commits with 
perf(Refactoring): Major refactoring
and 
BREAKING CHANGE: Major Release
The version changes from v1.3.2 to v.1.3.3

## Expected behavior
I expected semantic-release, which should change from v2.0.0
when I use either perf(Refactoring): ... or BREAKING CHANGE: ....

## Environment

- **semantic-release** version: 15.9.4
- CI environment: https://travis-ci.org/leocwlam/system-logger
- Plugins used: no plugins
- **semantic-release** configuration: https://github.com/leocwlam/system-logger/blob/master/.travis.yml
- CI logs: https://api.travis-ci.org/v3/job/413748587/log.txt

![majorrelease](https://user-images.githubusercontent.com/35342488/43861207-24d668e8-9b24-11e8-98eb-4e890096c2d1.png)

**Comment by pvdlg** [comment]
That's because none of those commit follow the [Angular convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits).

Per the convention a breaking change has to be indicated by a `BREAKING CHANGE` note in the footer of the commit.

[Your first commit](https://github.com/leocwlam/system-logger/commit/3475da1766e736bb3e4cc9393925f35b497a246f) is not formatted like a breaking change commit. It just happens to contains the works "major" in the subject...but is formatted like a `perf` commit.

[Your second commit](https://github.com/leocwlam/system-logger/commit/55a310f01ffacbea22ed7cce005928a4e2c68d3e) just `BREAKING CHANGE` in the subject but doesn't have a body or a footer and therefore doesn't contains `BREAKING CHANGE` in the footer.
