### ISSUE TITLE
Expose the path of the configuration file to plugins for better path resolution.

### ISSUE THREAD

**Issue by momocow** [semantic-release/semantic-release#990]
## New feature motivation
When the configuration of a plugin contains paths, for examples paths to template files for generating release notes, users may also provide relative paths in their configuration.

Currently, plugins can only resolve those paths based on `process.cwd()`, but it is more intuitively that those relative paths are resolved from where the configuration comes from.

## New feature description
As the title reads, expose the path of the configuration file to plugins for better path resolution.

## New feature implementation
More pratically, I think the path is already right there in the [`get-config.js#L23`](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-config.js#L23), which is parsed from `cosmiconfig`.

Add the path to the context object so plugins can exploit the path to perform resolution.
(`context.configFile`?)

Thanks. 😄

**Comment by pvdlg** [comment]
It's actually a bit more complex than that due to [shareable configuration](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/shareable-configurations.md).

You can have the following project structure:
```
my-project
├── package.json
├── node_modules
│   ├── my-shareable-config
│   │   ├── index.js
│   │   ├── my-template.hbs
```
In that case the template is embedded in the `my-shareable-config` package, so you won't be able to load it by just knowing the path of the semantic-release config.

And that can also happens with the dependency of a dependency and so on. So I'm not there is a good way to define which path is the right one to load dependencies from.

Maybe an easier way is to configure semantic-release with a [`release.config.js`](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#configuration-file) file so you can import your template file there.
Similarly if you create a shareable config you can import your template from there as a shareable config is a JS module.
In that situation your plugin would receive a string for the template with the content of the template rather than the path.

**Comment by momocow** [comment]
Oops, I just missed to think about shareable configurations. I'll keep that in mind.

Usually, I would like to make my configuration files a bit "less logical" as possible, that is, keep them static files instead of scripts. But it seems a `release.config.js` file is the best choice now to simplify path resolution due to the deep and complicated structure of Nodejs package system.

Also, I found that the configuration is merged into an object that makes it impossible to trace back where a certain path in the value of config came from.

**Comment by pvdlg** [comment]
Unfortunately, as far as I know there is no good solution for this kind of problems. Passing the main semantic-release config path might solve your issue in one specific case, but it will open the door to many situations that are even more broken.

Passing the path of the config implicitly makes that it's a "supported feature". And it won't work in case of a shareable config, because there is no way to know if the file would have to be loaded relatively to the main config or relatively to the shareable config.

So we won't implement this at this point.

You have different solutions though:
- Mention in your docs that in order to customize the template a `release.config.js` must be use and load the template. In that case your option expect the content of the template.
- Or mention that the path to the template must be relative to the root of the project (which is where semantic-release should run from). In that case your option expect a path to the template.

**Comment by momocow** [comment]
That's all right, it's kind of virtualization that semantic-release brings to plugins, and plugins should avoid trying to resolve the actual project structure to maintain the flexibility.
In this case, delegating those works to users seems the best choice.

Thanks for your support!
