### ISSUE TITLE
[Question] How to bump major using commit messages?

### ISSUE THREAD

**Issue by kopax** [semantic-release/semantic-release#998]
Hi and thanks again for the great work.

We are experience two issues and one is pretty annoying as it does not reflect what is written in the documentation.

When we use `perf(....): ..... BREAKING CHANGE ....` it does not bump the major version. So far we have not found at to release a new major without manually do `git tag`.

Are we the only one ? We have tried with many semantic-release version.

**Comment by travi** [comment]
major bumps have been working fine for us with the default convention. 

it's hard to tell from what you show above, but are you putting the `BREAKING CHANGE: ` in the subject or the body? it must be in the body and be exact (notice the `:` that i included that you did not above). 

i also tend to typo things like that, so i prefer to use [commitizen](https://commitizen.github.io/cz-cli/) to format the message rather than type it manually, only to learn that i had a typo after it published differently than i intended.

**Comment by kopax** [comment]
@travi, I've been trying a few times with the following commit message:

- `perf(babel): babel 7 BREAKING CHANGE\nUse version 0.18.1`
- `perf(cli): BREAKING CHANGE cli now use @babel/node during test`

You are right to say it does not include the `:`. Is this really a requirement ? What about the fact of having `perf` shouldn't that be enough for major?

I really like commitizen but found it convenient to also write short message in one line.

**Comment by pvdlg** [comment]
@kopax you already asked this question [here](https://gitter.im/semantic-release/semantic-release?at=5bf6cfdca115c91ef7768d41) and someone else already told you that you won't be able to get help if you don't provide any details.

I'm mentioning it because it became a recurring problem where you ask a question with no details, context or error messages, forcing other to chase you for informations. That's actually something mention in you [guidelines](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#bug-report).

You won't get any answer to such vague question because no one can just guess the answer without information to analyze. Then when you see that you open an issue to force an answer from the maintenance team. 

People maintaining this project and helping out on the chat/issue tracker are not paid and have no obligation to provide support, they are all volunteer doing so on their free time as a hobby. Try to put your self in the shoes of someone susceptible to help you. Would you take on your free time to help someone who doesn't even bother including the problematic commit message, or the link to the repo, or the CI logs?

So please provide those information on this issue and for future questions. You might not figure out what to provide right away, but at least try to provide some common sense things: commit message, repo link, semantic-release logs.

**Comment by pvdlg** [comment]
I would assume you are using the Angular commit convention...So please read: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#footer.

The `BREAKING CHANGE` part as to be in the footer. A oneliner commit is not a valid breaking change commit per the convention.

**Comment by kopax** [comment]
Dear @pvldg, sorry for the confusion. I did ask twice in 30 minutes interval. I am using a IRC client and I must admit that I forgot Gitter was also a website and support platform. For some reason my IRC client did not blink on your replies, I wish I would have seen them earlier to prevent that. 

That doesn't excuse the absence of details here, I sincerely apologize.

- semantic-release: 15.12.1.

I do use angular commit convention (which are default for commitzen), thanks for pointing that link, I will always remember to be more specific. Thanks for the awesome work and supporting some users.

Best regards,
